"use client"

import { useState, useEffect, useCallback } from 'react'
import {
  Target, Calendar, X, Loader2, Sparkles, Clock,
  Download, Maximize2, ChevronLeft, ChevronRight,
  RefreshCw, CheckCircle2,
} from 'lucide-react'

interface DayPlan {
  day: number; focus: string; task: string; duration: string; tip: string
}
interface CountdownData { company: string; date: string; plan: DayPlan[] }

const COMPANIES = ['OpenAI','Anthropic','Google','Meta','Microsoft','Amazon','Nvidia','Hugging Face','Apple','Other']
const STORAGE_KEY = 'interview_countdown'

const TOPIC_COLORS: Record<string, string> = {
  LLM: 'bg-blue-500/20 text-blue-300', RAG: 'bg-violet-500/20 text-violet-300',
  Agents: 'bg-orange-500/20 text-orange-300', 'Fine-Tuning': 'bg-yellow-500/20 text-yellow-300',
  MLOps: 'bg-green-500/20 text-green-300', Transformers: 'bg-teal-500/20 text-teal-300',
  Behavioral: 'bg-rose-500/20 text-rose-300', Python: 'bg-lime-500/20 text-lime-300',
  Statistics: 'bg-amber-500/20 text-amber-300', 'System Design': 'bg-red-500/20 text-red-300',
  'Vector DB': 'bg-pink-500/20 text-pink-300', 'Computer Vision': 'bg-cyan-500/20 text-cyan-300',
}
function topicColor(focus: string) {
  const key = Object.keys(TOPIC_COLORS).find(k => focus.toLowerCase().includes(k.toLowerCase()))
  return key ? TOPIC_COLORS[key] : 'bg-zinc-700/40 text-zinc-300'
}

function daysUntil(dateStr: string): number {
  const target = new Date(dateStr); target.setHours(0,0,0,0)
  const today  = new Date();        today.setHours(0,0,0,0)
  return Math.ceil((target.getTime() - today.getTime()) / 86400000)
}
function todaysPlan(plan: DayPlan[], dateStr: string): DayPlan | null {
  const dayIndex = plan.length - daysUntil(dateStr)
  return plan[Math.max(0, Math.min(dayIndex, plan.length - 1))] ?? null
}

// ─── Full Plan Modal ──────────────────────────────────────────────────────────

function PlanModal({ data, onClose, onRegenerate }: {
  data: CountdownData; onClose: () => void; onRegenerate: () => void
}) {
  const [downloading, setDownloading] = useState(false)
  const days       = daysUntil(data.date)
  const dateLabel  = new Date(data.date + 'T12:00:00').toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })
  const todayIdx   = Math.max(0, data.plan.length - days)

  const downloadPDF = useCallback(async () => {
    setDownloading(true)
    try {
      const { default: jsPDF } = await import('jspdf')
      const doc  = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      const pw   = doc.internal.pageSize.width
      const ph   = doc.internal.pageSize.height
      const ml   = 18
      const mr   = pw - ml
      let   y    = 20

      // Header
      doc.setFillColor(20, 20, 20)
      doc.rect(0, 0, pw, 28, 'F')
      doc.setTextColor(249, 115, 22)
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      doc.text('AmanAI Lab', ml, 12)
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(11)
      doc.text(`${data.company} Interview Prep — ${data.plan.length}-Day AI/ML Plan`, ml, 20)
      doc.setTextColor(180, 180, 180)
      doc.setFontSize(8)
      doc.text(`Interview: ${dateLabel}  |  Generated by amanailab.com`, ml, 26)
      y = 36

      // Plan days
      for (const d of data.plan) {
        const isToday = d.day === (todayIdx + 1)
        const blockH  = 22 + (d.tip ? 5 : 0)

        if (y + blockH > ph - 15) {
          doc.addPage()
          y = 15
        }

        // Day badge
        if (isToday) {
          doc.setFillColor(249, 115, 22)
          doc.roundedRect(ml, y - 3, 14, 5.5, 1, 1, 'F')
          doc.setTextColor(255, 255, 255)
        } else {
          doc.setFillColor(40, 40, 40)
          doc.roundedRect(ml, y - 3, 14, 5.5, 1, 1, 'F')
          doc.setTextColor(150, 150, 150)
        }
        doc.setFontSize(7)
        doc.setFont('helvetica', 'bold')
        doc.text(`Day ${d.day}`, ml + 1.5, y + 0.5)

        // Focus topic
        doc.setTextColor(isToday ? 249 : 220, isToday ? 115 : 220, isToday ? 22 : 220)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'bold')
        doc.text(d.focus, ml + 17, y)

        // Duration
        doc.setTextColor(120, 120, 120)
        doc.setFontSize(8)
        doc.setFont('helvetica', 'normal')
        doc.text(d.duration, mr, y, { align: 'right' })
        y += 6

        // Task
        doc.setTextColor(80, 80, 80)
        doc.setFontSize(8)
        const taskLines = doc.splitTextToSize(d.task, mr - ml - 17)
        doc.text(taskLines, ml + 17, y)
        y += taskLines.length * 4.5

        // Tip
        if (d.tip) {
          doc.setTextColor(180, 120, 60)
          const tipLines = doc.splitTextToSize(`Tip: ${d.tip}`, mr - ml - 17)
          doc.text(tipLines, ml + 17, y)
          y += tipLines.length * 4.5
        }

        // Separator
        y += 3
        doc.setDrawColor(235, 235, 235)
        doc.line(ml, y, mr, y)
        y += 4
      }

      // Footer
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const pages = (doc as any).internal.getNumberOfPages() as number
      for (let i = 1; i <= pages; i++) {
        doc.setPage(i)
        doc.setTextColor(160, 160, 160)
        doc.setFontSize(7)
        doc.text(`Page ${i}/${pages} · AmanAI Lab — amanailab.com`, pw / 2, ph - 6, { align: 'center' })
      }

      doc.save(`${data.company.replace(/\s+/g, '_')}_${data.plan.length}Day_AI_ML_Plan.pdf`)
    } catch (e) {
      console.error('PDF error', e)
    } finally {
      setDownloading(false)
    }
  }, [data, dateLabel, todayIdx])

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/75 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-2xl bg-zinc-900 border border-zinc-700 rounded-2xl shadow-2xl shadow-black/60 flex flex-col max-h-[90vh]">

        {/* Modal header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-zinc-800 shrink-0">
          <div>
            <h2 className="text-base font-bold text-zinc-100">{data.company} — {data.plan.length}-Day AI/ML Plan</h2>
            <p className="text-xs text-zinc-500 mt-0.5 flex items-center gap-1">
              <Calendar className="w-3 h-3" /> {dateLabel} · {days} days remaining
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={onRegenerate}
              className="flex items-center gap-1.5 text-xs text-zinc-400 hover:text-zinc-200 bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 px-3 py-1.5 rounded-lg transition-colors">
              <RefreshCw className="w-3.5 h-3.5" /> Regenerate
            </button>
            <button onClick={downloadPDF} disabled={downloading}
              className="flex items-center gap-1.5 text-xs font-semibold bg-orange-500 hover:bg-orange-400 disabled:opacity-50 text-white px-3 py-1.5 rounded-lg transition-colors">
              {downloading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
              {downloading ? 'Generating…' : 'Download PDF'}
            </button>
            <button onClick={onClose} className="p-1.5 hover:bg-zinc-800 rounded-lg transition-colors">
              <X className="w-4 h-4 text-zinc-500" />
            </button>
          </div>
        </div>

        {/* Plan list */}
        <div className="overflow-y-auto flex-1 px-5 py-4">
          <div className="flex flex-col gap-2">
            {data.plan.map((d, i) => {
              const isToday = i === todayIdx
              const isPast  = i < todayIdx
              return (
                <div key={d.day}
                  className={`flex gap-3 p-3.5 rounded-xl border transition-all ${
                    isToday  ? 'bg-orange-500/8 border-orange-500/30 ring-1 ring-orange-500/20' :
                    isPast   ? 'bg-zinc-800/20 border-zinc-800/50 opacity-60' :
                               'bg-zinc-800/30 border-zinc-800/60'
                  }`}>
                  {/* Day number */}
                  <div className={`w-10 h-10 rounded-xl flex flex-col items-center justify-center shrink-0 ${isToday ? 'bg-orange-500' : isPast ? 'bg-zinc-700' : 'bg-zinc-800'}`}>
                    {isPast
                      ? <CheckCircle2 className="w-4 h-4 text-green-400" />
                      : <>
                          <span className={`text-[10px] font-extrabold leading-none ${isToday ? 'text-white' : 'text-zinc-400'}`}>Day</span>
                          <span className={`text-sm font-extrabold leading-none ${isToday ? 'text-white' : 'text-zinc-200'}`}>{d.day}</span>
                        </>
                    }
                  </div>

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${topicColor(d.focus)}`}>{d.focus}</span>
                      {isToday && <span className="text-[10px] font-bold text-orange-400 bg-orange-500/10 px-2 py-0.5 rounded-full">Today</span>}
                      <span className="flex items-center gap-1 text-[10px] text-zinc-600 ml-auto">
                        <Clock className="w-3 h-3" />{d.duration}
                      </span>
                    </div>
                    <p className="text-xs text-zinc-300 leading-relaxed">{d.task}</p>
                    {d.tip && <p className="text-[10px] text-orange-400/80 mt-1.5 italic">💡 {d.tip}</p>}
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </div>
    </div>
  )
}

// ─── Main component ───────────────────────────────────────────────────────────

export default function InterviewCountdown({ weakTopics, strongTopics }: { weakTopics: string[]; strongTopics: string[] }) {
  const [data, setData]               = useState<CountdownData | null>(null)
  const [setting, setSetting]         = useState(false)
  const [company, setCompany]         = useState('Google')
  const [date, setDate]               = useState('')
  const [generating, setGenerating]   = useState(false)
  const [showModal, setShowModal]     = useState(false)
  const [loaded, setLoaded]           = useState(false)

  useEffect(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY)
      if (stored) {
        const parsed = JSON.parse(stored) as CountdownData
        if (daysUntil(parsed.date) > 0) setData(parsed)
        else localStorage.removeItem(STORAGE_KEY)
      }
    } catch { /* ignore */ }
    setLoaded(true)
  }, [])

  const generate = useCallback(async () => {
    if (!company || !date) return
    const days = daysUntil(date)
    if (days <= 0) return
    setGenerating(true)
    try {
      const res = await fetch('/api/career/interview-plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ company, daysLeft: days, weakTopics, strongTopics }),
      })
      const result = await res.json()
      const newData: CountdownData = { company, date, plan: result.plan ?? [] }
      setData(newData)
      localStorage.setItem(STORAGE_KEY, JSON.stringify(newData))
      setSetting(false)
    } catch { /* ignore */ }
    finally { setGenerating(false) }
  }, [company, date, weakTopics, strongTopics])

  const clear = useCallback(() => {
    setData(null)
    localStorage.removeItem(STORAGE_KEY)
    setShowModal(false)
  }, [])

  const handleRegenerate = useCallback(() => {
    setShowModal(false)
    setData(null)
    setSetting(true)
  }, [])

  const minDate = new Date(); minDate.setDate(minDate.getDate() + 1)
  const maxDate = new Date(); maxDate.setDate(maxDate.getDate() + 120)

  if (!loaded) return null

  // ── Setup state ──
  if (setting || !data) {
    return (
      <div className="bg-zinc-900 border border-orange-500/20 rounded-2xl p-5 ring-1 ring-orange-500/5">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Target className="w-4 h-4 text-orange-400" />
            <p className="text-sm font-bold text-zinc-100">Interview Countdown</p>
          </div>
          {setting && (
            <button onClick={() => setSetting(false)} className="p-1 hover:bg-zinc-800 rounded transition-colors">
              <X className="w-3.5 h-3.5 text-zinc-500" />
            </button>
          )}
        </div>

        {!setting ? (
          <div className="flex flex-col items-center py-4 gap-3">
            <Calendar className="w-8 h-8 text-zinc-700" />
            <div className="text-center">
              <p className="text-sm font-semibold text-zinc-300 mb-1">Got an interview coming up?</p>
              <p className="text-xs text-zinc-500">Enter your date → AI generates a personalized day-by-day AI/ML prep plan for your company.</p>
            </div>
            <button onClick={() => setSetting(true)}
              className="flex items-center gap-2 bg-orange-500 hover:bg-orange-400 text-white text-sm font-semibold px-5 py-2.5 rounded-xl transition-all hover:shadow-lg hover:shadow-orange-500/20">
              <Sparkles className="w-3.5 h-3.5" /> Plan My Interview Prep
            </button>
          </div>
        ) : (
          <div className="flex flex-col gap-3">
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-xs font-semibold text-zinc-400 mb-1.5 block">Company</label>
                <select value={company} onChange={e => setCompany(e.target.value)}
                  className="w-full bg-zinc-800 border border-zinc-700 focus:border-orange-500/60 rounded-xl px-3 py-2 text-sm text-zinc-200 outline-none transition-colors">
                  {COMPANIES.map(c => <option key={c} value={c}>{c}</option>)}
                </select>
              </div>
              <div>
                <label className="text-xs font-semibold text-zinc-400 mb-1.5 block">Interview Date</label>
                <input type="date" value={date} onChange={e => setDate(e.target.value)}
                  min={minDate.toISOString().split('T')[0]}
                  max={maxDate.toISOString().split('T')[0]}
                  className="w-full bg-zinc-800 border border-zinc-700 focus:border-orange-500/60 rounded-xl px-3 py-2 text-sm text-zinc-200 outline-none transition-colors" />
              </div>
            </div>
            {date && <p className="text-xs text-zinc-500 text-center">{daysUntil(date)}-day plan will be generated (up to 60 days)</p>}
            <button onClick={generate} disabled={!date || generating}
              className="flex items-center justify-center gap-2 bg-orange-500 hover:bg-orange-400 disabled:opacity-40 text-white text-sm font-semibold py-2.5 rounded-xl transition-all">
              {generating
                ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating AI/ML plan…</>
                : <><Sparkles className="w-3.5 h-3.5" /> Generate Plan for {company}</>
              }
            </button>
          </div>
        )}
      </div>
    )
  }

  // ── Active countdown ──
  const days      = daysUntil(data.date)
  const todayTask = todaysPlan(data.plan, data.date)
  const todayIdx  = Math.max(0, data.plan.length - days)
  const dateLabel = new Date(data.date + 'T12:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
  const progress  = Math.round((todayIdx / data.plan.length) * 100)

  return (
    <>
      {showModal && <PlanModal data={data} onClose={() => setShowModal(false)} onRegenerate={handleRegenerate} />}

      <div className="bg-zinc-900 border border-orange-500/20 rounded-2xl overflow-hidden ring-1 ring-orange-500/5">

        {/* Header row */}
        <div className="flex items-center gap-3 px-5 py-4 border-b border-zinc-800">
          {/* Countdown badge */}
          <div className="flex flex-col items-center w-12 h-12 bg-orange-500/10 border border-orange-500/20 rounded-xl justify-center shrink-0">
            <span className="text-base font-extrabold text-orange-400 leading-none">{days}</span>
            <span className="text-[8px] text-orange-400/70 leading-none mt-0.5">days</span>
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-bold text-zinc-100">{data.company} Interview</p>
            <p className="text-xs text-zinc-500 flex items-center gap-1"><Calendar className="w-3 h-3" /> {dateLabel}</p>
            {/* Progress bar */}
            <div className="flex items-center gap-2 mt-1.5">
              <div className="flex-1 h-1 bg-zinc-800 rounded-full overflow-hidden">
                <div className="h-full bg-orange-500 rounded-full transition-all" style={{ width: `${progress}%` }} />
              </div>
              <span className="text-[9px] text-zinc-600 shrink-0">Day {todayIdx + 1}/{data.plan.length}</span>
            </div>
          </div>
          <div className="flex items-center gap-1.5 shrink-0">
            <button onClick={() => setShowModal(true)}
              className="flex items-center gap-1 text-xs text-zinc-400 hover:text-zinc-200 bg-zinc-800 hover:bg-zinc-700 px-2.5 py-1.5 rounded-lg border border-zinc-700 transition-colors">
              <Maximize2 className="w-3 h-3" /> View Plan
            </button>
            <button onClick={clear} className="p-1.5 hover:bg-zinc-800 rounded-lg transition-colors">
              <X className="w-3.5 h-3.5 text-zinc-600 hover:text-zinc-400" />
            </button>
          </div>
        </div>

        {/* Today's task */}
        {todayTask && (
          <div className="px-5 py-4">
            <p className="text-[10px] font-bold text-orange-400 uppercase tracking-wider mb-2">
              Today — Day {todayTask.day}
            </p>
            <div className="bg-zinc-800/50 border border-zinc-700/50 rounded-xl p-3.5">
              <div className="flex items-start justify-between gap-2 mb-2">
                <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${topicColor(todayTask.focus)}`}>{todayTask.focus}</span>
                <span className="flex items-center gap-1 text-[10px] text-zinc-600 shrink-0">
                  <Clock className="w-3 h-3" />{todayTask.duration}
                </span>
              </div>
              <p className="text-xs text-zinc-300 leading-relaxed">{todayTask.task}</p>
              {todayTask.tip && <p className="text-[10px] text-orange-400/80 mt-2 italic">💡 {todayTask.tip}</p>}
            </div>
          </div>
        )}

        {/* Navigation arrows for prev/next day preview */}
        <div className="px-5 pb-4 flex items-center gap-2">
          <button onClick={() => setShowModal(true)}
            className="flex-1 flex items-center justify-center gap-1.5 text-xs text-zinc-500 hover:text-orange-400 bg-zinc-800/40 hover:bg-zinc-800 border border-zinc-700/50 py-2 rounded-xl transition-colors">
            <Maximize2 className="w-3.5 h-3.5" />
            View full {data.plan.length}-day plan + Download PDF
          </button>
        </div>
      </div>
    </>
  )
}
