export interface StaticProblem {
  order_index: number
  title: string
  slug: string
  description: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  topic: string
  tags: string[]
  companies: string[]
  hints: string[]
  starter_code: string
  solution_code?: string
  test_cases: Array<{
    id: number
    function_call: string
    expected_output: string
    is_hidden: boolean
    description: string
  }>
}

export const STATIC_PROBLEMS: StaticProblem[] = [
  {
    order_index: 1, title: 'Softmax Function', slug: 'softmax-function',
    difficulty: 'Easy', topic: 'Math', tags: ['Math','Probability','LLM'],
    companies: ['OpenAI','Google','Meta'],
    hints: ['Use math.exp() for the exponential.','Divide each exp(x) by the sum of all exp values.','Round to 5 decimal places.'],
    description: '## Softmax Function\n\nConvert a list of real numbers (logits) into a **probability distribution**.\n\n### Formula\n`softmax(xᵢ) = exp(xᵢ) / Σ exp(xⱼ)`\n\n### Example\n```\nInput:  [1.0, 2.0, 3.0]\nOutput: [0.09003, 0.24473, 0.66524]\n```\n\nRound each value to **5 decimal places**.',
    starter_code: 'def softmax(logits: list) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'softmax([1.0, 2.0, 3.0])',expected_output:'[0.09003, 0.24473, 0.66524]',is_hidden:false,description:'Basic 3-element'},
      {id:2,function_call:'softmax([0.0, 0.0, 0.0])',expected_output:'[0.33333, 0.33333, 0.33333]',is_hidden:false,description:'Uniform input'},
      {id:3,function_call:'softmax([1.0])',expected_output:'[1.0]',is_hidden:true,description:'Single element'},
      {id:4,function_call:'softmax([10.0, -10.0])',expected_output:'[1.0, 0.0]',is_hidden:true,description:'Extreme values'},
    ],
  },
  {
    order_index: 2, title: 'Cosine Similarity', slug: 'cosine-similarity',
    difficulty: 'Easy', topic: 'Vector DB', tags: ['Vector DB','Embeddings','Math'],
    companies: ['Pinecone','OpenAI','Google'],
    hints: ['cos(a,b) = dot(a,b) / (||a|| × ||b||)','Use math.sqrt for norms.','Round to 5 decimal places.'],
    description: '## Cosine Similarity\n\nMeasure the cosine angle between two vectors — the core operation in every vector database.\n\n### Formula\n`cos(a, b) = dot(a, b) / (||a|| × ||b||)`\n\n### Range: [-1, 1]\n- 1.0 → identical direction\n- 0.0 → orthogonal\n- -1.0 → opposite\n\nRound to **5 decimal places**.',
    starter_code: 'def cosine_similarity(a: list, b: list) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'cosine_similarity([1,0,0],[0,1,0])',expected_output:'0.0',is_hidden:false,description:'Orthogonal'},
      {id:2,function_call:'cosine_similarity([1,1],[1,1])',expected_output:'1.0',is_hidden:false,description:'Identical direction'},
      {id:3,function_call:'cosine_similarity([1,2,3],[4,5,6])',expected_output:'0.97463',is_hidden:false,description:'General case'},
      {id:4,function_call:'cosine_similarity([1,0],[-1,0])',expected_output:'-1.0',is_hidden:true,description:'Opposite direction'},
    ],
  },
  {
    order_index: 3, title: 'Cross-Entropy Loss', slug: 'cross-entropy-loss',
    difficulty: 'Easy', topic: 'Math', tags: ['Math','Loss Functions','Training'],
    companies: ['Google','Meta','Nvidia'],
    hints: ['loss = -Σ y_true * log(y_pred)','Clip predictions to avoid log(0).','Round to 5 decimal places.'],
    description: '## Cross-Entropy Loss\n\nCompute the cross-entropy loss between true labels and predicted probabilities.\n\n### Formula\n`loss = -Σ y_true[i] * log(y_pred[i])`\n\n### Example\n```\ny_true = [0, 1, 0]\ny_pred = [0.1, 0.8, 0.1]\nloss = 0.22314\n```\n\nRound to **5 decimal places**.',
    starter_code: 'def cross_entropy_loss(y_true: list, y_pred: list) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'cross_entropy_loss([0,1,0],[0.1,0.8,0.1])',expected_output:'0.22314',is_hidden:false,description:'Basic 3-class'},
      {id:2,function_call:'cross_entropy_loss([1,0],[0.9,0.1])',expected_output:'0.10536',is_hidden:false,description:'Binary correct'},
      {id:3,function_call:'cross_entropy_loss([1,0],[0.5,0.5])',expected_output:'0.69315',is_hidden:true,description:'Uncertain prediction'},
      {id:4,function_call:'cross_entropy_loss([0,0,1],[0.1,0.1,0.8])',expected_output:'0.22314',is_hidden:true,description:'Third class true'},
    ],
  },
  {
    order_index: 4, title: 'Sigmoid Function', slug: 'sigmoid-function',
    difficulty: 'Easy', topic: 'Math', tags: ['Math','Activation Functions'],
    companies: ['Google','Meta'],
    hints: ['sigmoid(x) = 1 / (1 + exp(-x))','Round to 5 decimal places.'],
    description: '## Sigmoid Function\n\nImplement the sigmoid activation function used in logistic regression, binary classification, and LSTM gates.\n\n### Formula\n`σ(x) = 1 / (1 + e^(-x))`\n\n### Properties\n- Output range: (0, 1)\n- σ(0) = 0.5\n\nRound to **5 decimal places**.',
    starter_code: 'def sigmoid(x: float) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'sigmoid(0)',expected_output:'0.5',is_hidden:false,description:'Zero input'},
      {id:2,function_call:'sigmoid(1)',expected_output:'0.73106',is_hidden:false,description:'Positive input'},
      {id:3,function_call:'sigmoid(-1)',expected_output:'0.26894',is_hidden:false,description:'Negative input'},
      {id:4,function_call:'sigmoid(10)',expected_output:'0.9999546',is_hidden:true,description:'Large positive'},
    ],
  },
  {
    order_index: 5, title: 'Euclidean Distance', slug: 'euclidean-distance',
    difficulty: 'Easy', topic: 'Math', tags: ['Math','Distance','KNN'],
    companies: ['Google','Amazon'],
    hints: ['dist = sqrt(sum((a[i] - b[i])^2))','Round to 5 decimal places.'],
    description: '## Euclidean Distance\n\nCompute the L2 distance between two vectors. Used in KNN, clustering, and vector search.\n\n### Formula\n`d(a, b) = √Σ(aᵢ - bᵢ)²`\n\nRound to **5 decimal places**.',
    starter_code: 'def euclidean_distance(a: list, b: list) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'euclidean_distance([0,0],[3,4])',expected_output:'5.0',is_hidden:false,description:'3-4-5 triangle'},
      {id:2,function_call:'euclidean_distance([1,2,3],[4,5,6])',expected_output:'5.19615',is_hidden:false,description:'3D vectors'},
      {id:3,function_call:'euclidean_distance([1,1],[1,1])',expected_output:'0.0',is_hidden:false,description:'Same point'},
      {id:4,function_call:'euclidean_distance([0],[5])',expected_output:'5.0',is_hidden:true,description:'1D'},
    ],
  },
  {
    order_index: 6, title: 'Gradient Descent Step', slug: 'gradient-descent-step',
    difficulty: 'Easy', topic: 'Math', tags: ['Optimization','Training','Math'],
    companies: ['Google','OpenAI','Meta'],
    hints: ['new_weight = weight - learning_rate * gradient','Round to 5 decimal places.'],
    description: '## Gradient Descent Step\n\nImplement a single gradient descent weight update.\n\n### Formula\n`w_new = w - lr × gradient`\n\nRound each weight to **5 decimal places**.',
    starter_code: 'def gradient_descent_step(weights: list, gradients: list, lr: float) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'gradient_descent_step([0.5,-0.3,0.8],[0.1,-0.2,0.05],0.1)',expected_output:'[0.49, -0.28, 0.795]',is_hidden:false,description:'Basic step'},
      {id:2,function_call:'gradient_descent_step([1.0],[0.5],0.01)',expected_output:'[0.995]',is_hidden:false,description:'Small lr'},
      {id:3,function_call:'gradient_descent_step([0.0,0.0],[0.0,0.0],0.1)',expected_output:'[0.0, 0.0]',is_hidden:true,description:'Zero gradients'},
      {id:4,function_call:'gradient_descent_step([2.0,-1.0],[1.0,-1.0],0.5)',expected_output:'[1.5, -0.5]',is_hidden:true,description:'Large step'},
    ],
  },
  {
    order_index: 7, title: 'TF-IDF Score', slug: 'tfidf-score',
    difficulty: 'Medium', topic: 'NLP', tags: ['NLP','Information Retrieval','Math'],
    companies: ['Google','Amazon','Microsoft'],
    hints: ['TF(t,d) = count(t in d) / len(d)','IDF(t) = log(N / df(t))','TF-IDF = TF * IDF, round to 5 decimal places.'],
    description: '## TF-IDF Score\n\nCompute the TF-IDF score for a term in a document.\n\n- **TF(t, d)** = count of term t in doc d / total terms in d\n- **IDF(t)** = log(N / df(t)) — natural log\n- **TF-IDF** = TF × IDF\n\nRound to **5 decimal places**.',
    starter_code: 'import math\n\ndef tfidf(term: str, document: list, all_documents: list) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:"tfidf('cat',['cat','sat','cat','mat'],[['cat','sat'],['dog','ran'],['cat','mat']])",expected_output:'0.20273',is_hidden:false,description:'Term in 2 of 3 docs'},
      {id:2,function_call:"tfidf('dog',['dog','ran'],[['cat','sat'],['dog','ran'],['cat','mat']])",expected_output:'0.54931',is_hidden:false,description:'Rare term'},
      {id:3,function_call:"tfidf('cat',['cat','cat','cat'],[['cat'],['cat'],['cat']])",expected_output:'0.0',is_hidden:true,description:'Term in all docs'},
      {id:4,function_call:"tfidf('ml',['ml','ai','ml'],[['ml','ai'],['python','data'],['ai','ml']])",expected_output:'0.27031',is_hidden:true,description:'Medium frequency'},
    ],
  },
  {
    order_index: 8, title: 'KNN Classifier', slug: 'knn-classifier',
    difficulty: 'Medium', topic: 'Classical ML', tags: ['KNN','Classification','Distance'],
    companies: ['Amazon','Google','Netflix'],
    hints: ['Compute Euclidean distance from query to all training points.','Sort by distance, take k nearest.','Return the most common label.'],
    description: '## K-Nearest Neighbours Classifier\n\nClassify a point based on the majority label among its k nearest neighbours.\n\n1. Compute Euclidean distance to all training points\n2. Select the k smallest distances\n3. Return majority label (ties broken by lower label value)',
    starter_code: 'def knn_classify(train_X: list, train_y: list, query: list, k: int) -> int:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'knn_classify([[1,1],[2,2],[5,5],[6,6]],[0,0,1,1],[3,3],3)',expected_output:'0',is_hidden:false,description:'Majority class 0'},
      {id:2,function_call:'knn_classify([[1,1],[2,2],[5,5],[6,6]],[0,0,1,1],[4,4],1)',expected_output:'1',is_hidden:false,description:'Nearest is class 1'},
      {id:3,function_call:'knn_classify([[0],[1],[2],[3]],[0,0,1,1],[1.4],1)',expected_output:'0',is_hidden:true,description:'1D nearest'},
      {id:4,function_call:'knn_classify([[1,1],[9,9],[5,5]],[0,1,0],[4,4],3)',expected_output:'0',is_hidden:true,description:'Majority vote'},
    ],
  },
  {
    order_index: 9, title: 'Tokenise Text', slug: 'tokenise-text',
    difficulty: 'Easy', topic: 'NLP', tags: ['NLP','Tokenization','LLM'],
    companies: ['OpenAI','Hugging Face'],
    hints: ['Lowercase the text first.','Split on whitespace.','Remove punctuation from each token.'],
    description: '## Word-Level Tokeniser\n\nTokenise a string into lowercase words, removing punctuation.\n\n1. Convert to lowercase\n2. Remove all punctuation (`.,!?;:\'"-`)\n3. Split on whitespace\n4. Remove empty strings\n\n```\nInput:  "Hello, world!"\nOutput: ["hello", "world"]\n```',
    starter_code: 'def tokenise(text: str) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:"tokenise('Hello, world! This is NLP.')",expected_output:"['hello', 'world', 'this', 'is', 'nlp']",is_hidden:false,description:'Basic sentence'},
      {id:2,function_call:"tokenise('AI/ML is great')",expected_output:"['ai/ml', 'is', 'great']",is_hidden:false,description:'Slash not removed'},
      {id:3,function_call:"tokenise('one two  three')",expected_output:"['one', 'two', 'three']",is_hidden:true,description:'Multiple spaces'},
      {id:4,function_call:"tokenise('RAG, fine-tuning, and LoRA!')",expected_output:"['rag', 'fine-tuning', 'and', 'lora']",is_hidden:true,description:'Hyphens preserved'},
    ],
  },
  {
    order_index: 10, title: 'Precision, Recall & F1', slug: 'precision-recall-f1',
    difficulty: 'Easy', topic: 'Math', tags: ['Evaluation','Classification','Metrics'],
    companies: ['Google','Meta','Amazon'],
    hints: ['Precision = TP / (TP + FP)','Recall = TP / (TP + FN)','F1 = 2 * P * R / (P + R)'],
    description: '## Precision, Recall & F1 Score\n\nGiven true and predicted labels, compute Precision, Recall, and F1 for the **positive class (1)**.\n\n- Precision = TP / (TP + FP)\n- Recall = TP / (TP + FN)\n- F1 = 2 × P × R / (P + R)\n\nReturn `(precision, recall, f1)` each rounded to **5 decimal places**.',
    starter_code: 'def precision_recall_f1(y_true: list, y_pred: list) -> tuple:\n    # Returns (precision, recall, f1)\n    pass',
    test_cases: [
      {id:1,function_call:'precision_recall_f1([1,1,0,0],[1,0,1,0])',expected_output:'(0.5, 0.5, 0.5)',is_hidden:false,description:'Equal TP FP FN'},
      {id:2,function_call:'precision_recall_f1([1,1,1],[1,1,1])',expected_output:'(1.0, 1.0, 1.0)',is_hidden:false,description:'Perfect prediction'},
      {id:3,function_call:'precision_recall_f1([1,0,1,0,1],[1,1,1,0,0])',expected_output:'(0.66667, 0.66667, 0.66667)',is_hidden:true,description:'Mixed'},
      {id:4,function_call:'precision_recall_f1([0,0,0],[0,0,0])',expected_output:'(0.0, 0.0, 0.0)',is_hidden:true,description:'No positives'},
    ],
  },
  {
    order_index: 11, title: 'Dot Product Attention', slug: 'dot-product-attention',
    difficulty: 'Medium', topic: 'Transformers', tags: ['Transformers','Attention','LLM'],
    companies: ['Google','OpenAI','Meta'],
    hints: ['scores = Q @ K.T / sqrt(d_k)','Apply softmax to scores row-wise.','output = scores @ V','Round final output to 5 decimal places.'],
    description: '## Scaled Dot-Product Attention\n\nImplement the core attention operation.\n\n### Formula\n`Attention(Q, K, V) = softmax(QKᵀ / √dₖ) × V`\n\n- Q: (n_q × d_k), K: (n_k × d_k), V: (n_k × d_v)\n- Output: (n_q × d_v), each value rounded to 5 decimal places',
    starter_code: 'import math\n\ndef dot_product_attention(Q: list, K: list, V: list) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'dot_product_attention([[1,0]],[[1,0],[0,1]],[[1,0],[0,1]])',expected_output:'[[0.73106, 0.26894]]',is_hidden:false,description:'Single query'},
      {id:2,function_call:'dot_product_attention([[1,0],[0,1]],[[1,0],[0,1]],[[2,0],[0,2]])',expected_output:'[[1.46211, 0.53789], [0.53789, 1.46211]]',is_hidden:false,description:'Two queries'},
      {id:3,function_call:'dot_product_attention([[0,0]],[[1,0],[0,1]],[[1,0],[0,1]])',expected_output:'[[0.5, 0.5]]',is_hidden:true,description:'Zero query'},
    ],
  },
  {
    order_index: 12, title: 'Batch Normalisation', slug: 'batch-normalisation',
    difficulty: 'Medium', topic: 'Math', tags: ['Deep Learning','Normalisation','Training'],
    companies: ['Google','Nvidia','Meta'],
    hints: ['Compute mean and variance across the batch.','x_hat = (x - mean) / sqrt(var + eps)','y = gamma * x_hat + beta'],
    description: '## Batch Normalisation\n\nNormalise a batch of activations with learnable parameters γ and β.\n\n1. μ = mean(batch)\n2. σ² = variance(batch)\n3. x̂ = (x - μ) / √(σ² + ε)\n4. y = γ × x̂ + β\n\nRound to **5 decimal places**.',
    starter_code: 'import math\n\ndef batch_norm(batch: list, gamma: float, beta: float, eps: float = 1e-8) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'batch_norm([2.0,4.0,6.0,8.0],1.0,0.0)',expected_output:'[-1.34164, -0.4472, 0.4472, 1.34164]',is_hidden:false,description:'Unit scale zero shift'},
      {id:2,function_call:'batch_norm([1.0,1.0,1.0],1.0,0.0)',expected_output:'[0.0, 0.0, 0.0]',is_hidden:false,description:'Constant input'},
      {id:3,function_call:'batch_norm([0.0,2.0,4.0],2.0,1.0)',expected_output:'[-1.44949, 1.0, 3.44949]',is_hidden:true,description:'Scale=2 beta=1'},
    ],
  },
  {
    order_index: 13, title: 'Word Frequency Counter', slug: 'word-frequency-counter',
    difficulty: 'Easy', topic: 'NLP', tags: ['NLP','Python','Data Processing'],
    companies: ['Amazon','Google'],
    hints: ['Lowercase all words.','Split on whitespace.','Count with a dictionary, sort by count descending then alphabetically.'],
    description: '## Word Frequency Counter\n\nCount word frequencies and return top-k most frequent words.\n\n1. Lowercase, remove punctuation (`.,!?;:`), split on whitespace\n2. Count frequencies\n3. Return top-k as `(word, count)` tuples — sorted by count desc, then alphabetically for ties',
    starter_code: 'def top_k_words(text: str, k: int) -> list:\n    pass',
    test_cases: [
      {id:1,function_call:"top_k_words('the cat sat on the mat the cat',2)",expected_output:"[('the', 3), ('cat', 2)]",is_hidden:false,description:'Top 2 words'},
      {id:2,function_call:"top_k_words('ai ml ai dl ai ml',3)",expected_output:"[('ai', 3), ('ml', 2), ('dl', 1)]",is_hidden:false,description:'Three distinct'},
      {id:3,function_call:"top_k_words('hello hello world',1)",expected_output:"[('hello', 2)]",is_hidden:true,description:'Top 1'},
    ],
  },
  {
    order_index: 14, title: 'Mean Squared Error', slug: 'mean-squared-error',
    difficulty: 'Easy', topic: 'Math', tags: ['Regression','Loss Functions','Math'],
    companies: ['Google','Amazon'],
    hints: ['MSE = (1/n) * Σ(y_pred - y_true)²','Round to 5 decimal places.'],
    description: '## Mean Squared Error\n\nCompute MSE between predicted and true values.\n\n`MSE = (1/n) × Σ(ŷᵢ - yᵢ)²`\n\nRound to **5 decimal places**.',
    starter_code: 'def mse(y_true: list, y_pred: list) -> float:\n    pass',
    test_cases: [
      {id:1,function_call:'mse([3,-0.5,2,7],[2.5,0.0,2,8])',expected_output:'0.375',is_hidden:false,description:'Mixed errors'},
      {id:2,function_call:'mse([1,2,3],[1,2,3])',expected_output:'0.0',is_hidden:false,description:'Perfect prediction'},
      {id:3,function_call:'mse([0,0],[1,1])',expected_output:'1.0',is_hidden:true,description:'Unit errors'},
      {id:4,function_call:'mse([5],[2])',expected_output:'9.0',is_hidden:true,description:'Single value'},
    ],
  },
  {
    order_index: 15, title: 'One-Hot Encoding', slug: 'one-hot-encoding',
    difficulty: 'Easy', topic: 'Classical ML', tags: ['Data Processing','Encoding','Features'],
    companies: ['Google','Amazon','Meta'],
    hints: ['Create a list of zeros of length num_classes.','Set the index of the class to 1.'],
    description: '## One-Hot Encoding\n\nConvert integer labels into one-hot vectors.\n\n```\nlabels = [0, 2, 1], num_classes = 3\nOutput: [[1,0,0], [0,0,1], [0,1,0]]\n```',
    starter_code: 'def one_hot_encode(labels: list, num_classes: int) -> list:\n    pass',
    test_cases: [
      {id:1,function_call:'one_hot_encode([0,2,1],3)',expected_output:'[[1, 0, 0], [0, 0, 1], [0, 1, 0]]',is_hidden:false,description:'Basic 3-class'},
      {id:2,function_call:'one_hot_encode([0,1],2)',expected_output:'[[1, 0], [0, 1]]',is_hidden:false,description:'Binary'},
      {id:3,function_call:'one_hot_encode([3],4)',expected_output:'[[0, 0, 0, 1]]',is_hidden:true,description:'Last class'},
      {id:4,function_call:'one_hot_encode([0,0],3)',expected_output:'[[1, 0, 0], [1, 0, 0]]',is_hidden:true,description:'Repeated label'},
    ],
  },
  {
    order_index: 16, title: 'Positional Encoding', slug: 'positional-encoding',
    difficulty: 'Medium', topic: 'Transformers', tags: ['Transformers','Positional Encoding','LLM'],
    companies: ['Google','OpenAI'],
    hints: ['PE(pos, 2i) = sin(pos / 10000^(2i/d_model))','PE(pos, 2i+1) = cos(pos / 10000^(2i/d_model))','Round to 5 decimal places.'],
    description: '## Sinusoidal Positional Encoding\n\nGenerate the positional encoding for a single position.\n\n- `PE[2i]   = sin(pos / 10000^(2i / d_model))`\n- `PE[2i+1] = cos(pos / 10000^(2i / d_model))`\n\nRound to **5 decimal places**.',
    starter_code: 'import math\n\ndef positional_encoding(pos: int, d_model: int) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'positional_encoding(0,4)',expected_output:'[0.0, 1.0, 0.0, 1.0]',is_hidden:false,description:'Position 0'},
      {id:2,function_call:'positional_encoding(1,4)',expected_output:'[0.84147, 0.54030, 0.00999, 0.99995]',is_hidden:false,description:'Position 1'},
      {id:3,function_call:'positional_encoding(0,2)',expected_output:'[0.0, 1.0]',is_hidden:true,description:'Minimal d_model'},
    ],
  },
  {
    order_index: 17, title: 'Label Encoding', slug: 'label-encoding',
    difficulty: 'Easy', topic: 'Classical ML', tags: ['Data Processing','Encoding','Features'],
    companies: ['Amazon','Google'],
    hints: ['Find all unique labels.','Sort them alphabetically.','Assign index 0, 1, 2... to each.'],
    description: '## Label Encoding\n\nConvert categorical labels to integer indices.\n\n1. Find all unique labels\n2. Sort alphabetically\n3. Assign 0, 1, 2... to each unique label\n4. Return encoded list\n\n```\nlabels = ["cat", "dog", "cat", "bird"]\nOutput: [1, 2, 1, 0]  (bird=0, cat=1, dog=2)\n```',
    starter_code: 'def label_encode(labels: list) -> list:\n    pass',
    test_cases: [
      {id:1,function_call:"label_encode(['cat','dog','cat','bird'])",expected_output:'[1, 2, 1, 0]',is_hidden:false,description:'3 classes'},
      {id:2,function_call:"label_encode(['a','b','a','c','b'])",expected_output:'[0, 1, 0, 2, 1]',is_hidden:false,description:'Alphabetical order'},
      {id:3,function_call:"label_encode(['z','a','m'])",expected_output:'[2, 0, 1]',is_hidden:true,description:'Reverse order'},
      {id:4,function_call:"label_encode(['x'])",expected_output:'[0]',is_hidden:true,description:'Single label'},
    ],
  },
  {
    order_index: 18, title: 'Min-Max Normalisation', slug: 'min-max-normalisation',
    difficulty: 'Easy', topic: 'Classical ML', tags: ['Data Processing','Normalisation','Features'],
    companies: ['Google','Amazon','Meta'],
    hints: ['x_norm = (x - min) / (max - min)','If max == min, return all zeros.','Round to 5 decimal places.'],
    description: '## Min-Max Normalisation\n\nScale values to [0, 1].\n\n`x_norm = (x - x_min) / (x_max - x_min)`\n\nIf all values are equal, return zeros. Round to **5 decimal places**.',
    starter_code: 'def min_max_normalise(values: list) -> list:\n    pass',
    test_cases: [
      {id:1,function_call:'min_max_normalise([0,5,10])',expected_output:'[0.0, 0.5, 1.0]',is_hidden:false,description:'Basic scaling'},
      {id:2,function_call:'min_max_normalise([3,3,3])',expected_output:'[0.0, 0.0, 0.0]',is_hidden:false,description:'All same value'},
      {id:3,function_call:'min_max_normalise([1,2,3,4,5])',expected_output:'[0.0, 0.25, 0.5, 0.75, 1.0]',is_hidden:true,description:'Sequential'},
      {id:4,function_call:'min_max_normalise([-10,0,10])',expected_output:'[0.0, 0.5, 1.0]',is_hidden:true,description:'Negative values'},
    ],
  },
  {
    order_index: 19, title: 'Perplexity', slug: 'perplexity',
    difficulty: 'Medium', topic: 'NLP', tags: ['NLP','LLM','Evaluation'],
    companies: ['OpenAI','Google','Meta'],
    hints: ['perplexity = exp(-(1/N) * sum(log(p_i)))','Use natural log.','Round to 5 decimal places.'],
    description: '## Perplexity\n\nCompute perplexity of a language model — lower is better.\n\n`PP = exp(-(1/N) × Σ log(p(wᵢ)))`\n\nRound to **5 decimal places**.',
    starter_code: 'import math\n\ndef perplexity(probabilities: list) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'perplexity([0.5,0.3,0.8])',expected_output:'3.17578',is_hidden:false,description:'Mixed probabilities'},
      {id:2,function_call:'perplexity([1.0,1.0,1.0])',expected_output:'1.0',is_hidden:false,description:'Perfect model'},
      {id:3,function_call:'perplexity([0.1,0.1,0.1])',expected_output:'10.0',is_hidden:true,description:'Low probability model'},
      {id:4,function_call:'perplexity([0.5,0.5])',expected_output:'2.0',is_hidden:true,description:'Binary uniform'},
    ],
  },
  {
    order_index: 20, title: 'K-Means Centroid Update', slug: 'kmeans-centroid-update',
    difficulty: 'Medium', topic: 'Classical ML', tags: ['Clustering','K-Means','Unsupervised'],
    companies: ['Google','Amazon','Uber'],
    hints: ['Group points by their cluster assignment.','New centroid = mean of all points in that cluster.','Round to 5 decimal places.'],
    description: '## K-Means Centroid Update\n\nGiven points and cluster assignments, compute new centroids.\n\n```\npoints      = [[1,1],[2,2],[8,8],[9,9]]\nassignments = [0,    0,    1,    1   ]\nk = 2\nNew centroids: [[1.5, 1.5], [8.5, 8.5]]\n```\n\nRound to **5 decimal places**.',
    starter_code: 'def update_centroids(points: list, assignments: list, k: int) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'update_centroids([[1,1],[2,2],[8,8],[9,9]],[0,0,1,1],2)',expected_output:'[[1.5, 1.5], [8.5, 8.5]]',is_hidden:false,description:'Two clusters'},
      {id:2,function_call:'update_centroids([[0,0],[4,4],[8,8]],[0,1,2],3)',expected_output:'[[0.0, 0.0], [4.0, 4.0], [8.0, 8.0]]',is_hidden:false,description:'Three singleton clusters'},
      {id:3,function_call:'update_centroids([[1,2],[3,4],[5,6],[7,8]],[0,0,0,1],2)',expected_output:'[[3.0, 4.0], [7.0, 8.0]]',is_hidden:true,description:'Unequal sizes'},
    ],
  },

  // ─── NEW PROBLEMS ────────────────────────────────────────────────────────────
  {
    order_index: 21, title: 'Backpropagation Step', slug: 'backpropagation',
    difficulty: 'Hard', topic: 'Deep Learning', tags: ['Deep Learning','Backprop','Optimization'],
    companies: ['Google','Meta','OpenAI','Apple'],
    hints: ['Forward: z = dot(w, x) + b, y_pred = sigmoid(z)','Gradient: dw_i = (y_pred - y_true) * x_i, db = y_pred - y_true','Update: w_new = w - lr * dw'],
    description: '## Backpropagation Step\n\nPerform one backprop step for a **single neuron** with sigmoid activation.\n\n### Forward\n`z = Σ wᵢxᵢ + b`,  `ŷ = sigmoid(z)`\n\n### Backward (Binary Cross-Entropy)\n`∂L/∂wᵢ = (ŷ - y) × xᵢ`,  `∂L/∂b = ŷ - y`\n\n### Update\n`w_new = w - lr × ∂L/∂w`\n\nReturn `(w_new, b_new)` — weights rounded to 5 decimal places.',
    starter_code: 'import math\n\ndef backprop_step(x: list, w: list, b: float, y_true: float, lr: float) -> tuple:\n    """\n    x: input vector\n    w: weight vector\n    b: bias\n    y_true: target (0 or 1)\n    lr: learning rate\n    Returns: (w_new: list, b_new: float) rounded to 5 decimal places\n    """\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'backprop_step([1.0, 2.0],[0.5, -0.3],0.1,1.0,0.1)',expected_output:'([0.55, -0.2], 0.15)',is_hidden:false,description:'Basic update toward y=1'},
      {id:2,function_call:'backprop_step([1.0],[0.0],0.0,0.0,0.1)',expected_output:'([-0.05], -0.05)',is_hidden:false,description:'Update toward y=0'},
      {id:3,function_call:'backprop_step([0.0,0.0],[0.5,0.5],0.0,1.0,0.01)',expected_output:'([0.5, 0.5], 0.005)',is_hidden:true,description:'Zero inputs no weight change'},
      {id:4,function_call:'backprop_step([2.0],[0.0],0.0,1.0,0.5)',expected_output:'([0.25], 0.125)',is_hidden:true,description:'Large lr'},
    ],
  },
  {
    order_index: 22, title: 'MLP Forward Pass', slug: 'mlp-forward-pass',
    difficulty: 'Medium', topic: 'Deep Learning', tags: ['Deep Learning','Neural Networks','Forward Pass'],
    companies: ['Google','Meta','Amazon','Apple'],
    hints: ['For each layer: output = ReLU(W @ input + b)','The last layer has no activation (linear).','W has shape (out_features, in_features).'],
    description: '## MLP Forward Pass\n\nCompute the forward pass through a Multi-Layer Perceptron.\n\n- Apply **ReLU** activation after every hidden layer\n- Last layer is **linear** (no activation)\n- Each weight matrix W has shape `(out_features, in_features)`\n\nRound final output to **5 decimal places**.',
    starter_code: 'def mlp_forward(x: list, weights: list, biases: list) -> list:\n    """\n    x: input vector\n    weights: list of 2D weight matrices\n    biases: list of bias vectors\n    Returns: output vector\n    """\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'mlp_forward([1.0,2.0],[[[1,0],[0,1]],[[1,1]]],[[0,0],[0]])',expected_output:'[3.0]',is_hidden:false,description:'Identity then sum'},
      {id:2,function_call:'mlp_forward([1.0,-2.0],[[[1,0],[0,1]]],[[0,0]])',expected_output:'[1.0, 0.0]',is_hidden:false,description:'ReLU kills negative'},
      {id:3,function_call:'mlp_forward([2.0],[[[1],[-1]],[[1,1]]],[[0,0],[0]])',expected_output:'[2.0]',is_hidden:true,description:'Two hidden layers'},
      {id:4,function_call:'mlp_forward([0.0,0.0],[[[1,1]],[[2]]],[[1],[0]])',expected_output:'[2.0]',is_hidden:true,description:'Bias drives output'},
    ],
  },
  {
    order_index: 23, title: '1D Convolution', slug: 'convolution-1d',
    difficulty: 'Medium', topic: 'Deep Learning', tags: ['Deep Learning','CNN','Signal Processing'],
    companies: ['Google','Meta','Apple'],
    hints: ['Slide the kernel over the signal (valid convolution — no padding).','output[i] = sum(signal[i:i+len(kernel)] * kernel)','Output length = len(signal) - len(kernel) + 1'],
    description: '## 1D Valid Convolution\n\nConvolve a 1D signal with a kernel (no padding).\n\n`output[i] = Σⱼ signal[i+j] × kernel[j]`\n\nOutput length = `len(signal) - len(kernel) + 1`\n\nRound to **5 decimal places**.',
    starter_code: 'def conv1d(signal: list, kernel: list) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'conv1d([1,2,3,4,5],[1,0,-1])',expected_output:'[-2, -2, -2]',is_hidden:false,description:'Edge detection kernel'},
      {id:2,function_call:'conv1d([1,1,1,1],[0.5,0.5])',expected_output:'[1.0, 1.0, 1.0]',is_hidden:false,description:'Averaging kernel'},
      {id:3,function_call:'conv1d([1,2,3],[1,1,1])',expected_output:'[6]',is_hidden:true,description:'Full overlap'},
      {id:4,function_call:'conv1d([3,1,4,1,5,9],[1,-1])',expected_output:'[2, -3, 3, -4, -4]',is_hidden:true,description:'Difference kernel'},
    ],
  },
  {
    order_index: 24, title: 'RNN Step', slug: 'rnn-step',
    difficulty: 'Medium', topic: 'Deep Learning', tags: ['Deep Learning','RNN','Sequence Models'],
    companies: ['Google','Meta','Amazon'],
    hints: ['h_t = tanh(Wh @ h_prev + Wx @ x + b)','Matrix-vector multiply: (W @ v)[i] = sum(W[i][j] * v[j])','Round to 5 decimal places.'],
    description: '## Single RNN Step\n\nCompute one RNN timestep.\n\n`h_t = tanh(Wh × h_{t-1} + Wx × x_t + b)`\n\n- `Wh`: (d_h × d_h) hidden-to-hidden weights\n- `Wx`: (d_h × d_x) input-to-hidden weights\n- `b`: (d_h,) bias vector\n\nRound to **5 decimal places**.',
    starter_code: 'import math\n\ndef rnn_step(h_prev: list, x: list, Wh: list, Wx: list, b: list) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'rnn_step([0.0],[ 1.0],[[1.0]],[[1.0]],[0.0])',expected_output:'[0.76159]',is_hidden:false,description:'Zero hidden state'},
      {id:2,function_call:'rnn_step([1.0],[0.0],[[0.0]],[[0.0]],[0.0])',expected_output:'[0.0]',is_hidden:false,description:'Zero input and bias'},
      {id:3,function_call:'rnn_step([0.5,0.5],[1.0],[[1,0],[0,1]],[[1],[1]],[0,0])',expected_output:'[0.90515, 0.90515]',is_hidden:true,description:'2D hidden state'},
      {id:4,function_call:'rnn_step([0.0],[0.0],[[1.0]],[[1.0]],[1.0])',expected_output:'[0.76159]',is_hidden:true,description:'Bias drives output'},
    ],
  },
  {
    order_index: 25, title: 'LSTM Step', slug: 'lstm-step',
    difficulty: 'Hard', topic: 'Deep Learning', tags: ['Deep Learning','LSTM','Sequence Models'],
    companies: ['Google','Meta','Amazon','Apple'],
    hints: ['f = sigmoid(wf * (x + h_prev)) — forget gate','i = sigmoid(wi * (x + h_prev)) — input gate','g = tanh(wg * (x + h_prev)) — cell gate','o = sigmoid(wo * (x + h_prev)) — output gate','c_new = f * c_prev + i * g;  h_new = o * tanh(c_new)'],
    description: '## Simplified Scalar LSTM Step\n\nImplement one step of a scalar LSTM cell.\n\n```\nf = sigmoid(wf × (x + h_prev))   # forget gate\ni = sigmoid(wi × (x + h_prev))   # input gate\ng = tanh(wg × (x + h_prev))      # cell gate\no = sigmoid(wo × (x + h_prev))   # output gate\nc_new = f × c_prev + i × g\nh_new = o × tanh(c_new)\n```\n\nReturn `(h_new, c_new)` rounded to **5 decimal places**.',
    starter_code: 'import math\n\ndef lstm_step(x: float, h_prev: float, c_prev: float,\n             wf: float, wi: float, wg: float, wo: float) -> tuple:\n    # Returns (h_new, c_new)\n    pass',
    test_cases: [
      {id:1,function_call:'lstm_step(1.0,0.0,0.0,1.0,1.0,1.0,1.0)',expected_output:'(0.36973, 0.55694)',is_hidden:false,description:'Zero initial state'},
      {id:2,function_call:'lstm_step(0.0,0.0,0.0,1.0,1.0,1.0,1.0)',expected_output:'(0.0, 0.0)',is_hidden:false,description:'Zero input and state'},
      {id:3,function_call:'lstm_step(1.0,0.5,0.3,0.5,1.0,1.0,0.8)',expected_output:'(0.48566, 0.62842)',is_hidden:true,description:'Non-zero initial state'},
      {id:4,function_call:'lstm_step(-1.0,0.0,1.0,0.0,0.0,0.0,1.0)',expected_output:'(0.45964, 1.0)',is_hidden:true,description:'Forget gate open'},
    ],
  },
  {
    order_index: 26, title: 'Gini Impurity', slug: 'gini-impurity',
    difficulty: 'Easy', topic: 'Classical ML', tags: ['Decision Trees','Classification','Classical ML'],
    companies: ['Google','Meta','Amazon','Microsoft'],
    hints: ['gini = 1 - sum(p_i^2)','p_i = count of class i / total samples','Round to 5 decimal places.'],
    description: '## Gini Impurity\n\nCompute the Gini impurity of a node in a decision tree.\n\n`gini = 1 - Σ pᵢ²`\n\nwhere pᵢ = fraction of samples belonging to class i.\n\n```\nlabels = [1, 1, 0, 0]  →  gini = 1 - (0.5² + 0.5²) = 0.5\nlabels = [1, 1, 1, 0]  →  gini = 1 - (0.75² + 0.25²) = 0.375\n```\n\nRound to **5 decimal places**.',
    starter_code: 'def gini_impurity(labels: list) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'gini_impurity([1,1,0,0])',expected_output:'0.5',is_hidden:false,description:'Equal split'},
      {id:2,function_call:'gini_impurity([1,1,1])',expected_output:'0.0',is_hidden:false,description:'Pure node'},
      {id:3,function_call:'gini_impurity([1,1,1,0])',expected_output:'0.375',is_hidden:true,description:'3-1 split'},
      {id:4,function_call:'gini_impurity([0,1,2,0,1,2])',expected_output:'0.66667',is_hidden:true,description:'3-class equal'},
    ],
  },
  {
    order_index: 27, title: 'Gradient Clipping', slug: 'gradient-clipping',
    difficulty: 'Easy', topic: 'Deep Learning', tags: ['Deep Learning','Optimization','Training'],
    companies: ['Google','Meta','OpenAI','Nvidia'],
    hints: ['Compute global L2 norm = sqrt(sum of all gradient^2).','If norm > max_norm: scale each gradient by max_norm / norm.','Otherwise return unchanged. Round to 5 decimal places.'],
    description: '## Gradient Clipping by Global Norm\n\nClip gradients so their global L2 norm does not exceed `max_norm`.\n\n```\nnorm = sqrt(Σ gᵢ²)\nif norm > max_norm:\n    gradients = gradients × (max_norm / norm)\n```\n\nRound to **5 decimal places**.',
    starter_code: 'import math\n\ndef clip_gradients(gradients: list, max_norm: float) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'clip_gradients([3.0,4.0],1.0)',expected_output:'[0.6, 0.8]',is_hidden:false,description:'Norm=5, clip to 1'},
      {id:2,function_call:'clip_gradients([0.1,0.2],1.0)',expected_output:'[0.1, 0.2]',is_hidden:false,description:'Norm < max, no clip'},
      {id:3,function_call:'clip_gradients([0.0,0.0],1.0)',expected_output:'[0.0, 0.0]',is_hidden:true,description:'Zero gradients'},
      {id:4,function_call:'clip_gradients([1.0,1.0,1.0,1.0],1.0)',expected_output:'[0.5, 0.5, 0.5, 0.5]',is_hidden:true,description:'4-element clip to 1'},
    ],
  },
  {
    order_index: 28, title: 'K-Fold Split', slug: 'k-fold-split',
    difficulty: 'Medium', topic: 'Classical ML', tags: ['Cross-Validation','Evaluation','Classical ML'],
    companies: ['Google','Meta','Amazon'],
    hints: ['Split range(n_samples) into k roughly equal folds.','For fold i: val_indices = fold[i], train_indices = everything else.','Return list of [train_indices, val_indices] pairs.'],
    description: '## K-Fold Cross-Validation Split\n\nReturn k pairs of `(train_indices, val_indices)` for cross-validation.\n\n- Distribute samples into k folds as evenly as possible\n- For each fold i: val = fold i, train = all other folds\n- Sort train_indices in each pair\n\nReturn list of `[train_indices, val_indices]`.',
    starter_code: 'def k_fold_split(n_samples: int, k: int) -> list:\n    # Returns list of [train_indices, val_indices]\n    pass',
    test_cases: [
      {id:1,function_call:'k_fold_split(6,3)',expected_output:'[[[2, 3, 4, 5], [0, 1]], [[0, 1, 4, 5], [2, 3]], [[0, 1, 2, 3], [4, 5]]]',is_hidden:false,description:'6 samples 3 folds'},
      {id:2,function_call:'k_fold_split(4,2)',expected_output:'[[[2, 3], [0, 1]], [[0, 1], [2, 3]]]',is_hidden:false,description:'4 samples 2 folds'},
      {id:3,function_call:'k_fold_split(5,5)',expected_output:'[[[1, 2, 3, 4], [0]], [[0, 2, 3, 4], [1]], [[0, 1, 3, 4], [2]], [[0, 1, 2, 4], [3]], [[0, 1, 2, 3], [4]]]',is_hidden:true,description:'Leave-one-out'},
    ],
  },
  {
    order_index: 29, title: 'PCA Explained Variance', slug: 'pca-variance',
    difficulty: 'Easy', topic: 'Classical ML', tags: ['PCA','Dimensionality Reduction','Classical ML'],
    companies: ['Google','Meta','Netflix'],
    hints: ['ratio_i = eigenvalue_i / sum(all eigenvalues)','Round to 5 decimal places.'],
    description: '## PCA Explained Variance Ratio\n\nCompute the explained variance ratio from PCA eigenvalues.\n\n`ratio_i = eigenvalue_i / Σ eigenvalues`\n\n```\neigenvalues = [3, 1] → [0.75, 0.25]\neigenvalues = [5, 2, 1] → [0.625, 0.25, 0.125]\n```\n\nRound to **5 decimal places**.',
    starter_code: 'def explained_variance_ratio(eigenvalues: list) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'explained_variance_ratio([3,1])',expected_output:'[0.75, 0.25]',is_hidden:false,description:'2 components'},
      {id:2,function_call:'explained_variance_ratio([5,2,1])',expected_output:'[0.625, 0.25, 0.125]',is_hidden:false,description:'3 components'},
      {id:3,function_call:'explained_variance_ratio([10])',expected_output:'[1.0]',is_hidden:true,description:'Single component'},
      {id:4,function_call:'explained_variance_ratio([1,1,1,1])',expected_output:'[0.25, 0.25, 0.25, 0.25]',is_hidden:true,description:'Equal variance'},
    ],
  },
  {
    order_index: 30, title: 'LR Warmup Schedule', slug: 'learning-rate-warmup',
    difficulty: 'Medium', topic: 'Deep Learning', tags: ['Deep Learning','Optimization','LR Schedule'],
    companies: ['Google','Meta','OpenAI'],
    hints: ['If step <= warmup_steps: lr = base_lr * step / warmup_steps','Else: cosine decay from base_lr to 0','cos_decay = 0.5 * (1 + cos(pi * progress)) where progress = (step-warmup) / (total-warmup)'],
    description: '## Linear Warmup + Cosine Decay\n\nCompute the learning rate at a given training step.\n\n```\nif step <= warmup_steps:\n    lr = base_lr × step / warmup_steps\nelse:\n    progress = (step - warmup_steps) / (total_steps - warmup_steps)\n    lr = base_lr × 0.5 × (1 + cos(π × progress))\n```\n\nRound to **7 decimal places**.',
    starter_code: 'import math\n\ndef get_lr(step: int, warmup_steps: int, total_steps: int, base_lr: float) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'get_lr(5,10,100,0.001)',expected_output:'0.0005',is_hidden:false,description:'Mid warmup'},
      {id:2,function_call:'get_lr(10,10,100,0.001)',expected_output:'0.001',is_hidden:false,description:'End of warmup'},
      {id:3,function_call:'get_lr(0,10,100,0.001)',expected_output:'0.0',is_hidden:true,description:'Step 0'},
      {id:4,function_call:'get_lr(55,10,100,0.001)',expected_output:'0.0005',is_hidden:true,description:'Halfway through decay'},
    ],
  },
  {
    order_index: 31, title: 'Causal Attention Mask', slug: 'attention-mask',
    difficulty: 'Easy', topic: 'Transformers', tags: ['Transformers','Attention','LLM'],
    companies: ['OpenAI','Google','Meta','Anthropic'],
    hints: ['mask[i][j] = 1 if j <= i else 0','This creates a lower-triangular matrix.','Token i can only attend to tokens 0..i (not future tokens).'],
    description: '## Causal (Lower-Triangular) Attention Mask\n\nCreate the causal attention mask used in decoder-only transformers.\n\n`mask[i][j] = 1 if j ≤ i else 0`\n\nToken at position i can attend to all positions 0..i but NOT future positions.\n\n```\nseq_len = 3:\n[[1, 0, 0],\n [1, 1, 0],\n [1, 1, 1]]\n```\n\nReturn as a list of lists of integers.',
    starter_code: 'def causal_mask(seq_len: int) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'causal_mask(3)',expected_output:'[[1, 0, 0], [1, 1, 0], [1, 1, 1]]',is_hidden:false,description:'3x3 mask'},
      {id:2,function_call:'causal_mask(2)',expected_output:'[[1, 0], [1, 1]]',is_hidden:false,description:'2x2 mask'},
      {id:3,function_call:'causal_mask(1)',expected_output:'[[1]]',is_hidden:true,description:'Single token'},
      {id:4,function_call:'causal_mask(4)',expected_output:'[[1, 0, 0, 0], [1, 1, 0, 0], [1, 1, 1, 0], [1, 1, 1, 1]]',is_hidden:true,description:'4x4 mask'},
    ],
  },
  {
    order_index: 32, title: 'ReLU Activation', slug: 'relu-activation',
    difficulty: 'Easy', topic: 'Deep Learning', tags: ['Deep Learning','Activation Functions','Neural Networks'],
    companies: ['Google','Meta','Amazon','Apple'],
    hints: ['ReLU(x) = max(0, x)','Leaky ReLU(x) = x if x > 0 else alpha * x','Round to 5 decimal places.'],
    description: '## ReLU & Leaky ReLU\n\nImplement both ReLU and Leaky ReLU activation functions.\n\n- `ReLU(x) = max(0, x)`\n- `LeakyReLU(x, α) = x if x > 0 else α × x`\n\nReturn `(relu_output, leaky_relu_output)` both rounded to **5 decimal places**.',
    starter_code: 'def relu_variants(x: list, alpha: float = 0.01) -> tuple:\n    """\n    Returns (relu_output, leaky_relu_output)\n    Both are lists rounded to 5 decimal places.\n    """\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'relu_variants([-2.0,-1.0,0.0,1.0,2.0])',expected_output:'([0.0, 0.0, 0.0, 1.0, 2.0], [-0.02, -0.01, 0.0, 1.0, 2.0])',is_hidden:false,description:'Mixed values default alpha'},
      {id:2,function_call:'relu_variants([1.0,2.0,3.0])',expected_output:'([1.0, 2.0, 3.0], [1.0, 2.0, 3.0])',is_hidden:false,description:'All positive'},
      {id:3,function_call:'relu_variants([-5.0,-3.0],0.1)',expected_output:'([0.0, 0.0], [-0.5, -0.3])',is_hidden:true,description:'All negative alpha=0.1'},
      {id:4,function_call:'relu_variants([0.0])',expected_output:'([0.0], [0.0])',is_hidden:true,description:'Zero input'},
    ],
  },
  {
    order_index: 33, title: 'Macro F1 Score', slug: 'multiclass-f1',
    difficulty: 'Medium', topic: 'Classical ML', tags: ['Evaluation','Multiclass','Metrics'],
    companies: ['Google','Meta','Amazon','Microsoft'],
    hints: ['For each class: compute TP, FP, FN then F1.','Macro-average: mean of per-class F1 scores.','If a class has no support (zero TP+FN), set its F1 to 0.','Round to 5 decimal places.'],
    description: '## Macro F1 Score (Multiclass)\n\nCompute macro-averaged F1 score across all classes.\n\n1. For each class c: F1_c = 2×P_c×R_c / (P_c + R_c)\n2. Macro F1 = mean(F1 per class)\n3. If P+R = 0 for a class, F1 = 0\n\nRound to **5 decimal places**.',
    starter_code: 'def macro_f1(y_true: list, y_pred: list, n_classes: int) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'macro_f1([0,1,2,0,1,2],[0,2,1,0,1,2],3)',expected_output:'0.72222',is_hidden:false,description:'3-class mixed'},
      {id:2,function_call:'macro_f1([0,1,0,1],[0,1,0,1],2)',expected_output:'1.0',is_hidden:false,description:'Perfect prediction'},
      {id:3,function_call:'macro_f1([0,0,1,1],[1,1,0,0],2)',expected_output:'0.0',is_hidden:true,description:'All wrong'},
      {id:4,function_call:'macro_f1([0,1,2],[0,0,0],3)',expected_output:'0.22222',is_hidden:true,description:'Predict all class 0'},
    ],
  },
  {
    order_index: 34, title: 'BM25 Score', slug: 'bm25-score',
    difficulty: 'Hard', topic: 'NLP', tags: ['NLP','Information Retrieval','RAG'],
    companies: ['Google','Amazon','Microsoft'],
    hints: ['For each query term: BM25 term score = IDF * (tf*(k1+1)) / (tf + k1*(1-b+b*dl/avgdl))','IDF = log((N - df + 0.5) / (df + 0.5) + 1)','Sum term scores over all query terms in the document.'],
    description: '## BM25 Relevance Score\n\nCompute BM25 score for a document given a query.\n\n**IDF(t)** = `log((N - df(t) + 0.5) / (df(t) + 0.5) + 1)`\n\n**BM25(t, d)** = `IDF(t) × tf(t,d) × (k1+1) / (tf(t,d) + k1 × (1 - b + b × |d| / avgdl))`\n\n**Score** = Σ BM25(t, d) over query terms in document\n\nDefault: k1=1.5, b=0.75. Round to **5 decimal places**.',
    starter_code: 'import math\n\ndef bm25_score(query: list, document: list, corpus: list,\n              k1: float = 1.5, b: float = 0.75) -> float:\n    """\n    query: list of query terms\n    document: list of words in the document to score\n    corpus: list of documents (each a list of words)\n    """\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:"bm25_score(['cat'],['cat','sat','mat'],[['cat','sat'],['dog','ran'],['cat','mat']])",expected_output:'0.44183',is_hidden:false,description:'Single query term'},
      {id:2,function_call:"bm25_score(['dog'],['cat','sat','mat'],[['cat','sat'],['dog','ran'],['cat','mat']])",expected_output:'0.0',is_hidden:false,description:'Term not in document'},
      {id:3,function_call:"bm25_score(['cat','mat'],['cat','mat','cat'],[['cat'],['mat'],['cat','mat']])",expected_output:'1.64791',is_hidden:true,description:'Two matching terms'},
    ],
  },
  {
    order_index: 35, title: 'Text Preprocessing', slug: 'text-preprocessing',
    difficulty: 'Easy', topic: 'NLP', tags: ['NLP','Text Processing','Features'],
    companies: ['Google','Amazon','Meta'],
    hints: ['Lowercase the text.','Remove punctuation (.,!?;:).','Split on whitespace.','Remove stopwords.'],
    description: '## NLP Text Preprocessing\n\nPreprocess text for NLP tasks.\n\n1. Lowercase\n2. Remove punctuation (`.,!?;:`)\n3. Split on whitespace\n4. Remove stopwords from the provided list\n5. Return remaining tokens\n\n```\ntext = "The cat sat on the mat!"\nstopwords = ["the", "on"]\nOutput: ["cat", "sat", "mat"]\n```',
    starter_code: 'def preprocess_text(text: str, stopwords: list) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:"preprocess_text('The cat sat on the mat!',['the','on'])",expected_output:"['cat', 'sat', 'mat']",is_hidden:false,description:'Basic stopword removal'},
      {id:2,function_call:"preprocess_text('AI and ML are great!',['and','are'])",expected_output:"['ai', 'ml', 'great']",is_hidden:false,description:'Tech text'},
      {id:3,function_call:"preprocess_text('Hello, world.',[])",expected_output:"['hello', 'world']",is_hidden:true,description:'No stopwords'},
      {id:4,function_call:"preprocess_text('a b c',['a','b','c'])",expected_output:"[]",is_hidden:true,description:'All removed'},
    ],
  },
  // ── 10 NEW PROBLEMS ────────────────────────────────────────────────────────
  {
    order_index: 36, title: 'GRU Step', slug: 'gru-step',
    difficulty: 'Hard', topic: 'Deep Learning', tags: ['Deep Learning','GRU','Sequence Models'],
    companies: ['Google','Meta','Amazon','Apple'],
    hints: ['r = sigmoid(wr * (x + h_prev))  # reset gate','z = sigmoid(wz * (x + h_prev))  # update gate','n = tanh(wn * (x + r * h_prev)) # new gate','h_new = (1 - z) * h_prev + z * n'],
    description: '## Simplified Scalar GRU Step\n\nImplement one step of a scalar GRU cell.\n\n```\nr = sigmoid(wr × (x + h_prev))   # reset gate\nz = sigmoid(wz × (x + h_prev))   # update gate\nn = tanh(wn × (x + r × h_prev))  # new gate\nh_new = (1 - z) × h_prev + z × n\n```\n\nReturn `h_new` rounded to **5 decimal places**.',
    starter_code: 'import math\n\ndef gru_step(x: float, h_prev: float, wr: float, wz: float, wn: float) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'gru_step(1.0,0.0,1.0,1.0,1.0)',expected_output:'0.55694',is_hidden:false,description:'Zero initial state'},
      {id:2,function_call:'gru_step(0.0,0.0,1.0,1.0,1.0)',expected_output:'0.0',is_hidden:false,description:'Zero input'},
      {id:3,function_call:'gru_step(1.0,0.5,0.5,1.0,1.0)',expected_output:'0.65852',is_hidden:true,description:'Non-zero initial state'},
      {id:4,function_call:'gru_step(-1.0,1.0,1.0,0.0,1.0)',expected_output:'1.0',is_hidden:true,description:'Zero update gate keeps old state'},
    ],
  },
  {
    order_index: 37, title: 'Gaussian Naive Bayes', slug: 'naive-bayes-predict',
    difficulty: 'Medium', topic: 'Classical ML', tags: ['Naive Bayes','Classification','Probability'],
    companies: ['Google','Amazon','Meta'],
    hints: ['For each class: log_score = log(prior) + sum of log gaussian likelihoods','log N(x|μ,σ) = -0.5*log(2π) - log(σ) - 0.5*((x-μ)/σ)²','Return the class index with the highest log score.'],
    description: '## Gaussian Naive Bayes Classifier\n\nClassify a feature vector using Gaussian Naive Bayes.\n\nFor each class c:\n`log P(c|x) ∝ log(prior_c) + Σᵢ log N(xᵢ | μ_c[i], σ_c[i])`\n\nReturn the class index with the highest log score.\n\n```\nN(x|μ,σ) = (1/σ√2π) × exp(-0.5 × ((x-μ)/σ)²)\n```',
    starter_code: 'import math\n\ndef gaussian_nb(x: list, means: list, stds: list, priors: list) -> int:\n    """\n    x: feature vector\n    means: list of per-class mean vectors\n    stds: list of per-class std vectors\n    priors: prior probability per class\n    Returns: predicted class index\n    """\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'gaussian_nb([1.0],[[0.0],[4.0]],[[1.0],[1.0]],[0.5,0.5])',expected_output:'0',is_hidden:false,description:'x=1 closer to class 0 mean=0'},
      {id:2,function_call:'gaussian_nb([3.0],[[0.0],[4.0]],[[1.0],[1.0]],[0.5,0.5])',expected_output:'1',is_hidden:false,description:'x=3 closer to class 1 mean=4'},
      {id:3,function_call:'gaussian_nb([1.0,2.0],[[0.0,0.0],[3.0,3.0]],[[1.0,1.0],[1.0,1.0]],[0.5,0.5])',expected_output:'0',is_hidden:true,description:'2D features class 0'},
      {id:4,function_call:'gaussian_nb([2.0],[[0.0],[1.0]],[[1.0],[1.0]],[0.1,0.9])',expected_output:'1',is_hidden:true,description:'Prior favours class 1'},
    ],
  },
  {
    order_index: 38, title: 'NDCG@k', slug: 'ndcg-score',
    difficulty: 'Medium', topic: 'Classical ML', tags: ['Evaluation','Ranking','Information Retrieval'],
    companies: ['Google','Meta','Amazon','Netflix'],
    hints: ['DCG@k = Σᵢ rel[i] / log₂(i+2) for i in 0..k-1','IDCG@k = DCG@k of the ideally sorted relevances','NDCG@k = DCG@k / IDCG@k','If IDCG = 0, return 0.0'],
    description: '## NDCG@k (Normalised Discounted Cumulative Gain)\n\nCompute NDCG@k for a ranked list of relevance scores.\n\n`DCG@k = Σᵢ rel[i] / log₂(i+2)` for i=0..k-1\n\n`IDCG@k` = DCG@k of the ideally sorted list (descending)\n\n`NDCG@k = DCG@k / IDCG@k`\n\nRound to **5 decimal places**.',
    starter_code: 'import math\n\ndef ndcg_at_k(relevances: list, k: int) -> float:\n    """\n    relevances: relevance scores in ranked order (index 0 = top result)\n    k: cutoff rank\n    Returns: NDCG@k rounded to 5 decimal places\n    """\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'ndcg_at_k([3,2,3,0,1,2],3)',expected_output:'0.97779',is_hidden:false,description:'Standard NDCG@3'},
      {id:2,function_call:'ndcg_at_k([3,3,3],3)',expected_output:'1.0',is_hidden:false,description:'Perfect ranking'},
      {id:3,function_call:'ndcg_at_k([0,0,3],3)',expected_output:'0.5',is_hidden:true,description:'Relevant result at bottom'},
      {id:4,function_call:'ndcg_at_k([0,0,0],3)',expected_output:'0.0',is_hidden:true,description:'No relevant results'},
    ],
  },
  {
    order_index: 39, title: 'Dropout Forward Pass', slug: 'dropout-forward',
    difficulty: 'Easy', topic: 'Deep Learning', tags: ['Deep Learning','Regularisation','Neural Networks'],
    companies: ['Google','Meta','OpenAI','Nvidia'],
    hints: ['Apply mask: output[i] = x[i] * mask[i]','Scale surviving activations by 1/(1-p) — inverted dropout.','Round to 5 decimal places.'],
    description: '## Dropout Forward Pass (Inverted Dropout)\n\nApply dropout to an input vector during training.\n\n1. Apply the binary mask: `output[i] = x[i] × mask[i]`\n2. Scale surviving activations by `1 / (1 - p)` (inverted dropout)\n\n`mask[i] = 1` means keep, `mask[i] = 0` means drop.\n\nRound to **5 decimal places**.',
    starter_code: 'def dropout_forward(x: list, p: float, mask: list) -> list:\n    """\n    x: input values\n    p: dropout probability (probability of zeroing out)\n    mask: binary mask (0=drop, 1=keep), same length as x\n    Returns: scaled output with dropout applied\n    """\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'dropout_forward([1.0,2.0,3.0,4.0],0.5,[1,0,1,0])',expected_output:'[2.0, 0.0, 6.0, 0.0]',is_hidden:false,description:'50% dropout'},
      {id:2,function_call:'dropout_forward([1.0,2.0,3.0],0.0,[1,1,1])',expected_output:'[1.0, 2.0, 3.0]',is_hidden:false,description:'Zero dropout no change'},
      {id:3,function_call:'dropout_forward([2.0,4.0,6.0],0.25,[1,0,1])',expected_output:'[2.66667, 0.0, 8.0]',is_hidden:true,description:'25% dropout'},
      {id:4,function_call:'dropout_forward([1.0,1.0],0.5,[0,0])',expected_output:'[0.0, 0.0]',is_hidden:true,description:'All dropped'},
    ],
  },
  {
    order_index: 40, title: 'Confusion Matrix', slug: 'confusion-matrix',
    difficulty: 'Easy', topic: 'Classical ML', tags: ['Evaluation','Classification','Metrics'],
    companies: ['Google','Meta','Amazon','Microsoft'],
    hints: ['cm[i][j] = number of samples with true class i predicted as class j.','Initialise an n_classes × n_classes matrix of zeros.','Iterate through y_true and y_pred, incrementing cm[true][pred].'],
    description: '## Confusion Matrix\n\nCompute the confusion matrix.\n\n`cm[i][j]` = number of samples with **true class i** predicted as **class j**.\n\n```\ny_true = [0,1,2,0,1], y_pred = [0,2,1,0,1], n_classes = 3\ncm = [[2,0,0],[0,1,1],[0,1,0]]\n```\n\nReturn as a list of lists.',
    starter_code: 'def confusion_matrix(y_true: list, y_pred: list, n_classes: int) -> list:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'confusion_matrix([0,1,2,0,1,2],[0,2,1,0,1,2],3)',expected_output:'[[2, 0, 0], [0, 1, 1], [0, 1, 1]]',is_hidden:false,description:'3-class'},
      {id:2,function_call:'confusion_matrix([0,1,0,1],[0,1,0,1],2)',expected_output:'[[2, 0], [0, 2]]',is_hidden:false,description:'Perfect binary'},
      {id:3,function_call:'confusion_matrix([0,0,1,1],[1,1,0,0],2)',expected_output:'[[0, 2], [2, 0]]',is_hidden:true,description:'All wrong'},
      {id:4,function_call:'confusion_matrix([0,1,2],[0,0,0],3)',expected_output:'[[1, 0, 0], [0, 0, 1], [0, 0, 1]]',is_hidden:true,description:'Predict all class 0'},
    ],
  },
  {
    order_index: 41, title: 'Covariance Matrix', slug: 'covariance-matrix',
    difficulty: 'Medium', topic: 'Classical ML', tags: ['Statistics','PCA','Linear Algebra'],
    companies: ['Google','Meta','Netflix'],
    hints: ['Compute mean of x and y separately.','cov(x,y) = mean((x - mean_x) * (y - mean_y))','Use population covariance (divide by N, not N-1).','Round to 5 decimal places.'],
    description: '## 2D Covariance Matrix\n\nCompute the population covariance matrix for a 2D dataset.\n\n```\ncov(X, Y) = (1/N) Σ (xᵢ - μₓ)(yᵢ - μᵧ)\nMatrix: [[var(x), cov(x,y)], [cov(x,y), var(y)]]\n```\n\nRound to **5 decimal places**.',
    starter_code: 'def covariance_matrix(data: list) -> list:\n    """\n    data: list of [x, y] pairs\n    Returns: 2x2 covariance matrix\n    """\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'covariance_matrix([[1,2],[2,4],[3,6]])',expected_output:'[[0.66667, 1.33333], [1.33333, 2.66667]]',is_hidden:false,description:'Perfectly correlated'},
      {id:2,function_call:'covariance_matrix([[1,3],[2,2],[3,1]])',expected_output:'[[0.66667, -0.66667], [-0.66667, 0.66667]]',is_hidden:false,description:'Negatively correlated'},
      {id:3,function_call:'covariance_matrix([[0,0],[0,0],[0,0]])',expected_output:'[[0.0, 0.0], [0.0, 0.0]]',is_hidden:true,description:'Zero variance'},
      {id:4,function_call:'covariance_matrix([[1,2],[3,4]])',expected_output:'[[1.0, 1.0], [1.0, 1.0]]',is_hidden:true,description:'Two points'},
    ],
  },
  {
    order_index: 42, title: 'Intersection over Union (IoU)', slug: 'iou-score',
    difficulty: 'Easy', topic: 'Deep Learning', tags: ['Computer Vision','Object Detection','Evaluation'],
    companies: ['Google','Meta','Apple','Amazon'],
    hints: ['Intersection: [max(x1A,x1B), max(y1A,y1B), min(x2A,x2B), min(y2A,y2B)]','If intersection width or height ≤ 0, IoU = 0.','Union = area_A + area_B - intersection_area'],
    description: '## Intersection over Union (IoU)\n\nCompute IoU for two bounding boxes in `[x1, y1, x2, y2]` format.\n\n```\nIoU = intersection_area / union_area\nunion = area(A) + area(B) - intersection\n```\n\nIf boxes do not overlap, return 0.0.\n\nRound to **5 decimal places**.',
    starter_code: 'def iou(box1: list, box2: list) -> float:\n    """\n    box format: [x1, y1, x2, y2]\n    (x1,y1) = top-left, (x2,y2) = bottom-right\n    """\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'iou([0,0,2,2],[1,1,3,3])',expected_output:'0.14286',is_hidden:false,description:'Partial overlap'},
      {id:2,function_call:'iou([0,0,2,2],[0,0,2,2])',expected_output:'1.0',is_hidden:false,description:'Identical boxes'},
      {id:3,function_call:'iou([0,0,1,1],[2,2,3,3])',expected_output:'0.0',is_hidden:true,description:'No overlap'},
      {id:4,function_call:'iou([0,0,4,4],[1,1,2,2])',expected_output:'0.0625',is_hidden:true,description:'One box inside other'},
    ],
  },
  {
    order_index: 43, title: 'Random Forest Vote', slug: 'random-forest-vote',
    difficulty: 'Easy', topic: 'Classical ML', tags: ['Random Forest','Ensemble','Classification'],
    companies: ['Google','Meta','Amazon','Netflix','Apple'],
    hints: ['Count the frequency of each class label.','Return the class with the highest count.','Ties: return the lower class number.'],
    description: '## Random Forest Majority Vote\n\nGiven predictions from K decision trees, determine the final class via majority voting.\n\n- Return the class label that appears most frequently\n- Ties: return the numerically smallest class label\n\n```\npredictions = [0, 1, 0, 1, 0] → majority = 0\npredictions = [1, 2, 1, 2, 2] → majority = 2\n```',
    starter_code: 'def majority_vote(predictions: list) -> int:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'majority_vote([0,1,0,1,0])',expected_output:'0',is_hidden:false,description:'Class 0 wins'},
      {id:2,function_call:'majority_vote([1,2,1,2,2])',expected_output:'2',is_hidden:false,description:'Class 2 wins'},
      {id:3,function_call:'majority_vote([0,1])',expected_output:'0',is_hidden:true,description:'Tie goes to lower class'},
      {id:4,function_call:'majority_vote([3,3,3,1,1])',expected_output:'3',is_hidden:true,description:'Unambiguous majority'},
    ],
  },
  {
    order_index: 44, title: 'MLE for Gaussian', slug: 'mle-gaussian',
    difficulty: 'Easy', topic: 'Classical ML', tags: ['Statistics','MLE','Probability'],
    companies: ['Google','Meta','DeepMind'],
    hints: ['mu = mean of data','sigma = population standard deviation (divide by N, not N-1)','Round both to 5 decimal places.'],
    description: '## Maximum Likelihood Estimates for Gaussian\n\nCompute the MLE estimates for a Gaussian distribution.\n\n- `μ_MLE = (1/N) Σ xᵢ` (sample mean)\n- `σ_MLE = √((1/N) Σ (xᵢ - μ)²)` (population std, N denominator)\n\nReturn `(mu, sigma)` both rounded to **5 decimal places**.',
    starter_code: 'import math\n\ndef mle_gaussian(data: list) -> tuple:\n    # Returns (mu, sigma)\n    pass',
    test_cases: [
      {id:1,function_call:'mle_gaussian([2.0,4.0,4.0,4.0,5.0,5.0,7.0,9.0])',expected_output:'(5.0, 2.0)',is_hidden:false,description:'Classic textbook example'},
      {id:2,function_call:'mle_gaussian([3.0,3.0,3.0])',expected_output:'(3.0, 0.0)',is_hidden:false,description:'Constant data zero variance'},
      {id:3,function_call:'mle_gaussian([0.0,10.0])',expected_output:'(5.0, 5.0)',is_hidden:true,description:'Two values'},
      {id:4,function_call:'mle_gaussian([1.0,2.0,3.0,4.0,5.0])',expected_output:'(3.0, 1.41421)',is_hidden:true,description:'Uniform sequence'},
    ],
  },
  {
    order_index: 45, title: 'L2 Regularisation Loss', slug: 'l2-regularization-loss',
    difficulty: 'Easy', topic: 'Classical ML', tags: ['Regularisation','Loss Functions','Training'],
    companies: ['Google','Meta','Amazon'],
    hints: ['MSE = mean((y_true - y_pred)²)','L2 penalty = (lambda / 2) * sum(w²)','Total loss = MSE + L2 penalty','Round to 5 decimal places.'],
    description: '## Regularised MSE Loss with L2 Penalty\n\nCompute the total loss: MSE + L2 regularisation.\n\n`loss = MSE(y_true, y_pred) + (λ/2) × Σ wᵢ²`\n\nThe λ/2 convention simplifies the gradient (2×λ/2 = λ).\n\nRound to **5 decimal places**.',
    starter_code: 'def l2_reg_loss(y_true: list, y_pred: list, weights: list, lambda_: float) -> float:\n    # Your code here\n    pass',
    test_cases: [
      {id:1,function_call:'l2_reg_loss([1.0,2.0],[1.5,2.5],[0.5,0.5],0.1)',expected_output:'0.275',is_hidden:false,description:'Basic regularised loss'},
      {id:2,function_call:'l2_reg_loss([1.0,2.0],[1.0,2.0],[0.5,0.5],0.1)',expected_output:'0.025',is_hidden:false,description:'Perfect predictions, only L2'},
      {id:3,function_call:'l2_reg_loss([1.0],[2.0],[0.0],0.5)',expected_output:'1.0',is_hidden:true,description:'Zero weights no penalty'},
      {id:4,function_call:'l2_reg_loss([0.0,0.0],[1.0,1.0],[1.0,1.0],1.0)',expected_output:'2.0',is_hidden:true,description:'High penalty high error'},
    ],
  },
]

// Build a lookup map by slug for O(1) access
export const STATIC_PROBLEMS_MAP: Record<string, StaticProblem> = Object.fromEntries(
  STATIC_PROBLEMS.map(p => [p.slug, p])
)
