import { NextResponse } from 'next/server'
import { getAdminSupabase } from '@/lib/admin'

export const runtime = 'nodejs'

const QUESTIONS = [
  // ── LLM ─────────────────────────────────────────────────────────────────────
  { topic: 'LLM', level: 'mid', question: 'What is the difference between GPT-3 and GPT-4 architecturally?', answer: 'GPT-4 is a multimodal model that can accept image and text inputs, uses a larger context window (up to 128k tokens with Turbo), and is believed to use a Mixture of Experts (MoE) architecture with ~8 experts. GPT-3 is a dense transformer with 175B parameters, text-only, and 4k context window. GPT-4 has significantly improved reasoning, reduced hallucinations, and passes professional exams at high percentiles.' },
  { topic: 'LLM', level: 'fresher', question: 'What is a token in the context of LLMs?', answer: 'A token is the basic unit of text that LLMs process. It can be a word, part of a word, or punctuation depending on the tokenizer. For example, "ChatGPT" might be split into ["Chat", "G", "PT"]. The most common tokenizer is BPE (Byte Pair Encoding). GPT-4 uses approximately 4 characters per token on average. Tokens determine the model\'s context window limit and API pricing.' },
  { topic: 'LLM', level: 'mid', question: 'Explain the concept of scaling laws in LLMs.', answer: 'Scaling laws (Kaplan et al., Chinchilla) describe predictable relationships between model size, training data, compute budget, and model performance. Key finding: performance improves as a power law with scale. Chinchilla paper showed that for a given compute budget, you should balance model size and training tokens approximately equally (e.g., 70B model trained on 1.4T tokens performs better than 280B model on 700B tokens). This guides decisions on training runs.' },
  { topic: 'LLM', level: 'senior', question: 'What is Constitutional AI and how does Anthropic use it?', answer: 'Constitutional AI (CAI) is a training method where the model is guided by a set of principles (a "constitution") rather than just human feedback. The process: 1) Generate responses, 2) Have the AI critique its own responses against the constitution, 3) Revise based on critiques, 4) Train on the revised responses. This reduces reliance on human labelers for identifying harmful content. Anthropic uses CAI to train Claude, making it helpful, harmless, and honest without needing extensive human feedback on every harmful output.' },
  { topic: 'LLM', level: 'mid', question: 'What is the difference between zero-shot, one-shot, and few-shot prompting?', answer: 'Zero-shot: ask the model to perform a task with no examples — relies entirely on training knowledge. One-shot: provide one example in the prompt before the task. Few-shot: provide 2-5+ examples. Few-shot prompting was a key finding in the GPT-3 paper showing LLMs can learn from context examples. The model is not fine-tuned; it adapts based on the pattern shown in the prompt. Best practice: use 3-5 diverse, high-quality examples in the same format as the desired output.' },
  { topic: 'LLM', level: 'senior', question: 'How does RLHF work and what are its limitations?', answer: 'RLHF (Reinforcement Learning from Human Feedback): 1) Supervised fine-tuning on demonstrations, 2) Train a reward model on human preference comparisons, 3) Use PPO to optimize the policy (LLM) to maximize the reward model\'s score. Limitations: reward hacking (model finds ways to maximize reward that don\'t reflect actual quality), reward model can be fooled, human annotators have biases and inconsistencies, expensive and slow to scale, the KL penalty to prevent the model from drifting too far adds complexity.' },
  { topic: 'LLM', level: 'mid', question: 'What is chain-of-thought prompting and when should you use it?', answer: 'Chain-of-thought (CoT) prompting encourages the model to show its reasoning steps before giving a final answer. Example: "Q: Roger has 5 tennis balls... Let\'s think step by step: Roger starts with 5 balls, buys 2 cans of 3 balls each, so 2×3=6 new balls, 5+6=11 total. A: 11." CoT significantly improves performance on math, reasoning, and logical tasks. Use when: the task requires multi-step reasoning, arithmetic, or logical deduction. Zero-shot CoT: just append "Let\'s think step by step" to your prompt.' },
  { topic: 'LLM', level: 'senior', question: 'What is speculative decoding and how does it speed up inference?', answer: 'Speculative decoding uses a small "draft" model to generate candidate tokens quickly, then uses the larger target model to verify multiple tokens in parallel. Since the target model can process multiple tokens in one forward pass (verification is faster than generation), you get significant speedups when the draft model\'s predictions are often correct. Deepmind showed 2-3x speedup with minimal quality loss. The technique is now used in production at Anthropic and other labs.' },
  { topic: 'LLM', level: 'mid', question: 'What are the key differences between encoder-only, decoder-only, and encoder-decoder architectures?', answer: 'Encoder-only (BERT): bidirectional attention, sees all tokens at once, good for classification, NER, QA. Cannot generate text autoregressively. Decoder-only (GPT): causal/unidirectional attention, generates tokens left-to-right, best for generation tasks. Encoder-decoder (T5, BART): encoder processes input with bidirectional attention, decoder generates output with cross-attention to encoder. Best for seq2seq tasks like translation, summarization. Most modern LLMs are decoder-only as generation is the dominant use case.' },
  { topic: 'LLM', level: 'fresher', question: 'What is temperature in LLM sampling and how does it affect output?', answer: 'Temperature controls randomness in sampling. Low temperature (0.1-0.3): more deterministic, picks highest probability tokens, outputs are focused and repetitive. High temperature (0.8-1.2): more random, samples lower probability tokens, more creative and diverse. Temperature=0: greedy decoding (always pick the highest probability token). Temperature scales the logits before softmax: logits/temperature. Use low temperature for factual tasks, high temperature for creative writing. Temperature=1.0 = unchanged distribution.' },
  // ── RAG ─────────────────────────────────────────────────────────────────────
  { topic: 'RAG', level: 'mid', question: 'What is Retrieval-Augmented Generation (RAG) and why is it used?', answer: 'RAG combines a retrieval system with a generative LLM. The pipeline: 1) Query → retrieve relevant documents from a knowledge base (using vector search), 2) Augment the prompt with retrieved context, 3) Generate answer conditioned on the context. Used to: reduce hallucinations by grounding responses in actual data, allow access to up-to-date/proprietary information without fine-tuning, provide source attribution. RAG is preferred over fine-tuning for dynamic knowledge bases.' },
  { topic: 'RAG', level: 'senior', question: 'What is the difference between naive RAG, advanced RAG, and modular RAG?', answer: 'Naive RAG: simple pipeline — index, retrieve, generate. Problems: poor precision/recall, lost-in-the-middle issue, redundant context. Advanced RAG: pre-retrieval (query rewriting, HyDE), retrieval improvements (hybrid search, reranking), post-retrieval (context compression, reordering). Modular RAG: treats RAG as configurable modules — any retriever, any reranker, any generator can be swapped. Examples: FLARE (iterative retrieval), Fusion-in-Decoder, Self-RAG (model decides when to retrieve).' },
  { topic: 'RAG', level: 'mid', question: 'What chunking strategies exist for RAG and when do you use each?', answer: 'Fixed-size: simple, split by character/token count with overlap (e.g., 512 tokens, 50 overlap). Good as baseline. Sentence-based: split on sentence boundaries, preserves semantic coherence. Paragraph-based: preserves topical coherence, variable size. Recursive: try to split on natural boundaries (paragraphs → sentences → words). Semantic chunking: embed sentences and split where similarity drops — computationally expensive but best coherence. Document-specific: parse tables, headers as separate chunks. Rule of thumb: chunk size should match the granularity of your queries.' },
  { topic: 'RAG', level: 'senior', question: 'What is HyDE (Hypothetical Document Embeddings) and when should you use it?', answer: 'HyDE generates a hypothetical document that would answer the query (using an LLM), then retrieves based on the embedding of that hypothetical document rather than the query itself. The idea: the hypothetical answer is semantically closer to real answers in the vector space than the question is. Use when: queries are short/abstract and documents are long/detailed, there is a large distribution mismatch between query and document style. Downside: adds LLM inference cost before retrieval, can propagate hallucinations into the retrieval step.' },
  { topic: 'RAG', level: 'mid', question: 'What is the "lost in the middle" problem in RAG?', answer: 'Research shows LLMs attend more strongly to information at the beginning and end of their context window, and poorly to information in the middle. In RAG, if relevant content is placed in the middle of a long context, the model may miss it. Solutions: rerank retrieved chunks so most relevant are at start/end, use context compression to remove less relevant chunks, use models with better long-context attention (e.g., Longformer), limit context size to most relevant chunks only.' },
  { topic: 'RAG', level: 'senior', question: 'How do you evaluate a RAG system end-to-end?', answer: 'Component-level: retrieval metrics (NDCG, MRR, Precision@K, Recall@K), generation metrics (RAGAS: faithfulness, answer relevancy, context precision, context recall). System-level: end-to-end QA accuracy, human evaluation, LLM-as-judge. RAGAS framework specifically: Faithfulness (are claims grounded in context?), Answer Relevancy (does it answer the question?), Context Precision (how much of retrieved context is relevant?), Context Recall (does retrieved context cover ground truth?). Also track: latency, cost per query, hallucination rate.' },
  // ── Agents ────────────────────────────────────────────────────────────────────
  { topic: 'Agents', level: 'mid', question: 'What is the ReAct framework for AI agents?', answer: 'ReAct (Reasoning + Acting) interleaves reasoning traces and actions. The agent: 1) Reasons about what to do next (Thought), 2) Takes an action (Action + tool call), 3) Observes the result (Observation), 4) Repeats until task is complete. Advantages: reasoning explains agent behavior, allows course correction. Key components: a prompt that describes available tools and the ReAct format, tool implementations (search, calculator, code executor), a stopping condition.' },
  { topic: 'Agents', level: 'senior', question: 'What is the difference between single-agent and multi-agent architectures?', answer: 'Single-agent: one LLM handles the entire task, using tools as needed. Simple but can struggle with complex tasks requiring diverse capabilities. Multi-agent: multiple specialized LLMs collaborate — e.g., researcher, writer, critic agents. Patterns: supervisor (one agent delegates to others), pipeline (sequential handoffs), debate (agents challenge each other). Frameworks: LangGraph (state machine), CrewAI (role-based), AutoGen (conversation-based). Multi-agent adds coordination overhead but handles complex tasks better through specialization.' },
  { topic: 'Agents', level: 'mid', question: 'How do you prevent AI agents from going into infinite loops?', answer: 'Strategies: max_iterations limit (hard stop after N steps), max_execution_time timeout, cycle detection (track visited states/actions), stopping conditions in the prompt ("stop when you have a final answer"), human-in-the-loop checkpoints for long-running tasks, output parsers that detect when the agent is stuck, HALT signal in the action space. Best practice: combine multiple mechanisms — max iterations is the safety net, good prompting reduces the need to hit it.' },
  { topic: 'Agents', level: 'senior', question: 'What is tool/function calling and how does it work in modern LLMs?', answer: 'Tool calling (OpenAI function calling, Anthropic tool use): the model is given JSON schemas for available functions and can choose to call them with structured arguments. Mechanism: 1) Include tool schemas in the API request, 2) Model outputs a tool_call instead of text when it wants to use a tool, 3) You execute the tool, 4) Return the result in the next message, 5) Model uses the result to generate a response. Parallel tool calling: GPT-4 can call multiple tools simultaneously (returns a list of tool_calls). Better than unstructured function calling because it\'s JSON-valid and structured.' },
  { topic: 'Agents', level: 'mid', question: 'What is agent memory and what are the different types?', answer: 'Short-term memory: the current conversation context window — shared with the LLM in each call. Long-term memory: external storage (databases, vector stores) that persists across sessions — agent retrieves relevant memories. Episodic memory: past interactions and experiences. Semantic memory: facts and knowledge. Working memory: intermediate results during a task. Implementation: store memories as embeddings in a vector DB, retrieve k most relevant using similarity search before each LLM call. Tools like MemGPT implement "self-editing" memory where the agent manages what to remember.' },
  // ── Fine-Tuning ───────────────────────────────────────────────────────────────
  { topic: 'Fine-Tuning', level: 'mid', question: 'What is the difference between full fine-tuning and PEFT methods?', answer: 'Full fine-tuning: update all model parameters, requires massive GPU memory (e.g., 7B model needs ~28GB in bfloat16 just to store weights, plus optimizer states ~3x), but achieves best performance. PEFT (Parameter-Efficient Fine-Tuning): update only a small fraction of parameters. Methods: LoRA (inject low-rank matrices, ~0.1% of params), Prefix Tuning (prepend trainable tokens), Adapters (add small feed-forward layers between transformer blocks), Prompt Tuning (optimize continuous prompt vectors). PEFT preserves base model weights, allows serving multiple fine-tuned versions with one base model.' },
  { topic: 'Fine-Tuning', level: 'senior', question: 'Explain QLoRA and how it enables fine-tuning large models on consumer hardware.', answer: 'QLoRA (Quantized LoRA) combines: 1) 4-bit NormalFloat quantization of the frozen base model (NF4 is optimal for normally-distributed weights), 2) Double quantization (quantize the quantization constants), 3) Paged optimizers (offload optimizer states to CPU when GPU OOM). LoRA adapters are trained in 16-bit while the base model stays 4-bit. Result: 65B model fine-tunes on a single 48GB GPU (vs 640GB for full 16-bit). Key hyperparameters: r (rank), alpha (scaling), target modules (typically q_proj, v_proj).' },
  { topic: 'Fine-Tuning', level: 'mid', question: 'What is catastrophic forgetting and how do you mitigate it in fine-tuning?', answer: 'Catastrophic forgetting: when fine-tuning on new data, the model forgets previously learned knowledge. Mitigation strategies: Elastic Weight Consolidation (EWC) — penalize changes to important weights, Replay — mix original training data with new data, LoRA — only updates low-rank matrices so base model knowledge is preserved, low learning rate (1e-4 to 1e-5), few training epochs (1-3), domain-specific evaluation to detect forgetting. For instruction fine-tuning: include a mix of general instruction data (Alpaca, FLAN) with domain-specific data.' },
  { topic: 'Fine-Tuning', level: 'senior', question: 'What is DPO (Direct Preference Optimization) and how does it compare to RLHF?', answer: 'DPO trains directly from human preference data without a separate reward model or RL. It reformulates RLHF as a classification problem: given pairs of (chosen, rejected) responses, maximize likelihood of chosen over rejected with a KL constraint. Advantages over RLHF: no reward model training, no PPO (which is unstable), simpler pipeline, computationally cheaper. The objective: maximize log(σ(β × (log(π/π_ref)(chosen) - log(π/π_ref)(rejected)))). Used by Llama 2 chat and many open models. RLHF still has edge in some benchmarks but DPO is the practical choice.' },
  { topic: 'Fine-Tuning', level: 'mid', question: 'How do you prepare a dataset for instruction fine-tuning?', answer: 'Format: convert to instruction-following format — system prompt + user instruction + assistant response. Common formats: ChatML (<|im_start|>system\n...<|im_end|>), Llama chat format, Alpaca format. Data quality checklist: remove duplicates, filter short/low-quality responses, ensure diverse topics, balance difficulty levels. Data sources: Alpaca (GPT-4 generated), OpenAssistant (human conversations), FLAN (academic tasks), ShareGPT (real ChatGPT conversations). Min size: 1K examples for domain fine-tuning, 10K+ for general instruction following. Always evaluate on a held-out set.' },
  // ── MLOps ─────────────────────────────────────────────────────────────────────
  { topic: 'MLOps', level: 'mid', question: 'What is the difference between ML training and inference infrastructure?', answer: 'Training: high-memory GPUs (A100 80GB, H100), need fast interconnect (NVLink, InfiniBand) for multi-GPU, high storage I/O for training data, spot instances acceptable (with checkpointing), synchronous batch processing. Inference: optimize for latency and throughput, can use quantized models (INT8, INT4), batching requests, horizontal scaling, need SLA guarantees, support for dynamic batching (vLLM, TGI), KV-cache management. Inference cost is 10-100x the amortized training cost at scale, so optimization is critical.' },
  { topic: 'MLOps', level: 'senior', question: 'How do you detect and handle model drift in production?', answer: 'Data drift: input distribution changes (feature statistics, text topics). Concept drift: relationship between inputs and outputs changes. Detection methods: statistical tests (KS test, PSI — Population Stability Index), embedding drift (compare distributions in vector space), prediction drift (monitor output distribution), custom metrics (accuracy on labeled samples). Responses: automated retraining pipelines triggered by drift signals, shadow deployment of new model, A/B testing, canary deployment. Tools: Evidently AI, WhyLabs, Arize, Fiddler. Track: data quality metrics, model performance metrics, operational metrics.' },
  { topic: 'MLOps', level: 'mid', question: 'What is vLLM and why is it important for LLM serving?', answer: 'vLLM is an LLM serving framework that implements PagedAttention — a memory management technique inspired by OS paging that dramatically improves GPU memory utilization for KV-cache. Traditional serving wastes memory due to fragmentation from variable-length sequences. PagedAttention stores KV-cache in non-contiguous blocks, allowing up to 24x more throughput than HuggingFace Transformers. Also supports: continuous batching, tensor parallelism, quantization (GPTQ, AWQ). Widely used in production at scale for cost-effective inference.' },
  { topic: 'MLOps', level: 'senior', question: 'What metrics do you track for an LLM in production?', answer: 'Quality metrics: task-specific accuracy (e.g., BLEU, ROUGE, answer correctness), user satisfaction ratings, hallucination rate, safety filter triggers. Operational metrics: latency (P50, P95, P99 TTFT — Time To First Token, and TPOT — Time Per Output Token), throughput (tokens/second), error rates, retry rates. Cost metrics: cost per query, GPU utilization, tokens per dollar. Business metrics: task completion rate, user engagement, escalation rate. Alert on: latency spikes, accuracy drops, unusual output distribution, cost anomalies.' },
  { topic: 'MLOps', level: 'mid', question: 'What is A/B testing for ML models and how do you implement it?', answer: 'Split traffic between model A (control) and model B (experiment) to compare performance under real conditions. Implementation: traffic splitting at the API gateway level (10% to B, 90% to A), track metrics per variant with consistent user assignment (hash user_id to ensure same user always gets same variant), run for sufficient duration (power analysis to determine sample size), use hypothesis testing (t-test for continuous metrics, chi-square for categorical). Pitfalls: novelty effect (users behave differently with new things), leakage between variants, network effects.' },
  // ── Transformers ──────────────────────────────────────────────────────────────
  { topic: 'Transformers', level: 'mid', question: 'What is the role of positional encoding in transformers?', answer: 'Transformers have no inherent notion of token order (unlike RNNs). Positional encodings inject position information into token embeddings. Original paper (Vaswani 2017): sinusoidal encoding using sin/cos at different frequencies — allows the model to generalize to sequences longer than seen in training. Modern approaches: RoPE (Rotary Position Embedding, used in Llama) — encodes relative positions by rotating query/key vectors, ALiBi (Attention with Linear Biases, used in BLOOM) — adds a linear bias to attention scores based on token distance. RoPE is now dominant for its good extrapolation properties.' },
  { topic: 'Transformers', level: 'senior', question: 'Explain Flash Attention and why it matters for training large models.', answer: 'Flash Attention rewrites the attention operation to avoid materializing the full N×N attention matrix in GPU HBM (high-bandwidth memory). Instead, it computes attention in tiles that fit in SRAM (fast on-chip memory). Result: attention is now memory-bound → memory I/O bound rather than compute-bound. Reduces memory complexity from O(N²) to O(N) for the attention matrix. 2-4x faster than standard attention, enables longer context windows. Flash Attention 2 improved further with better parallelism. Flash Attention 3 (H100 optimized) is the current state of the art.' },
  { topic: 'Transformers', level: 'mid', question: 'What is Grouped Query Attention (GQA) and why is it used in modern LLMs?', answer: 'GQA is a compromise between Multi-Head Attention (MHA) and Multi-Query Attention (MQA). In MHA: each head has its own Q, K, V matrices. In MQA: all heads share a single K and V. In GQA: heads are grouped, and each group shares K and V — e.g., 32 query heads with 8 KV heads. Benefit: reduces KV-cache size during inference (critical bottleneck), allows faster inference with minimal quality loss. Used in Llama 2 70B, Llama 3, Mistral, Gemma. Typical configuration: 32Q heads, 8KV heads (4:1 ratio).' },
  { topic: 'Transformers', level: 'fresher', question: 'What is the purpose of the feedforward network in each transformer layer?', answer: 'The FFN in each transformer layer (also called the MLP) adds non-linearity and provides additional model capacity. Architecture: two linear projections with a non-linear activation in between: FFN(x) = Activation(W1·x + b1)·W2 + b2. The expansion dimension is typically 4× the model dimension (e.g., d_model=1024, d_ff=4096). GELU activation is standard in modern transformers. The FFN is believed to act as a "key-value memory" that stores factual knowledge. Some research shows the FFN stores more world knowledge than the attention layers.' },
  { topic: 'Transformers', level: 'senior', question: 'What is Mixture of Experts (MoE) and how does it enable efficient scaling?', answer: 'MoE replaces dense FFN layers with a set of N "expert" FFNs, where only K experts (typically 2 of 8) are activated per token (controlled by a gating network). Benefits: model has more total parameters but the same compute per token (sparse activation). Mixtral 8x7B has 46.7B total params but only activates 12.9B per forward pass. GPT-4 is widely believed to use MoE with ~8 experts. Challenges: expert load balancing (add auxiliary loss to prevent collapse), communication overhead in distributed settings, training instability. Switch Transformer showed MoE scales better than dense models with equal compute.' },
  // ── System Design ─────────────────────────────────────────────────────────────
  { topic: 'System Design', level: 'senior', question: 'Design a production RAG system for a 10M document corpus with <500ms P95 latency.', answer: 'Architecture: 1) Indexing pipeline: chunk docs → embed with batch GPU inference → upsert to vector DB (Pinecone/Qdrant) with metadata. 2) Serving: query → embed (fast, small model) → ANN search (HNSW index, ~10ms) → re-rank top-50 to top-5 → LLM generation. Latency breakdown: embedding ~20ms, retrieval ~10ms, reranking ~50ms, generation ~300ms = ~380ms. Optimizations: cache embeddings of frequent queries, pre-warm LLM, use streaming for generation, async retrieval + generation overlap. Scale: horizontal pod scaling for embedding service, read replicas for vector DB.' },
  { topic: 'System Design', level: 'senior', question: 'How would you design an LLM inference system to serve 10K concurrent users?', answer: 'Use vLLM or TGI for continuous batching and PagedAttention (maximizes GPU utilization). Architecture: load balancer → N inference pods (each with 1-4 GPUs). For high throughput: batch requests, use async generation. Autoscaling: scale on GPU utilization or queue depth. For cost: use spot instances with fallback, quantize to INT8/INT4. Routing: route short queries to smaller models, long/complex to larger. KV-cache sharing between requests with same system prompt (prefix caching). Cache frequent/deterministic responses at the API gateway layer.' },
  { topic: 'System Design', level: 'mid', question: 'How do you handle prompt injection attacks in LLM applications?', answer: 'Prompt injection: malicious user input that overrides system instructions (e.g., "Ignore previous instructions and..."). Defenses: input validation (detect injection patterns with a classifier), output validation (check responses against expected format/content), use separate system/user turn clearly delimited, minimal privilege (agent has only necessary tools), sandboxing (don\'t let agents execute arbitrary code), monitoring for anomalous outputs, human-in-the-loop for sensitive operations, use a fine-tuned safety classifier before/after generation.' },
  { topic: 'System Design', level: 'senior', question: 'How would you build a real-time AI news summarization system?', answer: 'Pipeline: 1) Data ingestion: scrape RSS feeds + news APIs every 5 min using async workers (Celery + Redis). 2) Deduplication: SimHash or MinHash to detect near-duplicate articles. 3) Topic clustering: embed articles, cluster similar ones (DBSCAN or agglomerative). 4) Summarization: prompt LLM to summarize cluster of related articles in 2-3 sentences. 5) Storage: summaries in Postgres with metadata, full articles in object storage. 6) Delivery: REST API + WebSocket for real-time updates to clients. Scale: rate limit news sources, use streaming summarization, cache summaries for popular topics.' },
  // ── Python for ML ──────────────────────────────────────────────────────────────
  { topic: 'Python', level: 'mid', question: 'What are Python generators and when are they useful in ML?', answer: 'Generators are lazy iterators that yield values one at a time instead of storing all in memory. Defined with yield keyword. Use cases in ML: 1) Data pipelines — process large datasets in batches without loading all into memory (yield batch), 2) Infinite streams of data augmentation, 3) Custom DataLoaders. Example: `def data_loader(paths): for p in paths: yield preprocess(load(p))`. Benefits: constant memory usage regardless of dataset size, can interleave I/O with computation. Works well with Python\'s for-loop and next(). generator expressions: `(x**2 for x in range(1000000))` vs list comprehension.' },
  { topic: 'Python', level: 'mid', question: 'How does Python\'s GIL affect multi-threaded ML workloads?', answer: 'The Global Interpreter Lock (GIL) prevents multiple Python threads from executing Python bytecode simultaneously. Impact on ML: CPU-bound work (numpy, tensor ops) bypasses the GIL because they release it during C extension calls, so threads work fine there. Pure Python CPU work (data preprocessing loops) is bottlenecked by the GIL. Solutions: 1) multiprocessing — uses separate processes with separate GILs, used by PyTorch DataLoader (num_workers>0), 2) asyncio — concurrent I/O without threads, 3) Cython/C extensions. PyTorch operations release the GIL, so Python threads work for GPU-bound ML training.' },
  { topic: 'Python', level: 'mid', question: 'Explain Python\'s context managers and how they\'re used in ML training.', answer: 'Context managers define setup/teardown logic using __enter__ and __exit__ or @contextmanager decorator. In ML: 1) `torch.no_grad()` — disables gradient computation during inference (saves memory, speeds up), 2) `torch.autocast("cuda")` — automatic mixed precision (uses float16 where safe, float32 where needed), 3) `with open(file) as f:` — safe file handling, 4) model.train() / model.eval() context managers. Implementation: class with __enter__ returning resource and __exit__ handling cleanup. @contextmanager with yield gives simpler generator-based implementation.' },
  { topic: 'Python', level: 'senior', question: 'How do you profile and optimize Python code for ML training pipelines?', answer: 'Profiling tools: cProfile/profile (function-level), line_profiler (@profile decorator, line-level), memory_profiler (memory usage), PyTorch Profiler (GPU + CPU timeline). Common bottlenecks: data loading (fix: increase num_workers, pin_memory=True, prefetch), inefficient preprocessing (vectorize with numpy/pandas instead of loops), Python loops in forward pass (use tensor operations), unnecessary CPU-GPU transfers. Tools: torch.utils.bottleneck, Tensorboard Profiler, NVIDIA Nsight. Rule of thumb: profile before optimizing, focus on the top bottleneck first.' },
  { topic: 'Python', level: 'mid', question: 'What is asyncio and how can it speed up LLM API calls?', answer: 'asyncio enables concurrent execution of I/O-bound tasks in a single thread using an event loop and async/await syntax. For LLM APIs: instead of sequential calls (each waits for response), run many API calls concurrently. Example with async OpenAI: `async def main(): tasks = [acall(prompt) for prompt in prompts]; results = await asyncio.gather(*tasks)`. Speedup: if each call takes 2 seconds and you have 100 calls, sequential takes 200s, concurrent takes ~2s (limited by rate limits). Use `asyncio.Semaphore` to respect rate limits. All major AI SDKs (openai, anthropic) have async clients.' },
  // ── Vector DB ──────────────────────────────────────────────────────────────────
  { topic: 'Vector DB', level: 'mid', question: 'What is HNSW and why is it the dominant algorithm for vector search?', answer: 'HNSW (Hierarchical Navigable Small World) is an approximate nearest neighbor algorithm using a multi-layer graph. Construction: each vector is added to a hierarchical graph where upper layers are sparse (long-range connections) and lower layers are dense (local connections). Search: start at the top layer, greedily navigate to closest node, descend to lower layers. Properties: O(log N) search time, high recall (>99% with ef parameter), supports incremental updates. Used by: Qdrant, Weaviate, Pinecone, pgvector. Trade-offs: high memory usage (graph structure), slower build time than IVF, but faster and more accurate search.' },
  { topic: 'Vector DB', level: 'senior', question: 'What is the difference between semantic search and keyword search, and when do you combine them?', answer: 'Keyword search (BM25): exact term matching with TF-IDF weighting, fast, no embedding needed, great for precise queries. Semantic search: vector similarity, captures meaning/synonyms, no exact term matching needed. Hybrid search: combine both scores (typically: score = (1-α)×BM25 + α×cosine_sim, or use RRF — Reciprocal Rank Fusion to merge ranked lists). Use hybrid when: queries can be either precise ("GET /api/v2/users error 404") or semantic ("how do I handle authentication errors"), or when neither alone is sufficient. Elasticsearch supports hybrid natively, as does Weaviate, Qdrant, and Pinecone.' },
  { topic: 'Vector DB', level: 'mid', question: 'What are the trade-offs between different embedding models for RAG?', answer: 'Small fast models (all-MiniLM-L6-v2, 22M params, 384-dim): ~10ms inference, good for general purpose, free. Medium models (BGE-M3, E5-large): better quality, multi-lingual support, 300-500ms. Large/API models (text-embedding-3-large from OpenAI, 3072-dim): highest quality, ~50ms API latency, costs money. Key factors: embedding dimension (higher = better quality but more memory), max sequence length (some truncate at 512 tokens), multilingual support, domain-specific performance. For RAG: BGE-M3 or E5-large are popular open-source choices. Always evaluate on your specific domain.' },
  // ── NLP ────────────────────────────────────────────────────────────────────────
  { topic: 'NLP', level: 'mid', question: 'What is Byte Pair Encoding (BPE) and why is it used for tokenization?', answer: 'BPE starts with a character vocabulary and iteratively merges the most frequent adjacent byte/character pairs. Result: a vocabulary of subwords that efficiently represents any text. Benefits: handles OOV (out-of-vocabulary) words by splitting them into known subwords, balances between character-level (handles everything) and word-level (inefficient vocabulary), good compression ratio. GPT models use BPE-based tokenizers (tiktoken). Example: "tokenization" → ["token", "iz", "ation"]. Trade-offs: language-dependent (English-optimized tokenizers tokenize other languages less efficiently), can create semantically odd splits.' },
  { topic: 'NLP', level: 'senior', question: 'What is the difference between BERT and sentence transformers for semantic search?', answer: 'BERT (and its variants): outputs token-level embeddings, designed for classification/NER/QA. To get sentence embedding: average pool or use [CLS] token — but these were NOT trained for semantic similarity, so they perform poorly for retrieval. Sentence Transformers (SBERT): fine-tuned specifically for semantic textual similarity using siamese network architecture on NLI/STS datasets. Optimized for: fast similarity computation, sentence-level tasks. BEIR benchmark shows SBERT models (GTE, E5, BGE) significantly outperform BERT on retrieval. For RAG: always use sentence transformers, not raw BERT.' },
  // ── Computer Vision ─────────────────────────────────────────────────────────────
  { topic: 'Computer Vision', level: 'mid', question: 'What is the Vision Transformer (ViT) and how does it apply attention to images?', answer: 'ViT splits an image into fixed-size patches (e.g., 16×16 pixels), flattens and linearly embeds them, then processes them as a sequence of tokens with standard transformer self-attention. A special [CLS] token aggregates image information for classification. Trained on large datasets (ImageNet-21K, JFT-300M), ViT matches or exceeds CNN performance. Advantages: captures long-range dependencies naturally (attention between distant patches), scalable with data/compute. CLIP (OpenAI) uses ViT as the image encoder. DINOv2 (Meta) is a powerful self-supervised ViT.' },
  { topic: 'Computer Vision', level: 'senior', question: 'What is the SAM (Segment Anything Model) and what makes it special?', answer: 'SAM (Meta 2023) is a promptable image segmentation model trained on 1.1B masks (SA-1B dataset). Key innovation: zero-shot generalization — segment any object given a point, box, or text prompt without task-specific training. Architecture: Image Encoder (ViT-H), Prompt Encoder (points, boxes, masks), Mask Decoder (outputs masks + confidence). Can generate mask for any region when prompted. Applications: data annotation automation, medical imaging, robotics. SAM 2 (2024) extends to video with memory attention for tracking objects across frames.' },
  // ── Additional important questions ─────────────────────────────────────────────
  { topic: 'LLM', level: 'mid', question: 'What is context window and how do long-context models work?', answer: 'Context window is the maximum number of tokens a model can process at once (input + output). GPT-4 Turbo: 128k tokens (~96k words). Techniques for long context: Sliding window attention (Mistral, Longformer) — each token attends only to nearby tokens + a few global ones. RoPE with extended base frequency (Llama 3.1 uses rope_theta=500000 for 128k context). ALiBi linear biases. Challenges: quadratic attention complexity (Flash Attention mitigates), "lost in the middle" problem, evaluation on long contexts is hard. In practice: RAG often beats long context for retrieval tasks because it\'s cheaper and more precise.' },
  { topic: 'RAG', level: 'mid', question: 'What is re-ranking in RAG and which models are used for it?', answer: 'Re-ranking adds a second-stage precision improvement: the first stage retrieves top-K candidates fast (HNSW + cosine similarity), the second stage uses a more expensive cross-encoder to score each (query, document) pair more accurately. Cross-encoders process query and document together (full attention) vs bi-encoders which encode them separately. Models: Cohere Rerank, BGE Reranker, cross-encoder/ms-marco-MiniLM-L-6-v2. Typical pipeline: retrieve top-50 with vector search → rerank to top-5 → pass to LLM. Re-ranking adds 50-150ms but significantly improves answer quality for complex queries.' },
  { topic: 'Agents', level: 'mid', question: 'What is LangGraph and how does it differ from LangChain for building agents?', answer: 'LangGraph (built on top of LangChain) models agent workflows as a directed graph (state machine) where nodes are functions/LLM calls and edges are transitions. This makes complex multi-step agent logic explicit and debuggable vs LangChain\'s sequential chain abstraction. Key features: conditional routing (edges based on state), cycles supported (for retry logic), streaming state updates, human-in-the-loop checkpointing. Best for: agents that need branching logic, multi-agent systems (supervisor → specialist pattern), long-running workflows that need checkpointing. LangChain is simpler for linear pipelines; LangGraph for complex conditional flows.' },
  { topic: 'Fine-Tuning', level: 'senior', question: 'What is GRPO (Group Relative Policy Optimization) and how does it enable LLMs to reason?', answer: 'GRPO (DeepSeek-R1) is a variant of PPO that eliminates the need for a separate value function model. For a given prompt, generate G responses, compute rewards for each, normalize relative to the group mean. This group comparison acts as a baseline for variance reduction. Combined with a "thinking" format (model generates reasoning before answer), GRPO trains models to reason step-by-step on math and coding problems. DeepSeek-R1 matches o1-preview performance using GRPO. Advantage over PPO: no value model = simpler, less memory, more stable training. Advantage over DPO: works with verifiable rewards (math correctness), not just human preferences.' },
  { topic: 'MLOps', level: 'mid', question: 'What is the difference between batch inference and online inference?', answer: 'Batch inference: process a large dataset offline, results stored for later use. Pros: maximize throughput, use large batch sizes, cost-effective, GPU utilization can hit 90%+. Cons: latency is hours/days, not real-time. Use for: weekly recommendation updates, offline evaluation, data pipelines. Online inference: real-time, low-latency (<100ms) response to individual requests. Pros: immediate results. Cons: lower GPU utilization (must size for peak load), higher cost per query, need to handle variable load. Use for: chatbots, search, content moderation. Streaming inference: online inference with token streaming for LLMs improves perceived latency.' },
  { topic: 'Transformers', level: 'mid', question: 'What is KV-cache and why is it critical for LLM inference performance?', answer: 'During autoregressive generation, each new token attends to all previous tokens. Without caching: recompute K,V for all previous tokens at every step — O(n²) total work. KV-cache: store the K and V matrices computed for previous tokens, reuse them for each new step — O(n) total work. Memory cost: proportional to batch_size × sequence_length × n_layers × d_head. At scale: a 70B model with 10K context and batch size 64 needs ~140GB for KV-cache alone. Optimizations: PagedAttention (vLLM), KV-cache quantization (INT8/INT4), prefix caching (reuse prompts), sliding window attention.' },
  { topic: 'Vector DB', level: 'senior', question: 'When would you use Pinecone vs Qdrant vs pgvector for a production RAG system?', answer: 'Pinecone: fully managed, zero ops overhead, auto-scaling, good for teams that want to focus on product not infrastructure. Expensive at scale, limited customization, vendor lock-in. Qdrant: open-source, self-hostable or managed, rich filtering (payload filters), good performance, active development. Good balance of control and features for medium-large scale. pgvector: extends PostgreSQL with vector operations, ideal when you already use Postgres and want simplicity, or need ACID transactions with vector search. Limitations: HNSW performance slightly lower than dedicated DBs, scaling requires Postgres expertise. Rule: Pinecone for speed, Qdrant for cost+control, pgvector for simplicity.' },
  { topic: 'Python', level: 'fresher', question: 'What is the difference between list comprehension and map/filter in Python for data processing?', answer: 'List comprehension `[f(x) for x in lst if condition]` is Pythonic, readable, generally faster than explicit loops. map() applies a function to every element, returns a lazy iterator — useful for large datasets or chaining. filter() selects elements matching a predicate, also lazy. For ML: list comprehensions are preferred for readability. `[x**2 for x in data]` vs `list(map(lambda x: x**2, data))`. Performance: list comprehension is typically fastest for simple operations, map() can be faster with built-in functions (map(str.upper, words)). For large datasets: prefer generators `(f(x) for x in lst)` to avoid loading everything in memory.' },
  // ── LLM (more) ──────────────────────────────────────────────────────────────
  { topic: 'LLM', level: 'senior', question: 'Why does temperature=0 sometimes still produce non-deterministic output?', answer: 'On GPUs, floating-point addition is non-associative — different thread scheduling can change the order of partial sums by a few ULPs. That can flip the argmax in rare near-ties at the last decoding step. To get truly reproducible output you also need fixed batch composition (other concurrent requests change kernel timing), fixed model weights (no quantisation re-loads), and ideally CPU inference. In production this is acceptable noise; only matters for evaluations.' },
  { topic: 'LLM', level: 'mid', question: 'What is the difference between top-k and top-p sampling?', answer: 'Top-k keeps the highest-k tokens by probability and samples from those (k is a fixed integer). Top-p (nucleus) keeps the smallest set of tokens whose probabilities sum to >= p (p in [0,1]) — the set grows when the model is uncertain and shrinks when confident, so it adapts to entropy. Production setups usually combine both: top-k=50 as a hard ceiling, top-p=0.95 to trim the long tail. Pure greedy (k=1 or temperature=0) gives the highest probability token at every step but produces repetitive, often degraded text on creative tasks.' },
  { topic: 'LLM', level: 'mid', question: 'Why is there a [BOS] token in most decoder-only models?', answer: 'Beginning-of-sequence token signals the start of generation and gives the model a fixed conditioning state. Decoder-only models were trained with [BOS] prepended to every sequence — omitting it at inference time shifts the input distribution and degrades quality. Some tokenizers (Llama, GPT) add it automatically; with raw tokenizers you must add it yourself. The [BOS] embedding is also what the model attends to before any user tokens exist, providing a stable "I am starting" representation.' },
  { topic: 'LLM', level: 'senior', question: 'What is the role of rope_theta in modern long-context models?', answer: 'rope_theta is the base frequency of Rotary Position Embeddings (RoPE). Higher theta = slower rotation per position = embeddings remain "different enough" at large positions. Llama 2 used 10,000 (good up to 4K). Llama 3.1 uses 500,000 to extend to 128K. You can scale theta after training (NTK-aware scaling, dynamic NTK) or interpolate positions (PI) to stretch context further at inference. Trade-off: higher theta gives longer context but slightly hurts performance in the original short-context range.' },
  { topic: 'LLM', level: 'mid', question: 'Explain prompt caching and when to use it.', answer: 'Prompt caching stores the model\'s internal state (KV-cache) for a stable prompt prefix so subsequent requests with the same prefix skip recomputation. Anthropic and OpenAI both expose this via API headers. Best uses: long system prompts shared across users, RAG with a stable context document, agents replaying tool definitions. Wins: 50-90% latency reduction on the cached prefix, ~10% of normal token cost. Caveats: minimum prefix length, TTL (~5 min), only the EXACT prefix is cached — even one different token invalidates.' },
  // ── RAG (more) ──────────────────────────────────────────────────────────────
  { topic: 'RAG', level: 'mid', question: 'When should you use a graph database instead of a vector DB for retrieval?', answer: 'Use graph DBs (Neo4j, Memgraph) when relationships between entities matter as much as semantic similarity — e.g., "find regulations that cite this section that affect product X". GraphRAG (Microsoft) extracts entities and relationships from documents during indexing and lets the LLM traverse the graph. Use vector DBs when queries are mostly semantic ("anything similar to this"). Hybrid: vector for retrieval, graph for filtering or expansion. Graph adds engineering complexity and slower writes, so only justified when entity relationships are the actual signal users need.' },
  { topic: 'RAG', level: 'senior', question: 'What is contextual retrieval and how does Anthropic\'s approach work?', answer: 'Naive chunking drops the broader document context. Contextual retrieval (Anthropic, 2024) prepends a short LLM-generated summary of where each chunk fits in its parent document before indexing. Example: instead of indexing "Revenue grew 30%", you index "Q3 2024 earnings discussion: Revenue grew 30% YoY driven by enterprise". Benefits: 35-50% reduction in retrieval failures on benchmarks. Cost: one LLM call per chunk at indexing time (prompt caching makes this ~$1/M chunks). Combine with reranking for another 30%+ improvement.' },
  { topic: 'RAG', level: 'mid', question: 'What is the difference between dense and sparse retrieval?', answer: 'Dense retrieval uses learned embeddings (BERT-style models) and measures similarity in continuous vector space — captures semantics and synonyms, can match "car" with "automobile". Sparse retrieval (BM25, SPLADE) uses term weights in a high-dimensional sparse vector where most dimensions are 0 — captures exact keyword overlap with TF-IDF weighting. Dense excels at conceptual queries; sparse at proper nouns, codes, exact phrases. Hybrid retrieval (combining both with RRF or weighted sum) consistently outperforms either alone — typical formula: score = 0.6 × dense + 0.4 × bm25.' },
  // ── Agents (more) ───────────────────────────────────────────────────────────
  { topic: 'Agents', level: 'mid', question: 'What is MCP (Model Context Protocol) and why does it matter?', answer: 'MCP (Anthropic, 2024) is an open protocol that standardizes how LLM apps connect to external tools and data sources. Before MCP, every integration (Slack, GitHub, your DB) was bespoke per LLM client. With MCP: a single MCP server exposes tools/resources, and any MCP-aware client (Claude Desktop, IDEs) can use them. Architecture: client ⇄ stdio/HTTP ⇄ server. Servers can expose tools (functions), resources (data), and prompts (templates). It\'s essentially "USB-C for AI tools" — write once, plug into any AI app.' },
  { topic: 'Agents', level: 'senior', question: 'How would you debug an agent that keeps getting stuck in a loop?', answer: 'Step 1: log every step (Thought / Action / Observation) — most loops are invisible without telemetry. Step 2: identify the loop pattern — same tool with same args (state not updating), or two tools alternating (oscillation). Step 3: common fixes: (a) deduplicate observations the agent has already seen, (b) add an explicit "what did you just try" to the system prompt, (c) tighten the tool descriptions so the agent picks the right one first, (d) add a "give up after N tries on the same approach" rule. Step 4: hard limit on max_iterations + max_total_tokens as a safety net. LangSmith / Langfuse / Phoenix make this dramatically easier than print-debugging.' },
  // ── Fine-Tuning (more) ───────────────────────────────────────────────────────
  { topic: 'Fine-Tuning', level: 'senior', question: 'What is GRPO and how did DeepSeek use it for reasoning?', answer: 'Group Relative Policy Optimization is a PPO variant that drops the value (critic) network. For each prompt, the policy generates G responses, you compute the reward of each, and use the GROUP mean as a baseline (instead of a learned value function). Advantages over PPO: ~50% less GPU memory, more stable training, no value-function bias. DeepSeek-R1 paired GRPO with verifiable rewards (math correctness, code passes tests) so no reward model is needed. The training learns to "think before answering" without any human-labeled reasoning traces — the format emerges from rewarding correct final answers.' },
  { topic: 'Fine-Tuning', level: 'mid', question: 'When is fine-tuning the wrong choice, and what should you do instead?', answer: 'Fine-tuning is wrong when: (1) you need fresh / changing knowledge — use RAG instead, (2) you have <500 examples — few-shot prompting will outperform, (3) you need format compliance only — JSON mode or structured outputs work better, (4) you can\'t collect a clean eval set — you\'ll fly blind. Fine-tuning IS right when: enforcing tone/style at scale, distilling a large model into a small one, adapting to a domain language (legal, medical) where prompting plateaus, reducing inference cost by enabling a smaller base model. Rule of thumb: try RAG + prompting first, fine-tune only when you\'ve hit a quality ceiling those can\'t fix.' },
  // ── MLOps (more) ─────────────────────────────────────────────────────────────
  { topic: 'MLOps', level: 'senior', question: 'How do you cost-optimize an LLM service handling 10M requests/day?', answer: 'Top levers in order of impact: (1) Cache aggressively — prefix caching for shared system prompts (50-90% off cached tokens), exact-match response caching for FAQs (1000x cheaper than re-running). (2) Route by complexity — simple queries to Haiku/3.5-mini, complex to Opus/4. (3) Quantize self-hosted models to INT4 (AWQ/GPTQ) → 4× throughput with <1% quality loss. (4) Continuous batching (vLLM / TGI) — 10-20× throughput vs naive. (5) Streaming responses to free GPU memory faster. (6) Right-size context — trim history aggressively, summarize old turns. (7) Monitor cost per request as a first-class metric; alert on anomalies.' },
  { topic: 'MLOps', level: 'mid', question: 'What is shadow deployment and when do you use it?', answer: 'Shadow deployment runs a new model in parallel with the production model: every request is sent to BOTH, but only the production model\'s response is returned to the user. The new model\'s outputs are logged for offline analysis. Use it to: validate a new model\'s quality on real production traffic without risk, compare latency / cost at realistic load, build a labeled dataset (production response = ground truth proxy). Once you trust the shadow model, ramp via canary (5% → 25% → 100%). Shadow doubles your inference cost during the test, but it\'s the safest way to validate a model swap.' },
  // ── Transformers (more) ─────────────────────────────────────────────────────
  { topic: 'Transformers', level: 'senior', question: 'What is KV-cache quantization and how much memory does it save?', answer: 'KV-cache (the stored K and V projections for already-generated tokens) dominates inference memory at long context: ~140 GB for Llama 70B at 8K context, batch 1. Quantizing the cache from FP16 to INT8 cuts memory in half with <1% perplexity hit; INT4 cuts it by 4× with ~2-3% perplexity hit. Tradeoff: smaller cache = larger batch size = much higher throughput, but quality drops slightly. Production systems often use FP8 / INT8 caches by default. Implementation in vLLM, TensorRT-LLM, llama.cpp. Critical for serving long-context models economically.' },
  { topic: 'Transformers', level: 'mid', question: 'Why are residual connections critical in transformers?', answer: 'Residual connections (output = x + sublayer(x)) enable training of very deep networks by giving gradients a direct path back through the network — without them, gradients vanish through dozens of layers. In transformers specifically: they let each layer learn an INCREMENT to the previous representation instead of a full re-encoding, which is empirically much easier to optimize. Pre-norm (LayerNorm before sublayer, then add residual) is now standard because it stabilizes training of 100+ layer models — post-norm (the original Vaswani 2017 design) becomes unstable at scale.' },
  // ── System Design (more) ─────────────────────────────────────────────────────
  { topic: 'System Design', level: 'senior', question: 'Design a multi-tenant LLM inference service with per-tenant quotas and isolation.', answer: 'Architecture: API gateway (Kong / AWS API GW) authenticates tenants and enforces per-tenant rate limits (token bucket in Redis). Behind it, a request router maps tenants to model pools — small/cheap models share a pool, premium tenants get dedicated GPU pods. Each pool runs vLLM with continuous batching. Quotas: tokens/min and concurrent requests, tracked in Redis with sliding-window counters. Fairness: priority queue per pool so a noisy tenant can\'t starve others (vLLM has a priority param). Isolation: separate Kubernetes namespaces per tier, NetworkPolicies prevent cross-tenant traffic, separate logs per tenant for audit. Cost: route by tenant tier — free tier shares a Llama 3.1 8B pool with low priority; enterprise gets a dedicated 70B pod.' },
  { topic: 'System Design', level: 'mid', question: 'How do you design an evaluation pipeline for a RAG system?', answer: 'Build it in 4 layers. (1) Unit eval: synthetic Q&A pairs covering core capabilities — run on every PR. (2) Component eval: retrieval (NDCG@10, recall@5), generation (faithfulness, answer relevancy via RAGAS or LLM-as-judge). (3) End-to-end eval: real user queries replayed against golden answers. (4) Production: thumbs up/down on responses, sampled human review. Tooling: store every prompt/response pair with metadata in a feedback table; nightly batch job runs LLM-as-judge on a sample. Trigger retraining/reindexing alerts when faithfulness drops below threshold. Critical: keep the eval set frozen — if it changes, regressions become invisible.' },
  // ── Python (more) ───────────────────────────────────────────────────────────
  { topic: 'Python', level: 'mid', question: 'What is the difference between asyncio.gather and asyncio.as_completed?', answer: 'asyncio.gather(*tasks) waits for ALL tasks and returns results in the SAME ORDER they were passed in — useful when you need all results before continuing. asyncio.as_completed(tasks) yields tasks as they complete (any order), letting you process the fastest results first — useful for race patterns or progress bars. Performance: both run tasks concurrently; the difference is in the result API. gather has return_exceptions=True option to collect failures instead of cancelling everything. For LLM batch calls: gather is usually right; switch to as_completed when you want to stream partial results to the user as each model returns.' },
  { topic: 'Python', level: 'senior', question: 'How does Python\'s ContextVar differ from threading.local, and when do you use it?', answer: 'threading.local stores values per-OS-thread. ContextVar stores values per-CONTEXT — and asyncio creates a new context per task. With asyncio, threading.local breaks (all tasks share the same OS thread) but ContextVar works correctly. Use ContextVar for: request-scoped data (request ID, user ID) in FastAPI / aiohttp servers, OpenTelemetry trace propagation, tenant context in multi-tenant async services. FastAPI uses ContextVar internally for request state. Rule: if your service uses async/await anywhere, replace threading.local with contextvars.' },
  // ── Vector DB (more) ────────────────────────────────────────────────────────
  { topic: 'Vector DB', level: 'mid', question: 'What is binary quantization and when is it worth using?', answer: 'Binary quantization compresses each float embedding into a single bit per dimension (sign of the value). A 1024-dim float32 embedding (4096 bytes) becomes 1024 bits = 128 bytes — a 32× reduction. Distance metric becomes Hamming distance, computable in nanoseconds with bitwise ops. Quality loss: 1-3 percentage points of recall, recoverable by reranking the top-100 binary candidates with full-precision vectors. Worth it when: index size exceeds RAM (binary fits where float32 doesn\'t), query throughput matters more than last-percent quality. Qdrant, Milvus, Weaviate all support it. Combined with reranking, often matches full-precision retrieval at 10× the throughput.' },
  { topic: 'Vector DB', level: 'senior', question: 'What is matryoshka representation learning and why does it matter?', answer: 'Matryoshka embeddings (Aditya Kusupati et al., 2022) train a model so that PREFIXES of the embedding (first 64, 128, 256 dims) are themselves usable embeddings of decreasing quality. One model serves many resolution levels — same vector, multiple uses. OpenAI\'s text-embedding-3 series uses this. Why it matters: at retrieval time, do a coarse search with truncated 256-dim vectors (fast, less RAM) to get top-1000 candidates, then rerank with full-resolution 3072-dim vectors. Storage saved AND latency reduced. Without matryoshka, training separate models per dimension multiplies cost; matryoshka does it in one training run.' },
  // ── NLP (more) ──────────────────────────────────────────────────────────────
  { topic: 'NLP', level: 'mid', question: 'Why do tokenizers tokenize different languages with very different efficiency?', answer: 'BPE / Unigram tokenizers learn merges from frequency in the training corpus. If English is 90% of the corpus, "the" is one token but a common Hindi word might be 5-8 tokens because its subwords are rarer in the data. Consequences: non-English inference is 2-4× more expensive per request, context window holds less information, latency is worse. Solutions: train a multilingual tokenizer with balanced corpus (Llama 3 uses 128K vocab partly for this), use language-specific models for non-English, or strip/translate inputs at the boundary. Bottom line: token count is not symmetric across languages.' },
  // ── Behavioral ──────────────────────────────────────────────────────────────
  { topic: 'Behavioral', level: 'mid', question: 'Tell me about a time you disagreed with a teammate on a technical decision.', answer: 'Frame using SBI (Situation / Behavior / Impact) or STAR. Strong answer pattern: (1) Specific context — model choice, architecture decision, eval approach. (2) Where you disagreed and WHY in technical terms — surface the trade-off (latency vs accuracy, build vs buy, complexity vs flexibility). (3) How you resolved it — running a small experiment, writing a doc, getting a third opinion, deferring with explicit risk. (4) Result and what you learned. Red flags interviewers watch for: dismissing the other person, "I was right and they were wrong," not acknowledging your bias. Show you can hold a position AND change your mind on evidence.' },
  { topic: 'Behavioral', level: 'senior', question: 'How do you decide what to deprioritize when everything feels urgent?', answer: 'Strong answer touches all of: (1) Explicit framework — RICE, weighted scoring, cost of delay. (2) Talk to stakeholders to separate "actually urgent" (a deadline, a regression) from "feels urgent" (loudest voice). (3) Make trade-offs visible — write the deprioritization decision down and share it, so it can be challenged or corrected. (4) Accept that this is a leadership signal: senior engineers say no, junior engineers ship everything and burn out. Concrete example: paused a model upgrade because we lacked an eval set; spent two weeks building one first. Slower this quarter, faster forever after.' },
  // ── Statistics / SQL & Data ─────────────────────────────────────────────────
  { topic: 'Statistics', level: 'mid', question: 'When is a p-value less than 0.05 still not enough to ship a change?', answer: 'P < 0.05 means "low probability of seeing this effect if the null is true" — it does NOT mean the effect is large, durable, or worth shipping. Reasons to NOT ship despite significance: (1) Effect size is tiny — statistical significance with no business value. (2) Multiple comparisons inflated false-positive rate — apply Bonferroni or FDR correction. (3) Novelty effect — users react to "new" but interest fades; rerun after 2 weeks. (4) Confounders — A/B was during a holiday, on a specific segment, etc. (5) Pre-registration violated — you tested 10 metrics and one was significant. (6) Cost — does the engineering cost to maintain the change justify the lift?' },
  { topic: 'SQL & Data', level: 'mid', question: 'Why is window function performance often better than self-join for ranking?', answer: 'Self-join for "rank within group" requires joining the table against itself with a correlated filter (e.g., count rows where score >= my_score) — that\'s O(N²) work. Window functions (ROW_NUMBER, RANK, DENSE_RANK with PARTITION BY) let the database SORT each partition once and assign ranks in a single pass — O(N log N) total. Modern engines (Postgres, Snowflake, BigQuery) implement these with hash partitioning + sort and can even parallelize per partition. Rule: any time you write "for each row, count rows that..." you probably want a window function instead.' },
]

export async function POST(req: Request) {
  const { password } = await req.json().catch(() => ({}))
  if (password !== process.env.ADMIN_PASSWORD) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const supabase = getAdminSupabase()

  // Idempotent: skip rows whose question text already exists.
  // Without this, re-running the seeder would duplicate every question.
  const { data: existing } = await supabase
    .from('interview_questions')
    .select('question')
  const existingSet = new Set((existing ?? []).map(r => (r.question as string).trim()))
  const toInsert = QUESTIONS
    .filter(q => !existingSet.has(q.question.trim()))
    .map(q => ({ question: q.question, answer: q.answer, topic: q.topic, level: q.level }))

  if (toInsert.length === 0) {
    return NextResponse.json({ seeded: 0, skipped: QUESTIONS.length, message: 'All questions already seeded.' })
  }

  const { error, data } = await supabase
    .from('interview_questions')
    .insert(toInsert)
    .select('id')

  if (error && !error.message.includes('duplicate')) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
  return NextResponse.json({
    seeded:  data?.length ?? toInsert.length,
    skipped: QUESTIONS.length - toInsert.length,
  })
}
