import { NextResponse } from 'next/server'
import { getAdminSupabase } from '@/lib/admin'

export const runtime = 'nodejs'

const QUESTIONS = [
  // ── LLM ─────────────────────────────────────────────────────────────────────
  { topic: 'LLM', level: 'mid', question: 'What is the difference between GPT-3 and GPT-4 architecturally?', answer: 'GPT-4 is a multimodal model that can accept image and text inputs, uses a larger context window (up to 128k tokens with Turbo), and is believed to use a Mixture of Experts (MoE) architecture with ~8 experts. GPT-3 is a dense transformer with 175B parameters, text-only, and 4k context window. GPT-4 has significantly improved reasoning, reduced hallucinations, and passes professional exams at high percentiles.' },
  { topic: 'LLM', level: 'fresher', question: 'What is a token in the context of LLMs?', answer: 'A token is the basic unit of text that LLMs process. It can be a word, part of a word, or punctuation depending on the tokenizer. For example, "ChatGPT" might be split into ["Chat", "G", "PT"]. The most common tokenizer is BPE (Byte Pair Encoding). GPT-4 uses approximately 4 characters per token on average. Tokens determine the model\'s context window limit and API pricing.' },
  { topic: 'LLM', level: 'mid', question: 'Explain the concept of scaling laws in LLMs.', answer: 'Scaling laws (Kaplan et al., Chinchilla) describe predictable relationships between model size, training data, compute budget, and model performance. Key finding: performance improves as a power law with scale. Chinchilla paper showed that for a given compute budget, you should balance model size and training tokens approximately equally (e.g., 70B model trained on 1.4T tokens performs better than 280B model on 700B tokens). This guides decisions on training runs.' },
  { topic: 'LLM', level: 'senior', question: 'What is Constitutional AI and how does Anthropic use it?', answer: 'Constitutional AI (CAI) is a training method where the model is guided by a set of principles (a "constitution") rather than just human feedback. The process: 1) Generate responses, 2) Have the AI critique its own responses against the constitution, 3) Revise based on critiques, 4) Train on the revised responses. This reduces reliance on human labelers for identifying harmful content. Anthropic uses CAI to train Claude, making it helpful, harmless, and honest without needing extensive human feedback on every harmful output.' },
  { topic: 'LLM', level: 'mid', question: 'What is the difference between zero-shot, one-shot, and few-shot prompting?', answer: 'Zero-shot: ask the model to perform a task with no examples — relies entirely on training knowledge. One-shot: provide one example in the prompt before the task. Few-shot: provide 2-5+ examples. Few-shot prompting was a key finding in the GPT-3 paper showing LLMs can learn from context examples. The model is not fine-tuned; it adapts based on the pattern shown in the prompt. Best practice: use 3-5 diverse, high-quality examples in the same format as the desired output.' },
  { topic: 'LLM', level: 'senior', question: 'How does RLHF work and what are its limitations?', answer: 'RLHF (Reinforcement Learning from Human Feedback): 1) Supervised fine-tuning on demonstrations, 2) Train a reward model on human preference comparisons, 3) Use PPO to optimize the policy (LLM) to maximize the reward model\'s score. Limitations: reward hacking (model finds ways to maximize reward that don\'t reflect actual quality), reward model can be fooled, human annotators have biases and inconsistencies, expensive and slow to scale, the KL penalty to prevent the model from drifting too far adds complexity.' },
  { topic: 'LLM', level: 'mid', question: 'What is chain-of-thought prompting and when should you use it?', answer: 'Chain-of-thought (CoT) prompting encourages the model to show its reasoning steps before giving a final answer. Example: "Q: Roger has 5 tennis balls... Let\'s think step by step: Roger starts with 5 balls, buys 2 cans of 3 balls each, so 2×3=6 new balls, 5+6=11 total. A: 11." CoT significantly improves performance on math, reasoning, and logical tasks. Use when: the task requires multi-step reasoning, arithmetic, or logical deduction. Zero-shot CoT: just append "Let\'s think step by step" to your prompt.' },
  { topic: 'LLM', level: 'senior', question: 'What is speculative decoding and how does it speed up inference?', answer: 'Speculative decoding uses a small "draft" model to generate candidate tokens quickly, then uses the larger target model to verify multiple tokens in parallel. Since the target model can process multiple tokens in one forward pass (verification is faster than generation), you get significant speedups when the draft model\'s predictions are often correct. Deepmind showed 2-3x speedup with minimal quality loss. The technique is now used in production at Anthropic and other labs.' },
  { topic: 'LLM', level: 'mid', question: 'What are the key differences between encoder-only, decoder-only, and encoder-decoder architectures?', answer: 'Encoder-only (BERT): bidirectional attention, sees all tokens at once, good for classification, NER, QA. Cannot generate text autoregressively. Decoder-only (GPT): causal/unidirectional attention, generates tokens left-to-right, best for generation tasks. Encoder-decoder (T5, BART): encoder processes input with bidirectional attention, decoder generates output with cross-attention to encoder. Best for seq2seq tasks like translation, summarization. Most modern LLMs are decoder-only as generation is the dominant use case.' },
  { topic: 'LLM', level: 'fresher', question: 'What is temperature in LLM sampling and how does it affect output?', answer: 'Temperature controls randomness in sampling. Low temperature (0.1-0.3): more deterministic, picks highest probability tokens, outputs are focused and repetitive. High temperature (0.8-1.2): more random, samples lower probability tokens, more creative and diverse. Temperature=0: greedy decoding (always pick the highest probability token). Temperature scales the logits before softmax: logits/temperature. Use low temperature for factual tasks, high temperature for creative writing. Temperature=1.0 = unchanged distribution.' },
  // ── RAG ─────────────────────────────────────────────────────────────────────
  { topic: 'RAG', level: 'mid', question: 'What is Retrieval-Augmented Generation (RAG) and why is it used?', answer: 'RAG combines a retrieval system with a generative LLM. The pipeline: 1) Query → retrieve relevant documents from a knowledge base (using vector search), 2) Augment the prompt with retrieved context, 3) Generate answer conditioned on the context. Used to: reduce hallucinations by grounding responses in actual data, allow access to up-to-date/proprietary information without fine-tuning, provide source attribution. RAG is preferred over fine-tuning for dynamic knowledge bases.' },
  { topic: 'RAG', level: 'senior', question: 'What is the difference between naive RAG, advanced RAG, and modular RAG?', answer: 'Naive RAG: simple pipeline — index, retrieve, generate. Problems: poor precision/recall, lost-in-the-middle issue, redundant context. Advanced RAG: pre-retrieval (query rewriting, HyDE), retrieval improvements (hybrid search, reranking), post-retrieval (context compression, reordering). Modular RAG: treats RAG as configurable modules — any retriever, any reranker, any generator can be swapped. Examples: FLARE (iterative retrieval), Fusion-in-Decoder, Self-RAG (model decides when to retrieve).' },
  { topic: 'RAG', level: 'mid', question: 'What chunking strategies exist for RAG and when do you use each?', answer: 'Fixed-size: simple, split by character/token count with overlap (e.g., 512 tokens, 50 overlap). Good as baseline. Sentence-based: split on sentence boundaries, preserves semantic coherence. Paragraph-based: preserves topical coherence, variable size. Recursive: try to split on natural boundaries (paragraphs → sentences → words). Semantic chunking: embed sentences and split where similarity drops — computationally expensive but best coherence. Document-specific: parse tables, headers as separate chunks. Rule of thumb: chunk size should match the granularity of your queries.' },
  { topic: 'RAG', level: 'senior', question: 'What is HyDE (Hypothetical Document Embeddings) and when should you use it?', answer: 'HyDE generates a hypothetical document that would answer the query (using an LLM), then retrieves based on the embedding of that hypothetical document rather than the query itself. The idea: the hypothetical answer is semantically closer to real answers in the vector space than the question is. Use when: queries are short/abstract and documents are long/detailed, there is a large distribution mismatch between query and document style. Downside: adds LLM inference cost before retrieval, can propagate hallucinations into the retrieval step.' },
  { topic: 'RAG', level: 'mid', question: 'What is the "lost in the middle" problem in RAG?', answer: 'Research shows LLMs attend more strongly to information at the beginning and end of their context window, and poorly to information in the middle. In RAG, if relevant content is placed in the middle of a long context, the model may miss it. Solutions: rerank retrieved chunks so most relevant are at start/end, use context compression to remove less relevant chunks, use models with better long-context attention (e.g., Longformer), limit context size to most relevant chunks only.' },
  { topic: 'RAG', level: 'senior', question: 'How do you evaluate a RAG system end-to-end?', answer: 'Component-level: retrieval metrics (NDCG, MRR, Precision@K, Recall@K), generation metrics (RAGAS: faithfulness, answer relevancy, context precision, context recall). System-level: end-to-end QA accuracy, human evaluation, LLM-as-judge. RAGAS framework specifically: Faithfulness (are claims grounded in context?), Answer Relevancy (does it answer the question?), Context Precision (how much of retrieved context is relevant?), Context Recall (does retrieved context cover ground truth?). Also track: latency, cost per query, hallucination rate.' },
  // ── Agents ────────────────────────────────────────────────────────────────────
  { topic: 'Agents', level: 'mid', question: 'What is the ReAct framework for AI agents?', answer: 'ReAct (Reasoning + Acting) interleaves reasoning traces and actions. The agent: 1) Reasons about what to do next (Thought), 2) Takes an action (Action + tool call), 3) Observes the result (Observation), 4) Repeats until task is complete. Advantages: reasoning explains agent behavior, allows course correction. Key components: a prompt that describes available tools and the ReAct format, tool implementations (search, calculator, code executor), a stopping condition.' },
  { topic: 'Agents', level: 'senior', question: 'What is the difference between single-agent and multi-agent architectures?', answer: 'Single-agent: one LLM handles the entire task, using tools as needed. Simple but can struggle with complex tasks requiring diverse capabilities. Multi-agent: multiple specialized LLMs collaborate — e.g., researcher, writer, critic agents. Patterns: supervisor (one agent delegates to others), pipeline (sequential handoffs), debate (agents challenge each other). Frameworks: LangGraph (state machine), CrewAI (role-based), AutoGen (conversation-based). Multi-agent adds coordination overhead but handles complex tasks better through specialization.' },
  { topic: 'Agents', level: 'mid', question: 'How do you prevent AI agents from going into infinite loops?', answer: 'Strategies: max_iterations limit (hard stop after N steps), max_execution_time timeout, cycle detection (track visited states/actions), stopping conditions in the prompt ("stop when you have a final answer"), human-in-the-loop checkpoints for long-running tasks, output parsers that detect when the agent is stuck, HALT signal in the action space. Best practice: combine multiple mechanisms — max iterations is the safety net, good prompting reduces the need to hit it.' },
  { topic: 'Agents', level: 'senior', question: 'What is tool/function calling and how does it work in modern LLMs?', answer: 'Tool calling (OpenAI function calling, Anthropic tool use): the model is given JSON schemas for available functions and can choose to call them with structured arguments. Mechanism: 1) Include tool schemas in the API request, 2) Model outputs a tool_call instead of text when it wants to use a tool, 3) You execute the tool, 4) Return the result in the next message, 5) Model uses the result to generate a response. Parallel tool calling: GPT-4 can call multiple tools simultaneously (returns a list of tool_calls). Better than unstructured function calling because it\'s JSON-valid and structured.' },
  { topic: 'Agents', level: 'mid', question: 'What is agent memory and what are the different types?', answer: 'Short-term memory: the current conversation context window — shared with the LLM in each call. Long-term memory: external storage (databases, vector stores) that persists across sessions — agent retrieves relevant memories. Episodic memory: past interactions and experiences. Semantic memory: facts and knowledge. Working memory: intermediate results during a task. Implementation: store memories as embeddings in a vector DB, retrieve k most relevant using similarity search before each LLM call. Tools like MemGPT implement "self-editing" memory where the agent manages what to remember.' },
  // ── Fine-Tuning ───────────────────────────────────────────────────────────────
  { topic: 'Fine-Tuning', level: 'mid', question: 'What is the difference between full fine-tuning and PEFT methods?', answer: 'Full fine-tuning: update all model parameters, requires massive GPU memory (e.g., 7B model needs ~28GB in bfloat16 just to store weights, plus optimizer states ~3x), but achieves best performance. PEFT (Parameter-Efficient Fine-Tuning): update only a small fraction of parameters. Methods: LoRA (inject low-rank matrices, ~0.1% of params), Prefix Tuning (prepend trainable tokens), Adapters (add small feed-forward layers between transformer blocks), Prompt Tuning (optimize continuous prompt vectors). PEFT preserves base model weights, allows serving multiple fine-tuned versions with one base model.' },
  { topic: 'Fine-Tuning', level: 'senior', question: 'Explain QLoRA and how it enables fine-tuning large models on consumer hardware.', answer: 'QLoRA (Quantized LoRA) combines: 1) 4-bit NormalFloat quantization of the frozen base model (NF4 is optimal for normally-distributed weights), 2) Double quantization (quantize the quantization constants), 3) Paged optimizers (offload optimizer states to CPU when GPU OOM). LoRA adapters are trained in 16-bit while the base model stays 4-bit. Result: 65B model fine-tunes on a single 48GB GPU (vs 640GB for full 16-bit). Key hyperparameters: r (rank), alpha (scaling), target modules (typically q_proj, v_proj).' },
  { topic: 'Fine-Tuning', level: 'mid', question: 'What is catastrophic forgetting and how do you mitigate it in fine-tuning?', answer: 'Catastrophic forgetting: when fine-tuning on new data, the model forgets previously learned knowledge. Mitigation strategies: Elastic Weight Consolidation (EWC) — penalize changes to important weights, Replay — mix original training data with new data, LoRA — only updates low-rank matrices so base model knowledge is preserved, low learning rate (1e-4 to 1e-5), few training epochs (1-3), domain-specific evaluation to detect forgetting. For instruction fine-tuning: include a mix of general instruction data (Alpaca, FLAN) with domain-specific data.' },
  { topic: 'Fine-Tuning', level: 'senior', question: 'What is DPO (Direct Preference Optimization) and how does it compare to RLHF?', answer: 'DPO trains directly from human preference data without a separate reward model or RL. It reformulates RLHF as a classification problem: given pairs of (chosen, rejected) responses, maximize likelihood of chosen over rejected with a KL constraint. Advantages over RLHF: no reward model training, no PPO (which is unstable), simpler pipeline, computationally cheaper. The objective: maximize log(σ(β × (log(π/π_ref)(chosen) - log(π/π_ref)(rejected)))). Used by Llama 2 chat and many open models. RLHF still has edge in some benchmarks but DPO is the practical choice.' },
  { topic: 'Fine-Tuning', level: 'mid', question: 'How do you prepare a dataset for instruction fine-tuning?', answer: 'Format: convert to instruction-following format — system prompt + user instruction + assistant response. Common formats: ChatML (<|im_start|>system\n...<|im_end|>), Llama chat format, Alpaca format. Data quality checklist: remove duplicates, filter short/low-quality responses, ensure diverse topics, balance difficulty levels. Data sources: Alpaca (GPT-4 generated), OpenAssistant (human conversations), FLAN (academic tasks), ShareGPT (real ChatGPT conversations). Min size: 1K examples for domain fine-tuning, 10K+ for general instruction following. Always evaluate on a held-out set.' },
  // ── MLOps ─────────────────────────────────────────────────────────────────────
  { topic: 'MLOps', level: 'mid', question: 'What is the difference between ML training and inference infrastructure?', answer: 'Training: high-memory GPUs (A100 80GB, H100), need fast interconnect (NVLink, InfiniBand) for multi-GPU, high storage I/O for training data, spot instances acceptable (with checkpointing), synchronous batch processing. Inference: optimize for latency and throughput, can use quantized models (INT8, INT4), batching requests, horizontal scaling, need SLA guarantees, support for dynamic batching (vLLM, TGI), KV-cache management. Inference cost is 10-100x the amortized training cost at scale, so optimization is critical.' },
  { topic: 'MLOps', level: 'senior', question: 'How do you detect and handle model drift in production?', answer: 'Data drift: input distribution changes (feature statistics, text topics). Concept drift: relationship between inputs and outputs changes. Detection methods: statistical tests (KS test, PSI — Population Stability Index), embedding drift (compare distributions in vector space), prediction drift (monitor output distribution), custom metrics (accuracy on labeled samples). Responses: automated retraining pipelines triggered by drift signals, shadow deployment of new model, A/B testing, canary deployment. Tools: Evidently AI, WhyLabs, Arize, Fiddler. Track: data quality metrics, model performance metrics, operational metrics.' },
  { topic: 'MLOps', level: 'mid', question: 'What is vLLM and why is it important for LLM serving?', answer: 'vLLM is an LLM serving framework that implements PagedAttention — a memory management technique inspired by OS paging that dramatically improves GPU memory utilization for KV-cache. Traditional serving wastes memory due to fragmentation from variable-length sequences. PagedAttention stores KV-cache in non-contiguous blocks, allowing up to 24x more throughput than HuggingFace Transformers. Also supports: continuous batching, tensor parallelism, quantization (GPTQ, AWQ). Widely used in production at scale for cost-effective inference.' },
  { topic: 'MLOps', level: 'senior', question: 'What metrics do you track for an LLM in production?', answer: 'Quality metrics: task-specific accuracy (e.g., BLEU, ROUGE, answer correctness), user satisfaction ratings, hallucination rate, safety filter triggers. Operational metrics: latency (P50, P95, P99 TTFT — Time To First Token, and TPOT — Time Per Output Token), throughput (tokens/second), error rates, retry rates. Cost metrics: cost per query, GPU utilization, tokens per dollar. Business metrics: task completion rate, user engagement, escalation rate. Alert on: latency spikes, accuracy drops, unusual output distribution, cost anomalies.' },
  { topic: 'MLOps', level: 'mid', question: 'What is A/B testing for ML models and how do you implement it?', answer: 'Split traffic between model A (control) and model B (experiment) to compare performance under real conditions. Implementation: traffic splitting at the API gateway level (10% to B, 90% to A), track metrics per variant with consistent user assignment (hash user_id to ensure same user always gets same variant), run for sufficient duration (power analysis to determine sample size), use hypothesis testing (t-test for continuous metrics, chi-square for categorical). Pitfalls: novelty effect (users behave differently with new things), leakage between variants, network effects.' },
  // ── Transformers ──────────────────────────────────────────────────────────────
  { topic: 'Transformers', level: 'mid', question: 'What is the role of positional encoding in transformers?', answer: 'Transformers have no inherent notion of token order (unlike RNNs). Positional encodings inject position information into token embeddings. Original paper (Vaswani 2017): sinusoidal encoding using sin/cos at different frequencies — allows the model to generalize to sequences longer than seen in training. Modern approaches: RoPE (Rotary Position Embedding, used in Llama) — encodes relative positions by rotating query/key vectors, ALiBi (Attention with Linear Biases, used in BLOOM) — adds a linear bias to attention scores based on token distance. RoPE is now dominant for its good extrapolation properties.' },
  { topic: 'Transformers', level: 'senior', question: 'Explain Flash Attention and why it matters for training large models.', answer: 'Flash Attention rewrites the attention operation to avoid materializing the full N×N attention matrix in GPU HBM (high-bandwidth memory). Instead, it computes attention in tiles that fit in SRAM (fast on-chip memory). Result: attention is now memory-bound → memory I/O bound rather than compute-bound. Reduces memory complexity from O(N²) to O(N) for the attention matrix. 2-4x faster than standard attention, enables longer context windows. Flash Attention 2 improved further with better parallelism. Flash Attention 3 (H100 optimized) is the current state of the art.' },
  { topic: 'Transformers', level: 'mid', question: 'What is Grouped Query Attention (GQA) and why is it used in modern LLMs?', answer: 'GQA is a compromise between Multi-Head Attention (MHA) and Multi-Query Attention (MQA). In MHA: each head has its own Q, K, V matrices. In MQA: all heads share a single K and V. In GQA: heads are grouped, and each group shares K and V — e.g., 32 query heads with 8 KV heads. Benefit: reduces KV-cache size during inference (critical bottleneck), allows faster inference with minimal quality loss. Used in Llama 2 70B, Llama 3, Mistral, Gemma. Typical configuration: 32Q heads, 8KV heads (4:1 ratio).' },
  { topic: 'Transformers', level: 'fresher', question: 'What is the purpose of the feedforward network in each transformer layer?', answer: 'The FFN in each transformer layer (also called the MLP) adds non-linearity and provides additional model capacity. Architecture: two linear projections with a non-linear activation in between: FFN(x) = Activation(W1·x + b1)·W2 + b2. The expansion dimension is typically 4× the model dimension (e.g., d_model=1024, d_ff=4096). GELU activation is standard in modern transformers. The FFN is believed to act as a "key-value memory" that stores factual knowledge. Some research shows the FFN stores more world knowledge than the attention layers.' },
  { topic: 'Transformers', level: 'senior', question: 'What is Mixture of Experts (MoE) and how does it enable efficient scaling?', answer: 'MoE replaces dense FFN layers with a set of N "expert" FFNs, where only K experts (typically 2 of 8) are activated per token (controlled by a gating network). Benefits: model has more total parameters but the same compute per token (sparse activation). Mixtral 8x7B has 46.7B total params but only activates 12.9B per forward pass. GPT-4 is widely believed to use MoE with ~8 experts. Challenges: expert load balancing (add auxiliary loss to prevent collapse), communication overhead in distributed settings, training instability. Switch Transformer showed MoE scales better than dense models with equal compute.' },
  // ── System Design ─────────────────────────────────────────────────────────────
  { topic: 'System Design', level: 'senior', question: 'Design a production RAG system for a 10M document corpus with <500ms P95 latency.', answer: 'Architecture: 1) Indexing pipeline: chunk docs → embed with batch GPU inference → upsert to vector DB (Pinecone/Qdrant) with metadata. 2) Serving: query → embed (fast, small model) → ANN search (HNSW index, ~10ms) → re-rank top-50 to top-5 → LLM generation. Latency breakdown: embedding ~20ms, retrieval ~10ms, reranking ~50ms, generation ~300ms = ~380ms. Optimizations: cache embeddings of frequent queries, pre-warm LLM, use streaming for generation, async retrieval + generation overlap. Scale: horizontal pod scaling for embedding service, read replicas for vector DB.' },
  { topic: 'System Design', level: 'senior', question: 'How would you design an LLM inference system to serve 10K concurrent users?', answer: 'Use vLLM or TGI for continuous batching and PagedAttention (maximizes GPU utilization). Architecture: load balancer → N inference pods (each with 1-4 GPUs). For high throughput: batch requests, use async generation. Autoscaling: scale on GPU utilization or queue depth. For cost: use spot instances with fallback, quantize to INT8/INT4. Routing: route short queries to smaller models, long/complex to larger. KV-cache sharing between requests with same system prompt (prefix caching). Cache frequent/deterministic responses at the API gateway layer.' },
  { topic: 'System Design', level: 'mid', question: 'How do you handle prompt injection attacks in LLM applications?', answer: 'Prompt injection: malicious user input that overrides system instructions (e.g., "Ignore previous instructions and..."). Defenses: input validation (detect injection patterns with a classifier), output validation (check responses against expected format/content), use separate system/user turn clearly delimited, minimal privilege (agent has only necessary tools), sandboxing (don\'t let agents execute arbitrary code), monitoring for anomalous outputs, human-in-the-loop for sensitive operations, use a fine-tuned safety classifier before/after generation.' },
  { topic: 'System Design', level: 'senior', question: 'How would you build a real-time AI news summarization system?', answer: 'Pipeline: 1) Data ingestion: scrape RSS feeds + news APIs every 5 min using async workers (Celery + Redis). 2) Deduplication: SimHash or MinHash to detect near-duplicate articles. 3) Topic clustering: embed articles, cluster similar ones (DBSCAN or agglomerative). 4) Summarization: prompt LLM to summarize cluster of related articles in 2-3 sentences. 5) Storage: summaries in Postgres with metadata, full articles in object storage. 6) Delivery: REST API + WebSocket for real-time updates to clients. Scale: rate limit news sources, use streaming summarization, cache summaries for popular topics.' },
  // ── Python for ML ──────────────────────────────────────────────────────────────
  { topic: 'Python', level: 'mid', question: 'What are Python generators and when are they useful in ML?', answer: 'Generators are lazy iterators that yield values one at a time instead of storing all in memory. Defined with yield keyword. Use cases in ML: 1) Data pipelines — process large datasets in batches without loading all into memory (yield batch), 2) Infinite streams of data augmentation, 3) Custom DataLoaders. Example: `def data_loader(paths): for p in paths: yield preprocess(load(p))`. Benefits: constant memory usage regardless of dataset size, can interleave I/O with computation. Works well with Python\'s for-loop and next(). generator expressions: `(x**2 for x in range(1000000))` vs list comprehension.' },
  { topic: 'Python', level: 'mid', question: 'How does Python\'s GIL affect multi-threaded ML workloads?', answer: 'The Global Interpreter Lock (GIL) prevents multiple Python threads from executing Python bytecode simultaneously. Impact on ML: CPU-bound work (numpy, tensor ops) bypasses the GIL because they release it during C extension calls, so threads work fine there. Pure Python CPU work (data preprocessing loops) is bottlenecked by the GIL. Solutions: 1) multiprocessing — uses separate processes with separate GILs, used by PyTorch DataLoader (num_workers>0), 2) asyncio — concurrent I/O without threads, 3) Cython/C extensions. PyTorch operations release the GIL, so Python threads work for GPU-bound ML training.' },
  { topic: 'Python', level: 'mid', question: 'Explain Python\'s context managers and how they\'re used in ML training.', answer: 'Context managers define setup/teardown logic using __enter__ and __exit__ or @contextmanager decorator. In ML: 1) `torch.no_grad()` — disables gradient computation during inference (saves memory, speeds up), 2) `torch.autocast("cuda")` — automatic mixed precision (uses float16 where safe, float32 where needed), 3) `with open(file) as f:` — safe file handling, 4) model.train() / model.eval() context managers. Implementation: class with __enter__ returning resource and __exit__ handling cleanup. @contextmanager with yield gives simpler generator-based implementation.' },
  { topic: 'Python', level: 'senior', question: 'How do you profile and optimize Python code for ML training pipelines?', answer: 'Profiling tools: cProfile/profile (function-level), line_profiler (@profile decorator, line-level), memory_profiler (memory usage), PyTorch Profiler (GPU + CPU timeline). Common bottlenecks: data loading (fix: increase num_workers, pin_memory=True, prefetch), inefficient preprocessing (vectorize with numpy/pandas instead of loops), Python loops in forward pass (use tensor operations), unnecessary CPU-GPU transfers. Tools: torch.utils.bottleneck, Tensorboard Profiler, NVIDIA Nsight. Rule of thumb: profile before optimizing, focus on the top bottleneck first.' },
  { topic: 'Python', level: 'mid', question: 'What is asyncio and how can it speed up LLM API calls?', answer: 'asyncio enables concurrent execution of I/O-bound tasks in a single thread using an event loop and async/await syntax. For LLM APIs: instead of sequential calls (each waits for response), run many API calls concurrently. Example with async OpenAI: `async def main(): tasks = [acall(prompt) for prompt in prompts]; results = await asyncio.gather(*tasks)`. Speedup: if each call takes 2 seconds and you have 100 calls, sequential takes 200s, concurrent takes ~2s (limited by rate limits). Use `asyncio.Semaphore` to respect rate limits. All major AI SDKs (openai, anthropic) have async clients.' },
  // ── Vector DB ──────────────────────────────────────────────────────────────────
  { topic: 'Vector DB', level: 'mid', question: 'What is HNSW and why is it the dominant algorithm for vector search?', answer: 'HNSW (Hierarchical Navigable Small World) is an approximate nearest neighbor algorithm using a multi-layer graph. Construction: each vector is added to a hierarchical graph where upper layers are sparse (long-range connections) and lower layers are dense (local connections). Search: start at the top layer, greedily navigate to closest node, descend to lower layers. Properties: O(log N) search time, high recall (>99% with ef parameter), supports incremental updates. Used by: Qdrant, Weaviate, Pinecone, pgvector. Trade-offs: high memory usage (graph structure), slower build time than IVF, but faster and more accurate search.' },
  { topic: 'Vector DB', level: 'senior', question: 'What is the difference between semantic search and keyword search, and when do you combine them?', answer: 'Keyword search (BM25): exact term matching with TF-IDF weighting, fast, no embedding needed, great for precise queries. Semantic search: vector similarity, captures meaning/synonyms, no exact term matching needed. Hybrid search: combine both scores (typically: score = (1-α)×BM25 + α×cosine_sim, or use RRF — Reciprocal Rank Fusion to merge ranked lists). Use hybrid when: queries can be either precise ("GET /api/v2/users error 404") or semantic ("how do I handle authentication errors"), or when neither alone is sufficient. Elasticsearch supports hybrid natively, as does Weaviate, Qdrant, and Pinecone.' },
  { topic: 'Vector DB', level: 'mid', question: 'What are the trade-offs between different embedding models for RAG?', answer: 'Small fast models (all-MiniLM-L6-v2, 22M params, 384-dim): ~10ms inference, good for general purpose, free. Medium models (BGE-M3, E5-large): better quality, multi-lingual support, 300-500ms. Large/API models (text-embedding-3-large from OpenAI, 3072-dim): highest quality, ~50ms API latency, costs money. Key factors: embedding dimension (higher = better quality but more memory), max sequence length (some truncate at 512 tokens), multilingual support, domain-specific performance. For RAG: BGE-M3 or E5-large are popular open-source choices. Always evaluate on your specific domain.' },
  // ── NLP ────────────────────────────────────────────────────────────────────────
  { topic: 'NLP', level: 'mid', question: 'What is Byte Pair Encoding (BPE) and why is it used for tokenization?', answer: 'BPE starts with a character vocabulary and iteratively merges the most frequent adjacent byte/character pairs. Result: a vocabulary of subwords that efficiently represents any text. Benefits: handles OOV (out-of-vocabulary) words by splitting them into known subwords, balances between character-level (handles everything) and word-level (inefficient vocabulary), good compression ratio. GPT models use BPE-based tokenizers (tiktoken). Example: "tokenization" → ["token", "iz", "ation"]. Trade-offs: language-dependent (English-optimized tokenizers tokenize other languages less efficiently), can create semantically odd splits.' },
  { topic: 'NLP', level: 'senior', question: 'What is the difference between BERT and sentence transformers for semantic search?', answer: 'BERT (and its variants): outputs token-level embeddings, designed for classification/NER/QA. To get sentence embedding: average pool or use [CLS] token — but these were NOT trained for semantic similarity, so they perform poorly for retrieval. Sentence Transformers (SBERT): fine-tuned specifically for semantic textual similarity using siamese network architecture on NLI/STS datasets. Optimized for: fast similarity computation, sentence-level tasks. BEIR benchmark shows SBERT models (GTE, E5, BGE) significantly outperform BERT on retrieval. For RAG: always use sentence transformers, not raw BERT.' },
  // ── Computer Vision ─────────────────────────────────────────────────────────────
  { topic: 'Computer Vision', level: 'mid', question: 'What is the Vision Transformer (ViT) and how does it apply attention to images?', answer: 'ViT splits an image into fixed-size patches (e.g., 16×16 pixels), flattens and linearly embeds them, then processes them as a sequence of tokens with standard transformer self-attention. A special [CLS] token aggregates image information for classification. Trained on large datasets (ImageNet-21K, JFT-300M), ViT matches or exceeds CNN performance. Advantages: captures long-range dependencies naturally (attention between distant patches), scalable with data/compute. CLIP (OpenAI) uses ViT as the image encoder. DINOv2 (Meta) is a powerful self-supervised ViT.' },
  { topic: 'Computer Vision', level: 'senior', question: 'What is the SAM (Segment Anything Model) and what makes it special?', answer: 'SAM (Meta 2023) is a promptable image segmentation model trained on 1.1B masks (SA-1B dataset). Key innovation: zero-shot generalization — segment any object given a point, box, or text prompt without task-specific training. Architecture: Image Encoder (ViT-H), Prompt Encoder (points, boxes, masks), Mask Decoder (outputs masks + confidence). Can generate mask for any region when prompted. Applications: data annotation automation, medical imaging, robotics. SAM 2 (2024) extends to video with memory attention for tracking objects across frames.' },
  // ── Additional important questions ─────────────────────────────────────────────
  { topic: 'LLM', level: 'mid', question: 'What is context window and how do long-context models work?', answer: 'Context window is the maximum number of tokens a model can process at once (input + output). GPT-4 Turbo: 128k tokens (~96k words). Techniques for long context: Sliding window attention (Mistral, Longformer) — each token attends only to nearby tokens + a few global ones. RoPE with extended base frequency (Llama 3.1 uses rope_theta=500000 for 128k context). ALiBi linear biases. Challenges: quadratic attention complexity (Flash Attention mitigates), "lost in the middle" problem, evaluation on long contexts is hard. In practice: RAG often beats long context for retrieval tasks because it\'s cheaper and more precise.' },
  { topic: 'RAG', level: 'mid', question: 'What is re-ranking in RAG and which models are used for it?', answer: 'Re-ranking adds a second-stage precision improvement: the first stage retrieves top-K candidates fast (HNSW + cosine similarity), the second stage uses a more expensive cross-encoder to score each (query, document) pair more accurately. Cross-encoders process query and document together (full attention) vs bi-encoders which encode them separately. Models: Cohere Rerank, BGE Reranker, cross-encoder/ms-marco-MiniLM-L-6-v2. Typical pipeline: retrieve top-50 with vector search → rerank to top-5 → pass to LLM. Re-ranking adds 50-150ms but significantly improves answer quality for complex queries.' },
  { topic: 'Agents', level: 'mid', question: 'What is LangGraph and how does it differ from LangChain for building agents?', answer: 'LangGraph (built on top of LangChain) models agent workflows as a directed graph (state machine) where nodes are functions/LLM calls and edges are transitions. This makes complex multi-step agent logic explicit and debuggable vs LangChain\'s sequential chain abstraction. Key features: conditional routing (edges based on state), cycles supported (for retry logic), streaming state updates, human-in-the-loop checkpointing. Best for: agents that need branching logic, multi-agent systems (supervisor → specialist pattern), long-running workflows that need checkpointing. LangChain is simpler for linear pipelines; LangGraph for complex conditional flows.' },
  { topic: 'Fine-Tuning', level: 'senior', question: 'What is GRPO (Group Relative Policy Optimization) and how does it enable LLMs to reason?', answer: 'GRPO (DeepSeek-R1) is a variant of PPO that eliminates the need for a separate value function model. For a given prompt, generate G responses, compute rewards for each, normalize relative to the group mean. This group comparison acts as a baseline for variance reduction. Combined with a "thinking" format (model generates reasoning before answer), GRPO trains models to reason step-by-step on math and coding problems. DeepSeek-R1 matches o1-preview performance using GRPO. Advantage over PPO: no value model = simpler, less memory, more stable training. Advantage over DPO: works with verifiable rewards (math correctness), not just human preferences.' },
  { topic: 'MLOps', level: 'mid', question: 'What is the difference between batch inference and online inference?', answer: 'Batch inference: process a large dataset offline, results stored for later use. Pros: maximize throughput, use large batch sizes, cost-effective, GPU utilization can hit 90%+. Cons: latency is hours/days, not real-time. Use for: weekly recommendation updates, offline evaluation, data pipelines. Online inference: real-time, low-latency (<100ms) response to individual requests. Pros: immediate results. Cons: lower GPU utilization (must size for peak load), higher cost per query, need to handle variable load. Use for: chatbots, search, content moderation. Streaming inference: online inference with token streaming for LLMs improves perceived latency.' },
  { topic: 'Transformers', level: 'mid', question: 'What is KV-cache and why is it critical for LLM inference performance?', answer: 'During autoregressive generation, each new token attends to all previous tokens. Without caching: recompute K,V for all previous tokens at every step — O(n²) total work. KV-cache: store the K and V matrices computed for previous tokens, reuse them for each new step — O(n) total work. Memory cost: proportional to batch_size × sequence_length × n_layers × d_head. At scale: a 70B model with 10K context and batch size 64 needs ~140GB for KV-cache alone. Optimizations: PagedAttention (vLLM), KV-cache quantization (INT8/INT4), prefix caching (reuse prompts), sliding window attention.' },
  { topic: 'Vector DB', level: 'senior', question: 'When would you use Pinecone vs Qdrant vs pgvector for a production RAG system?', answer: 'Pinecone: fully managed, zero ops overhead, auto-scaling, good for teams that want to focus on product not infrastructure. Expensive at scale, limited customization, vendor lock-in. Qdrant: open-source, self-hostable or managed, rich filtering (payload filters), good performance, active development. Good balance of control and features for medium-large scale. pgvector: extends PostgreSQL with vector operations, ideal when you already use Postgres and want simplicity, or need ACID transactions with vector search. Limitations: HNSW performance slightly lower than dedicated DBs, scaling requires Postgres expertise. Rule: Pinecone for speed, Qdrant for cost+control, pgvector for simplicity.' },
  { topic: 'Python', level: 'fresher', question: 'What is the difference between list comprehension and map/filter in Python for data processing?', answer: 'List comprehension `[f(x) for x in lst if condition]` is Pythonic, readable, generally faster than explicit loops. map() applies a function to every element, returns a lazy iterator — useful for large datasets or chaining. filter() selects elements matching a predicate, also lazy. For ML: list comprehensions are preferred for readability. `[x**2 for x in data]` vs `list(map(lambda x: x**2, data))`. Performance: list comprehension is typically fastest for simple operations, map() can be faster with built-in functions (map(str.upper, words)). For large datasets: prefer generators `(f(x) for x in lst)` to avoid loading everything in memory.' },
]

export async function POST(req: Request) {
  const { password } = await req.json().catch(() => ({}))
  if (password !== process.env.ADMIN_PASSWORD) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const supabase = getAdminSupabase()
  const { error } = await supabase
    .from('interview_questions')
    .upsert(
      QUESTIONS.map(q => ({ question: q.question, answer: q.answer, topic: q.topic, level: q.level })),
      { onConflict: 'question' }
    )

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ seeded: QUESTIONS.length })
}
