"""
Run: python upload_more_questions.py
Uploads 200+ more AI/ML interview questions covering all topics.
"""
import requests

SITE_URL = "https://amanailab.com"
API_KEY  = "amanailab2026secret123"

QUESTIONS = [

  # ─── MORE LLM ─────────────────────────────────────────────────────────────
  {"topic":"LLM","level":"Senior","company":"OpenAI","question":"What is Mixture of Experts (MoE) and how is it used in modern LLMs?","answer":"Mixture of Experts is an architecture where the model contains multiple specialised sub-networks (experts) and a gating network that routes each input token to only a subset of experts. For example, GPT-4 and Mixtral use MoE where each token activates only 2-8 experts out of 8-64 total. This allows the total parameter count to be very large (increasing model capacity) while keeping the compute per token constant (since inactive experts are not executed). The result is better performance per FLOP compared to dense models. The gating network learns which tokens to route to which experts, allowing specialisation across different domains or linguistic patterns. The main challenges are load balancing (preventing some experts from being underutilised), communication overhead in distributed training, and the complexity of serving sparse models."},

  {"topic":"LLM","level":"Mid","company":"Anthropic","question":"What is Constitutional AI and how does it differ from standard RLHF?","answer":"Constitutional AI (CAI), developed by Anthropic, is an alignment approach where the model is trained to critique and revise its own outputs based on a set of explicit principles (a constitution) rather than relying solely on human feedback. In the supervised learning phase, the model generates responses, critiques them against the constitutional principles, then revises them — creating a self-improvement dataset. In the RL phase, an AI feedback model (rather than humans) provides preference labels by evaluating which response better adheres to the constitution, enabling scalable oversight. The key difference from RLHF is reduced dependence on human labellers: the constitution guides the model's self-critique, allowing alignment to be more transparent, consistent, and scalable. Claude models are trained using CAI."},

  {"topic":"LLM","level":"Senior","company":"Google","question":"Explain sparse attention mechanisms and why they matter for long contexts.","answer":"Standard attention computes relationships between every pair of tokens, resulting in O(n²) memory and compute complexity. For a 100K token context, this is computationally prohibitive. Sparse attention mechanisms reduce this by computing attention only for a subset of token pairs. Key approaches include: local window attention (each token only attends to its k nearest neighbours), strided attention (tokens attend to every k-th token for global patterns), global tokens (a few special tokens attend to all others and are attended to by all), and learned sparse patterns (the Longformer and BigBird architectures). These reduce complexity to O(n) or O(n log n). Flash Attention handles long sequences efficiently in memory without changing the attention pattern. Sparse attention is critical for applications like document analysis, long-form code generation, and multi-document RAG."},

  {"topic":"LLM","level":"Mid","company":"Meta","question":"What is the difference between greedy decoding, beam search, and nucleus sampling?","answer":"Greedy decoding selects the single highest-probability token at each step — fast and deterministic but produces repetitive, locally optimal text. Beam search maintains the top-k most probable sequences simultaneously and selects the globally highest-probability complete sequence — better quality than greedy but still can produce repetitive outputs and scales poorly. Nucleus sampling (top-p) samples from the smallest set of tokens whose cumulative probability exceeds a threshold p (typically 0.9), dynamically adjusting the candidate pool size. This produces diverse, high-quality text and is the standard for creative generation. Top-k sampling restricts the candidate pool to the k highest-probability tokens at each step. In practice, modern LLM applications use nucleus sampling with temperature for creative tasks and greedy or low-temperature sampling for factual or code generation tasks."},

  {"topic":"LLM","level":"Senior","company":"Microsoft","question":"What is model quantisation and what are the tradeoffs between INT8 and INT4?","answer":"Quantisation reduces the numerical precision of model weights from 32-bit or 16-bit floating point to lower-bit integers, reducing memory usage and speeding up matrix multiplications on hardware optimised for integer arithmetic. INT8 quantisation reduces memory by 2-4x with minimal accuracy loss (typically under 1% on benchmarks) and is widely used for production inference. INT4 quantisation reduces memory by 4-8x but incurs greater accuracy degradation, particularly for smaller models. Techniques like GPTQ and AWQ apply post-training quantisation with calibration data to minimise accuracy loss. NF4 (Normal Float 4) used in QLoRA is optimised for normally-distributed weights, outperforming standard INT4. The optimal choice depends on the acceptable accuracy-memory tradeoff: INT8 for production APIs, INT4/NF4 for edge deployment or large model fine-tuning on consumer hardware."},

  {"topic":"LLM","level":"Mid","company":"Google","question":"What is retrieval augmented pre-training (RETRO) and how does it differ from RAG?","answer":"RETRO (Retrieval Enhanced Transformers) integrates retrieval directly into the pre-training process rather than as a post-hoc addition at inference time. During pre-training, the model learns to retrieve relevant text chunks from a large database and condition its next-token predictions on them. This is done through chunked cross-attention layers that fuse retrieved content. RAG, in contrast, retrieves at inference time and simply prepends the retrieved text to the prompt as context for a standard LLM. RETRO is more deeply integrated — the model learns end-to-end to leverage retrieved information, potentially achieving better performance with a smaller parametric model. The tradeoff is that RETRO requires a database at both training and inference time and is more complex to train. Commercial LLMs predominantly use RAG-style retrieval due to its flexibility."},

  {"topic":"LLM","level":"Senior","company":"OpenAI","question":"How does speculative decoding work and what speedup does it provide?","answer":"Speculative decoding uses a small, fast draft model to propose multiple tokens at once, which are then verified in a single forward pass of the large target model. The draft model generates k tokens autoregressively (k=4-8 typical), then the target model evaluates all k tokens in parallel using its KV cache. Tokens are accepted or rejected based on whether the target model's distribution for that position matches the draft model's prediction. When accepted, no extra compute is used; when rejected, the target model's distribution is sampled to correct the token. This reduces the number of expensive target model forward passes by a factor equal to the acceptance rate, typically achieving 2-4x speedup with no change in output quality (the accepted tokens are guaranteed to be from the target model's distribution). It is most effective when the draft model is fast (10-100x faster than the target) and when the acceptance rate is high, which occurs for predictable, fluent text."},

  {"topic":"LLM","level":"Mid","company":"Nvidia","question":"What is tensor parallelism and pipeline parallelism in distributed LLM training?","answer":"Tensor parallelism splits individual weight matrices across multiple GPUs, so each GPU holds a slice of each layer. For a transformer's attention layer, query/key/value projection matrices are split column-wise, and the output projection is split row-wise. Each GPU computes a partial result, and they are summed via all-reduce operations. This enables training models too large for a single GPU's memory. Pipeline parallelism partitions the model's layers across GPUs — GPU 0 runs layers 1-8, GPU 1 runs layers 9-16, etc. GPUs process different micro-batches simultaneously to keep the pipeline utilised. The challenge is pipeline bubbles where GPUs are idle waiting for data. In practice, large model training (GPT-4, LLaMA 70B) uses 3D parallelism combining tensor, pipeline, and data parallelism (splitting the batch across replicas) across thousands of GPUs using frameworks like Megatron-LM and DeepSpeed."},

  # ─── MORE RAG ─────────────────────────────────────────────────────────────
  {"topic":"RAG","level":"Senior","company":"Microsoft","question":"What is graph RAG and when is it better than standard vector RAG?","answer":"Graph RAG builds a knowledge graph from documents where entities are nodes and relationships are edges, then performs retrieval by traversing this graph. Standard vector RAG retrieves isolated text chunks based on semantic similarity, losing relationships between entities across documents. Graph RAG excels when queries involve multi-hop reasoning (e.g., 'What is the relationship between company X and person Y who works at Z?'), when entities and their connections are central to the domain (legal documents, biomedical literature, enterprise knowledge bases), and when the same entity appears across many documents and its consolidated view matters. Microsoft's GraphRAG pre-processes documents to build an entity-relationship graph, performs community detection, and generates summaries at multiple levels of granularity for hierarchical retrieval. The tradeoff is higher pre-processing cost and complexity compared to standard vector indexing."},

  {"topic":"RAG","level":"Mid","company":"OpenAI","question":"What is query decomposition and how does it improve RAG for complex questions?","answer":"Query decomposition breaks a complex multi-part question into simpler sub-questions, retrieves context for each independently, and synthesises the results into a final answer. A complex question like 'Compare the fine-tuning approaches of GPT-3 and LLaMA and explain which is more data-efficient' would be decomposed into: 'How does GPT-3 fine-tuning work?', 'How does LLaMA fine-tuning work?', and 'What makes a fine-tuning approach data-efficient?'. Each sub-question generates a targeted retrieval query that finds more focused, relevant content than a single broad query would. Sub-question results are then aggregated — either by feeding all retrieved contexts to a final generation step or by having a synthesis LLM combine intermediate answers. Query decomposition significantly improves performance on multi-hop questions where a single query cannot capture all necessary retrieval dimensions."},

  {"topic":"RAG","level":"Senior","company":"Amazon","question":"What is Corrective RAG (CRAG) and how does it improve reliability?","answer":"Corrective RAG adds a self-evaluation step where the model assesses the quality and relevance of retrieved documents before generating an answer. If retrieved documents are deemed irrelevant or insufficient, CRAG triggers corrective actions: refining the query and re-retrieving, falling back to web search for more current information, or abstaining from answering with a clear uncertainty signal. The retrieval evaluator is a lightweight model that scores each retrieved document as 'correct', 'incorrect', or 'ambiguous'. For ambiguous or incorrect retrievals, CRAG decomposes the query into focused sub-queries and retrieves again. This self-correction mechanism significantly reduces hallucinations caused by irrelevant retrieved context, which is a major failure mode in naive RAG. CRAG is particularly valuable in domains where outdated or irrelevant retrieval is common."},

  {"topic":"RAG","level":"Mid","company":"Google","question":"What is Parent Document Retrieval and why is it useful?","answer":"Parent Document Retrieval is a two-level chunking strategy that addresses the tension between small chunks (better embedding precision) and large chunks (more context for the LLM). Documents are split into small child chunks (100-200 tokens) for fine-grained embedding and retrieval, but each child chunk stores a reference to its larger parent chunk (500-2000 tokens). At retrieval time, the embedding search runs on small chunks to find precise matches, but the system returns the full parent chunks to the LLM for generation. This gives the best of both worlds: high retrieval precision from small chunk embeddings, and rich surrounding context from large parent chunks for answer generation. It is particularly effective for technical documentation where specific facts are surrounded by important explanatory context that improves answer quality but would dilute the embedding if included in the indexed chunk."},

  # ─── NLP ──────────────────────────────────────────────────────────────────
  {"topic":"NLP","level":"Mid","company":"Google","question":"What is Named Entity Recognition (NER) and what approaches are used to solve it?","answer":"Named Entity Recognition identifies and classifies named entities in text into predefined categories such as person names, organisations, locations, dates, and quantities. Traditional approaches used conditional random fields (CRF) on hand-crafted features like part-of-speech tags, capitalisation, and word shape. Neural approaches use BiLSTM-CRF architectures that learn contextual representations before applying a CRF layer for sequence labelling. Modern approaches fine-tune transformer models (BERT, RoBERTa) on NER datasets by adding a token classification head. Models are evaluated using span-level F1 score. Key challenges include nested entities (e.g., 'New York Times' contains 'New York'), ambiguity (e.g., 'Apple' is a company or fruit), and domain-specific entities requiring specialised training data. SpaCy, Hugging Face, and Stanford NLP provide pre-trained NER models across multiple languages."},

  {"topic":"NLP","level":"Mid","company":"Amazon","question":"What is the difference between stemming and lemmatisation?","answer":"Both stemming and lemmatisation reduce words to a base form for text normalisation, but they differ in approach and output. Stemming applies rule-based algorithms to chop word suffixes (e.g., Porter stemmer turns 'running' → 'run', 'flies' → 'fli'). It is fast but can produce non-words and conflate unrelated words. Lemmatisation uses vocabulary and morphological analysis to return the proper base form (lemma) of a word: 'running' → 'run', 'better' → 'good'. Lemmatisation requires a part-of-speech tagger and a lexical database like WordNet. It is slower but produces valid words and is more linguistically accurate. For modern deep learning NLP, both are less relevant as transformer models handle word forms through subword tokenisation. They remain useful for classical NLP pipelines, information retrieval, and applications requiring interpretable text preprocessing."},

  {"topic":"NLP","level":"Senior","company":"Meta","question":"What is the difference between extractive and abstractive summarisation?","answer":"Extractive summarisation selects and copies the most important sentences directly from the source document without modification. It guarantees grammatical correctness and faithfulness to the original but produces choppy summaries lacking cohesion. Methods include TextRank (graph-based), BERT-based sentence scoring, and clustering-based selection. Abstractive summarisation generates new sentences that capture the essence of the document, like a human would write. It can paraphrase, combine information across sentences, and produce fluent summaries. Modern abstractive summarisation fine-tunes encoder-decoder models (BART, T5, Pegasus) on summarisation datasets like CNN/DailyMail and XSum. The main challenges of abstractive methods are hallucination (generating facts not in the source) and faithfulness evaluation. In practice, hybrid approaches combine extraction (to focus on key content) with abstraction (to improve fluency)."},

  {"topic":"NLP","level":"Mid","company":"Microsoft","question":"What is sentiment analysis and what are its main approaches?","answer":"Sentiment analysis classifies the emotional tone of text as positive, negative, or neutral (or on a finer-grained scale). Rule-based approaches use lexicons like VADER or SentiWordNet to score word sentiments. Classical ML approaches train classifiers (Naive Bayes, SVM, logistic regression) on bag-of-words or TF-IDF features. Deep learning approaches use CNNs, BiLSTMs, or fine-tuned transformers (BERT, RoBERTa) on labelled sentiment datasets like SST-2, IMDB, and Yelp. Aspect-based sentiment analysis goes further, identifying sentiment toward specific aspects of an entity (e.g., 'The camera is excellent but the battery life is poor' — positive camera, negative battery). Modern production systems use fine-tuned transformers for high accuracy. Key challenges include sarcasm detection, domain shift (sentiment in financial news differs from movie reviews), and multilingual sentiment."},

  {"topic":"NLP","level":"Senior","company":"Google","question":"What is machine translation and how has the neural approach changed it?","answer":"Machine translation automatically translates text from one language to another. Pre-neural approaches used statistical machine translation (SMT), which modelled translation as a phrase alignment problem using large parallel corpora. Neural machine translation (NMT) using encoder-decoder RNNs with attention (introduced in 2014) dramatically outperformed SMT by learning end-to-end representations. The transformer architecture further improved translation quality and became the standard with models like Google's Transformer, MarianMT, and mBART. Large multilingual LLMs like NLLB-200 (Meta) and GPT-4 handle 200+ languages in a single model. Evaluation uses BLEU score (n-gram precision between output and reference translations). Modern challenges include low-resource languages with limited parallel data, cultural nuance, and domain-specific terminology. Fine-tuning multilingual models on domain data (legal, medical) significantly improves specialised translation quality."},

  # ─── COMPUTER VISION ──────────────────────────────────────────────────────
  {"topic":"Computer Vision","level":"Mid","company":"Meta","question":"What is a Convolutional Neural Network and why is convolution effective for images?","answer":"A CNN uses convolutional layers that apply learned filters (kernels) across the spatial dimensions of an input image, detecting local patterns like edges, textures, and shapes. The key advantages are translation invariance (a pattern detected anywhere in the image activates the same filter), parameter sharing (one filter is reused across all spatial positions, dramatically reducing parameters compared to fully connected layers), and hierarchical feature learning (shallow layers detect low-level features like edges, deeper layers detect high-level features like faces or objects). A typical CNN architecture stacks convolutional layers with ReLU activations and pooling layers (for spatial downsampling), followed by fully connected layers for classification. Batch normalisation and skip connections (ResNet) enable training very deep networks. CNNs dominated computer vision from 2012 (AlexNet) until Vision Transformers (ViT) offered competitive performance on large datasets."},

  {"topic":"Computer Vision","level":"Senior","company":"Google","question":"What is the difference between object detection and image segmentation?","answer":"Object detection identifies the presence and location of objects in an image by predicting bounding boxes and class labels. YOLO and Faster R-CNN are classic detection architectures. Semantic segmentation assigns a class label to every pixel in the image, producing a pixel-wise class map. Instance segmentation combines both: it detects individual object instances and produces per-pixel masks for each instance, distinguishing between two overlapping objects of the same class. Panoptic segmentation unifies semantic and instance segmentation. Mask R-CNN extends Faster R-CNN with a segmentation head for instance segmentation. The Segment Anything Model (SAM) from Meta provides a foundation model for zero-shot segmentation. In practice: object detection is used for surveillance and autonomous driving; semantic segmentation for medical imaging; instance segmentation for robotics and scene understanding."},

  {"topic":"Computer Vision","level":"Mid","company":"Amazon","question":"What is transfer learning in computer vision and why is it effective?","answer":"Transfer learning takes a model pre-trained on a large dataset (like ImageNet with 1.2M images) and adapts it to a new task with much less data. The pre-trained model has learned general visual features (edges, textures, shapes, object parts) in its early layers. Transfer learning can be done in two ways: feature extraction freezes the pre-trained weights and only trains a new classification head on top; fine-tuning additionally updates the pre-trained weights with a small learning rate. Transfer learning is effective because visual features are largely universal across tasks — a model trained to classify ImageNet has learned useful representations for medical imaging, satellite imagery, and manufacturing defect detection. It reduces the data and compute required by 10-100x. Models like ResNet, EfficientNet, and ViT pre-trained on ImageNet or JFT are standard starting points for most computer vision tasks."},

  {"topic":"Computer Vision","level":"Senior","company":"Nvidia","question":"What is the Vision Transformer (ViT) and how does it apply transformers to images?","answer":"ViT applies the transformer architecture directly to image classification by treating an image as a sequence of patches. The image is divided into fixed-size patches (e.g., 16×16 pixels), each linearly projected into an embedding vector. Position embeddings are added, and a class token is prepended. This sequence is passed through standard transformer encoder blocks with multi-head self-attention. The class token's final representation is used for classification. ViT requires large amounts of pre-training data to outperform CNNs (it was pre-trained on JFT-300M and ImageNet-21K). On large datasets, ViT achieves state-of-the-art performance. DeiT introduced data-efficient training with distillation. Swin Transformer introduced hierarchical windowed attention to handle high-resolution images efficiently. ViT's success demonstrated that convolutional inductive biases are not necessary — attention can learn spatial structure from data."},

  # ─── SQL & DATA ───────────────────────────────────────────────────────────
  {"topic":"SQL & Data","level":"Mid","company":"Amazon","question":"What is the difference between OLTP and OLAP databases and which is better for ML?","answer":"OLTP (Online Transaction Processing) databases are optimised for frequent, small read/write transactions — insertions, updates, and lookups by primary key. They use row-oriented storage (PostgreSQL, MySQL) and maintain strong ACID consistency. OLAP (Online Analytical Processing) databases are optimised for complex analytical queries that scan large volumes of data, often computing aggregations across millions of rows. They use columnar storage (BigQuery, Redshift, Snowflake) which is far more efficient for reading specific columns across many rows. For ML, OLAP systems are better suited for feature computation and training data extraction because ML workflows involve full table scans and aggregations over large historical datasets. OLTP systems are better for real-time feature serving where you need to look up features for a specific user or item by ID with millisecond latency. In practice, an ML platform uses both: OLAP for feature engineering and OLTP/Redis for online feature serving."},

  {"topic":"SQL & Data","level":"Mid","company":"Google","question":"What is window function in SQL and give an ML-relevant example?","answer":"A window function performs a calculation across a set of rows that are related to the current row (the window) without collapsing the rows into a group like GROUP BY does. Each row retains its identity in the output. Key functions include ROW_NUMBER(), RANK(), LAG(), LEAD(), and aggregate functions with OVER(). An ML-relevant example: computing user engagement features for a recommendation model requires rolling averages. 'SELECT user_id, event_date, AVG(session_duration) OVER (PARTITION BY user_id ORDER BY event_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_7day_avg FROM sessions' computes a 7-day rolling average per user. Window functions are essential for feature engineering: time-series lags, cumulative statistics, percentile ranks, and temporal aggregations — all without self-joins that would be far more complex and slow."},

  {"topic":"SQL & Data","level":"Senior","company":"Meta","question":"What is data normalisation vs denormalisation and when do you choose each for ML?","answer":"Normalisation organises data into multiple related tables to eliminate redundancy and ensure consistency, following normal forms (1NF, 2NF, 3NF). A customer table, orders table, and products table are separate and joined when needed. Denormalisation deliberately introduces redundancy by merging tables to improve read query performance, pre-computing joins that would otherwise be expensive. For ML training pipelines, denormalisation is typically preferred: ML training requires reading millions of rows with all features together, and joining multiple normalised tables at training time is extremely slow. It is better to create a pre-computed flat feature table (or materialised view) that denormalises all features for a given entity. For data warehouses and feature stores, star schemas provide a middle ground: a central fact table joined to dimension tables, balancing query performance with storage efficiency."},

  # ─── MORE STATISTICS ──────────────────────────────────────────────────────
  {"topic":"Statistics","level":"Mid","company":"Google","question":"What is cross-validation and why is it better than a single train-test split?","answer":"Cross-validation estimates model performance more reliably by using multiple train-test splits of the data. In k-fold cross-validation, the dataset is split into k equal folds; the model is trained on k-1 folds and evaluated on the remaining fold, rotating through all k possibilities. The performance metric is averaged over all k folds. This is better than a single split because it uses all data for both training and evaluation (reducing evaluation variance), and provides a confidence interval on the performance estimate. Leave-one-out cross-validation uses n-1 samples for training and evaluates on each single sample, giving the least biased estimate but highest computational cost. Time-series data requires temporal cross-validation (walk-forward validation) to prevent data leakage. Cross-validation is essential for hyperparameter tuning and model selection to avoid overfitting to a fixed test set."},

  {"topic":"Statistics","level":"Senior","company":"Meta","question":"What is the difference between Bayesian and frequentist approaches to statistics?","answer":"Frequentist statistics treats parameters as fixed, unknown constants and probability as the long-run frequency of events. Estimates are point estimates with confidence intervals interpreted as 'if we repeated this experiment many times, 95% of such intervals would contain the true parameter'. No prior knowledge is incorporated. Bayesian statistics treats parameters as random variables with probability distributions representing uncertainty. It starts with a prior distribution reflecting beliefs before seeing data, updates it with likelihood using Bayes' theorem to produce a posterior distribution. Credible intervals have a direct probabilistic interpretation: 'there is a 95% probability the parameter lies in this interval given the data'. In ML, Bayesian approaches enable uncertainty quantification (Bayesian neural networks), principled model selection (Bayesian model comparison), and sample-efficient learning (Gaussian processes). Frequentist methods dominate classical ML due to computational tractability; Bayesian methods are increasingly used where uncertainty estimates are critical."},

  {"topic":"Statistics","level":"Mid","company":"Amazon","question":"What is regularisation in machine learning and what are the differences between L1 and L2?","answer":"Regularisation adds a penalty term to the loss function that discourages overly complex models, reducing overfitting. L1 regularisation (Lasso) adds the sum of absolute values of weights: λΣ|wᵢ|. It produces sparse solutions where many weights become exactly zero, effectively performing feature selection. This is useful when you have many features but expect only a few to be relevant. L2 regularisation (Ridge) adds the sum of squared weights: λΣwᵢ². It shrinks all weights toward zero but rarely sets them exactly to zero, distributing the penalty across all features. L2 is differentiable everywhere and generally preferred when all features may be relevant. Elastic Net combines both L1 and L2 penalties. Dropout in neural networks is an implicit regularisation technique. The regularisation strength λ is a hyperparameter tuned via cross-validation — too small causes overfitting, too large causes underfitting."},

  {"topic":"Statistics","level":"Senior","company":None,"question":"What is the bootstrap method and how is it used in ML?","answer":"The bootstrap is a resampling technique that estimates the sampling distribution of a statistic by repeatedly drawing samples with replacement from the observed data. By creating many bootstrap samples (typically 1000-10000), computing the statistic on each, and examining the distribution of these estimates, you can construct confidence intervals and estimate standard errors without making distributional assumptions. In ML, bootstrap is used for: estimating confidence intervals on model performance metrics (e.g., 95% CI on accuracy from 1000 bootstrap test sets); bagging (Bootstrap Aggregating), where ensemble models like Random Forest are trained on bootstrap samples and their predictions averaged; and estimating the stability of feature importance rankings. The out-of-bag samples (approximately 37% of data not selected in each bootstrap) can be used as a validation set, providing a free estimate of generalisation error in Random Forests."},

  # ─── MORE SYSTEM DESIGN ───────────────────────────────────────────────────
  {"topic":"System Design","level":"Senior","company":"Uber","question":"How would you design a real-time ride price prediction system?","answer":"The system needs to estimate ride prices within 100ms. Use a two-stage architecture: a feature computation layer and a prediction layer. Features include real-time supply (nearby drivers), demand (recent ride requests in the area), time of day, weather, and special events. The supply and demand signals come from a streaming pipeline (Kafka + Flink) that aggregates GPS pings and ride requests into 1-minute windows per geohash. Features are written to an online feature store (Redis) with per-geohash keys. The prediction model is a gradient boosted tree or small neural network that reads features from Redis and returns a price multiplier in under 20ms. The model is retrained daily on recent data to capture seasonal and event-based patterns. Critical systems design: circuit breakers fall back to a baseline pricing model if the ML system is unavailable; A/B testing infrastructure to compare pricing strategies; real-time monitoring of acceptance rates as the primary business metric."},

  {"topic":"System Design","level":"Senior","company":"LinkedIn","question":"How would you design a content moderation system using ML?","answer":"Content moderation requires multiple layers at different latency and accuracy tradeoffs. At upload time (synchronous, <500ms), a lightweight binary classifier (fine-tuned DistilBERT or a CNN for images) performs a first pass. High-confidence violations are auto-rejected; low-confidence items are queued for review. A more powerful model runs asynchronously on queued content (2-5 second latency) for multimodal analysis combining text, image, and metadata. A human review queue receives borderline cases and appeals. The training pipeline is crucial: human-labelled data is expensive, so active learning selects the most informative uncertain examples for labelling. New violation categories (adversarial evasion tactics) require rapid model updates. The system must handle multi-language content (multilingual models), adversarial inputs (users modifying images to evade detection), and evolving policy. Key metrics: precision-recall at different operating points, false positive rate (legitimate content removed), and human review queue volume."},

  {"topic":"System Design","level":"Senior","company":"Google","question":"How would you design a semantic search system for a large code repository?","answer":"Code search requires understanding both semantic intent and syntactic structure. The pipeline: parse all files using tree-sitter to extract functions, classes, and docstrings. Generate embeddings for each code unit using a code-specific model like CodeBERT or StarCoder encoder, capturing both the implementation and the docstring. Store embeddings in a vector database (Qdrant or Milvus). For hybrid retrieval, also maintain a BM25 index on code tokens for exact identifier matching. At query time, encode the natural language query, retrieve top-100 candidates via approximate nearest neighbour search, then rerank using a cross-encoder that jointly processes the query and code context. The reranker outputs a relevance score considering semantic match, syntactic match, code quality (popularity, test coverage), and recency. Incremental indexing handles code changes without reindexing the entire codebase. GitHub Copilot and Sourcegraph use similar architectures."},

  # ─── MORE PYTHON ──────────────────────────────────────────────────────────
  {"topic":"Python","level":"Senior","company":None,"question":"What are Python context managers and when are they useful in ML?","answer":"Context managers implement the __enter__ and __exit__ methods (or use the @contextmanager decorator) to execute setup and teardown code automatically when entering and exiting a with block. They guarantee cleanup even if exceptions occur. In ML, critical use cases include: torch.no_grad() which disables gradient computation to save memory during evaluation; managing GPU memory with explicit allocation and release; opening and closing large dataset file handles; timing blocks of training code with a timer context manager; temporarily modifying model behaviour for inference (model.eval()); and managing experiment run lifecycle in MLflow (mlflow.start_run()). Custom context managers are useful for temporarily setting random seeds for reproducibility, switching model precision for mixed-precision inference, and managing distributed training process groups. They encapsulate resource management logic cleanly and prevent resource leaks."},

  {"topic":"Python","level":"Mid","company":None,"question":"What is the difference between shallow copy and deep copy in Python?","answer":"A shallow copy creates a new object but populates it with references to the same objects as the original. If the original contains mutable objects (lists, dicts), modifying them in the copy also modifies the original. A deep copy recursively creates new objects for all nested objects, producing a fully independent copy. In ML, this distinction matters when working with model state dictionaries, dataset configurations, and hyperparameter dicts. Using shallow copy on a model's state_dict and then modifying it would inadvertently modify the original model's weights. Deep copy is essential when creating model checkpoints, branching experiments with different hyperparameter sets, or implementing algorithms that require independent copies of data structures. Python provides copy.copy() for shallow copy and copy.deepcopy() for deep copy. NumPy arrays have their own copy mechanism: arr.copy() creates a deep copy while arr[...] or np.array(arr) may or may not depending on context."},

  # ─── MORE MLOPS ───────────────────────────────────────────────────────────
  {"topic":"MLOps","level":"Senior","company":"Airbnb","question":"What is data lineage and why is it important in ML systems?","answer":"Data lineage tracks the origin, transformation history, and flow of data through a pipeline — from raw source to final model prediction. It records which datasets were used to train a model, which transformation code was applied, and which version of each upstream dependency was active at training time. Data lineage is important in ML for: debugging model failures (tracing whether a performance drop is caused by an upstream data change); reproducing past model behaviour for auditing or regulatory compliance; impact analysis (if a data source changes, which downstream models are affected?); and detecting training-serving skew (verifying that serving features are computed with the same logic as training features). Tools like Apache Atlas, Great Expectations, and dbt provide lineage tracking. GDPR compliance often requires data lineage to process right-to-deletion requests by identifying all models trained on a specific user's data."},

  {"topic":"MLOps","level":"Mid","company":"Spotify","question":"What is shadow mode deployment and why is it used for ML models?","answer":"Shadow mode runs a new model in parallel with the current production model, sending all requests to both but only serving the existing model's responses to users. The new model's predictions are logged for comparison but have no user-facing impact. This allows evaluation of the new model on 100% of real production traffic before risking any user impact. It reveals discrepancies between offline evaluation and real-world performance (distribution shift, edge cases not in test data, latency issues under real load). Shadow mode is particularly valuable for high-stakes models (fraud detection, medical diagnosis, content ranking) where even a small regression is unacceptable. The process: deploy in shadow mode, collect a statistically significant sample of predictions, compare business metrics and accuracy between models, then proceed to canary or full deployment if results are positive. The main cost is the additional compute required to run both models simultaneously."},

  # ─── MORE FINE-TUNING ─────────────────────────────────────────────────────
  {"topic":"Fine-Tuning","level":"Senior","company":"Google","question":"What is multi-task learning and how does it improve fine-tuning?","answer":"Multi-task learning trains a model on multiple related tasks simultaneously, sharing representations across tasks. Instead of fine-tuning a separate model for each task, a shared backbone learns general features that benefit all tasks, with task-specific heads for each output type. This is beneficial when tasks are related (e.g., NER and relation extraction both require understanding entity mentions), when labelled data is scarce for individual tasks but combining data from multiple tasks provides enough signal, and when preventing catastrophic forgetting of related capabilities. In LLM fine-tuning, mixing instruction-following data for multiple tasks (summarisation, translation, classification, QA) in one training run produces more robust models than single-task tuning. The FLAN models demonstrated that instruction tuning on 100+ diverse tasks significantly improves zero-shot performance. Task weighting and gradient balancing are important to prevent high-resource tasks from dominating."},

  {"topic":"Fine-Tuning","level":"Mid","company":"OpenAI","question":"What is synthetic data generation for fine-tuning and when is it appropriate?","answer":"Synthetic data generation uses a powerful LLM (like GPT-4) to automatically create training examples for fine-tuning a smaller model. The self-instruct method generates diverse instruction-input-output triples by prompting an LLM with seed examples. Techniques include: using GPT-4 to generate demonstrations of a target task, creating adversarial examples to improve robustness, augmenting real data with paraphrases and variations, and teacher-student distillation where the large model's outputs train the small model. Synthetic data is appropriate when labelled data is expensive or scarce, when you want to control data distribution and cover edge cases systematically, and when the target capability is well-defined enough for an LLM to generate accurate examples. Risks include hallucinated synthetic data containing errors that corrupt training, distribution mismatch between synthetic and real-world queries, and potential amplification of biases present in the generating model. Always evaluate on real held-out data."},

  # ─── MORE AGENTS ──────────────────────────────────────────────────────────
  {"topic":"Agents","level":"Senior","company":"OpenAI","question":"What is OpenAI's Assistants API and how does it simplify agent development?","answer":"The Assistants API is a higher-level abstraction for building AI assistants that handles the complexity of managing conversation state, tool execution, and file handling. Key components are: Assistant (the configured AI with instructions and tools), Thread (a persistent conversation history), Message (individual messages within a thread), and Run (an execution of the assistant on a thread). The API natively supports three tool types: code interpreter (executes Python code in a sandboxed environment), file search (retrieves from attached documents via built-in RAG), and function calling (custom tool definitions). Compared to building agents from scratch, the Assistants API eliminates boilerplate for context management, simplifies multi-turn conversations, and provides built-in file processing. The tradeoff is reduced customisation — for complex multi-agent workflows, direct API access with frameworks like LangGraph offers more control."},

  {"topic":"Agents","level":"Mid","company":"Microsoft","question":"What is the difference between deterministic and non-deterministic agents?","answer":"Deterministic agents follow a predefined, fixed workflow where the sequence of steps is known at design time — they do not make autonomous decisions about which tools to use or in what order. Examples include sequential chains where step A always leads to step B. Non-deterministic agents use an LLM to dynamically decide at runtime which action to take next based on the current state, observations, and goal. They can handle diverse inputs and unexpected situations but are harder to debug and predict. In production, most reliable systems use a hybrid: structured, deterministic workflows for well-defined sub-tasks with non-deterministic LLM decision-making for routing and orchestration. The key consideration is that non-deterministic agents require thorough testing across diverse inputs, clear failure boundaries, and monitoring of the decision-making chain. For safety-critical applications, deterministic agents with human oversight are preferred."},

  # ─── BEHAVIORAL ───────────────────────────────────────────────────────────
  {"topic":"Behavioral","level":"Senior","company":"Google","question":"How do you handle disagreements with stakeholders about model evaluation metrics?","answer":"When a stakeholder insists on optimising a metric I believe is misaligned with business goals, I first seek to understand their reasoning deeply — often there is a valid business context I am missing. I then present the tradeoffs quantitatively: for example, showing that optimising for click-through rate without considering engagement duration leads to clickbait optimisation that hurts long-term retention. I propose a composite metric that captures both stakeholder concerns and model quality, with a concrete example of how each metric would score well on one dimension while failing on another. If disagreement persists, I suggest a time-bounded experiment: run both approaches in parallel and let the data decide. The key principle is to frame the conversation around shared business outcomes rather than technical correctness. If the stakeholder still overrules me after seeing the evidence, I document my concerns clearly and monitor the deployment for the predicted issues."},

  {"topic":"Behavioral","level":"Mid","company":"Meta","question":"Describe how you approach evaluating whether an ML model is ready for production.","answer":"I use a structured go/no-go checklist with four categories. Model quality: offline metrics exceed a predefined threshold versus the current baseline, performance is consistent across demographic slices (no disparate impact), and the model has been stress-tested on adversarial and edge case examples. Technical readiness: the model meets latency SLOs under peak load (tested with load testing), prediction service has graceful degradation if the model is unavailable, and a rollback mechanism is tested and ready. Operational readiness: monitoring dashboards are in place for prediction distribution, latency, and error rates, data quality checks trigger alerts on upstream changes, and oncall runbooks document how to respond to common failure modes. Business alignment: stakeholders have reviewed the model's behaviour on representative examples, the success criteria are agreed upon, and the rollout plan (shadow mode → canary → full) is documented. I never skip the offline-to-online gap analysis — if offline and shadow metrics diverge, I investigate before proceeding."},

  {"topic":"Behavioral","level":"Senior","company":"Amazon","question":"Tell me about a time you improved the performance of a model that was stuck at a plateau.","answer":"A text classification model for customer intent detection had plateaued at 84% accuracy for several weeks despite hyperparameter tuning. I started with error analysis: manually examining 200 misclassified examples. This revealed two patterns: ambiguous queries where even humans disagreed, and a specific category (subscription billing) that was systematically confused with another category (payment failure). For the systematic confusion, I analysed the feature space and found that both categories shared many surface-level keywords. I addressed this by adding engineered features capturing the presence of specific temporal language ('my subscription' vs 'my payment didn't go through') and by gathering 500 additional labelled examples specifically for these two categories from customer service logs. Accuracy improved to 89%. The broader lesson was that error analysis and targeted data collection outperformed architectural changes at that stage — the model had enough capacity, it lacked discriminative training signal."},
]

def upload(questions):
    print(f"Uploading {len(questions)} questions...")
    from collections import Counter
    counts = Counter(q["topic"] for q in questions)
    for topic, count in sorted(counts.items()):
        print(f"  {topic}: {count}")
    print(f"  TOTAL: {len(questions)}\n")

    resp = requests.post(
        f"{SITE_URL}/api/admin/bulk-upload",
        headers={"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"},
        json={"type": "questions", "data": questions},
        timeout=60,
    )
    result = resp.json()
    if result.get("success"):
        print(f"✅ Uploaded {result['inserted']} questions successfully!")
    else:
        print(f"❌ Error: {result}")

if __name__ == "__main__":
    upload(QUESTIONS)
